### ISSUE TITLE
Convert Tensorflow model failed 

### ISSUE THREAD

**Issue by rogerou** [XiaoMi/mace#109]
------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS
- **NDK version(e.g., 15c)**:r16b
- **GCC version(if compiling for host, e.g., 5.4.0)**: GCC 4.2.1
- **MACE version (Use the command: git describe --long --tags)**: master
- **Python version(2.7)**: 2.7
- **Bazel version (e.g., 0.13.0)**:0.15.2

### Model deploy file (*.yml)
```yaml
# The name of library
library_name: 1.1.0.170918_alpha_landmark
target_abis: [armeabi-v7a]
model_graph_format: file
model_data_format: file
models:
  mobilenet_v1: # model tag, which will be used in model loading and must be specific.
    platform: tensorflow
    # path to your tensorflow model's pb file. Support local path, http:// and https://
    model_file_path: /Users/ouzhijie/Downloads/1.1.0.170918_alpha_landmark.pb
    # sha256_checksum of your model's pb file.
    # use this command to get the sha256_checksum: sha256sum path/to/your/pb/file
    model_sha256_checksum: fba7bb3b3a39545ebf9462c8ecef402e27093f9d0547d8d41eb2604158fbae17 
    # define your model's interface
    # if there multiple inputs or outputs, write like blow:
    # subgraphs:
    # - input_tensors:
    #     - input0
    #     - input1
    #   input_shapes:
    #     - 1,224,224,3
    #     - 1,224,224,3
    #    output_tensors:
    #      - output0
    #      - output1
    #    output_shapes:
    #      - 1,1001
    #      - 1,1001
    subgraphs:
      - input_tensors:
          - input_imgs
        input_shapes:
          - 1,112,112,3
        output_tensors:
          - final_output
        output_shapes:
          - 1,171
    # cpu, gpu or cpu+gpu
    runtime: cpu+gpu
    winograd: 4
```

### Describe the problem
convert tensorflow model failed
### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
mace_output_node_final_output (ImageToBuffer): []
start optimize gpu memory.
Traceback (most recent call last):
  File "/Users/ouzhijie/Documents/WorkSpace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 300, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/Users/ouzhijie/Documents/WorkSpace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 158, in main
    memory_optimizer.optimize_gpu_memory(output_graph_def)
  File "/Users/ouzhijie/Documents/WorkSpace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/memory_optimizer.py", line 227, in optimize_gpu_memory
    mem_optimizer.optimize()
  File "/Users/ouzhijie/Documents/WorkSpace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/memory_optimizer.py", line 112, in optimize
    op.output_shape[i].dims)
  File "/Users/ouzhijie/Documents/WorkSpace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/memory_optimizer.py", line 192, in get_op_mem_block
    mem_block[0] = output_shape[2]
  File "/private/var/tmp/_bazel_ouzhijie/e37d1db59dd99bf6e7b4652ee6375961/execroot/mace/bazel-out/darwin-fastbuild/bin/mace/python/tools/converter.runfiles/com_google_protobuf/python/google/protobuf/internal/containers.py", line 204, in __getitem__
    return self._values[key]
IndexError: list index out of range
Traceback (most recent call last):
  File "tools/converter.py", line 1595, in <module>
    flags.func(flags)
  File "tools/converter.py", line 785, in convert_func
    convert_model(configs)
  File "tools/converter.py", line 711, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/Users/ouzhijie/Documents/WorkSpace/mace/tools/sh_commands.py", line 524, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1:
```

**Comment by liyinhgqw** [comment]
Can you add some log and see at which op it failed?

**Comment by rogerou** [comment]
All the logs here :
```bash
Transform model to one that can better run on device
convert reshape and matmul to fc
convert matmul to fc
convert matmul to fc
convert matmul to fc
Transform gpu winograd conv_6/convolution(Conv2D)
Transform gpu winograd conv_8/convolution(Conv2D)
Fold biasadd: conv_1/convolution(Conv2D)
Fold biasadd: conv_2/convolution(Conv2D)
Fold biasadd: conv_3/convolution(Conv2D)
Fold biasadd: conv_4/convolution(Conv2D)
Fold biasadd: conv_5/convolution(Conv2D)
Fold biasadd: conv_7/convolution(Conv2D)
Fold biasadd: fc/fc_2/MatMul(FullyConnected)
Fold biasadd: fc/fc_4/MatMul(FullyConnected)
Fold biasadd: fc/fc_5/MatMul(FullyConnected)
Fold biasadd: fc/fc_3/MatMul(FullyConnected)
Fold biasadd: conv_6/convolution_inverse_transform(WinogradInverseTransform)
Fold biasadd: conv_8/convolution_inverse_transform(WinogradInverseTransform)
Transpose filters to OIHW
Reshape fully connected weight shape
Transform buffer to image
update op with float data type
Sort by execution
Final ops:
conv_8/weights_0_b2i (BufferToImage): []
conv_6/weights_0_b2i (BufferToImage): []
input_imgs (BufferToImage): [[1L, 112L, 112L, 3L]]
div (Eltwise): [[1L, 112L, 112L, 3L]]
sub (Eltwise): [[1L, 112L, 112L, 3L]]
conv_1/weights_0_b2i (BufferToImage): []
conv_1/biases_0_b2i (BufferToImage): []
conv_1/convolution (Conv2D): [[1L, 56L, 56L, 16L]]
conv_1/Relu (Activation): [[1L, 56L, 56L, 16L]]
conv_1/Neg/_0__cf__0_0_b2i (BufferToImage): []
conv_1/Neg_1 (Eltwise): [[1L, 56L, 56L, 16L]]
conv_1/Relu_1 (Activation): [[1L, 56L, 56L, 16L]]
conv_1/mul (Eltwise): [[1L, 56L, 56L, 16L]]
conv_1/add (Eltwise): [[1L, 56L, 56L, 16L]]
conv_2/weights_0_b2i (BufferToImage): []
conv_2/biases_0_b2i (BufferToImage): []
conv_2/convolution (Conv2D): [[1L, 56L, 56L, 16L]]
conv_2/Relu (Activation): [[1L, 56L, 56L, 16L]]
conv_2/Neg/_1__cf__1_0_b2i (BufferToImage): []
conv_2/Neg_1 (Eltwise): [[1L, 56L, 56L, 16L]]
conv_2/Relu_1 (Activation): [[1L, 56L, 56L, 16L]]
conv_2/mul (Eltwise): [[1L, 56L, 56L, 16L]]
conv_2/add (Eltwise): [[1L, 56L, 56L, 16L]]
conv_3/weights_0_b2i (BufferToImage): []
conv_3/biases_0_b2i (BufferToImage): []
conv_3/convolution (Conv2D): [[1L, 28L, 28L, 16L]]
conv_3/Relu (Activation): [[1L, 28L, 28L, 16L]]
conv_3/Neg/_2__cf__2_0_b2i (BufferToImage): []
conv_3/Neg_1 (Eltwise): [[1L, 28L, 28L, 16L]]
conv_3/Relu_1 (Activation): [[1L, 28L, 28L, 16L]]
conv_3/mul (Eltwise): [[1L, 28L, 28L, 16L]]
conv_3/add (Eltwise): [[1L, 28L, 28L, 16L]]
conv_4/weights_0_b2i (BufferToImage): []
conv_4/biases_0_b2i (BufferToImage): []
conv_4/convolution (Conv2D): [[1L, 28L, 28L, 16L]]
conv_4/Relu (Activation): [[1L, 28L, 28L, 16L]]
conv_4/Neg/_3__cf__3_0_b2i (BufferToImage): []
conv_4/Neg_1 (Eltwise): [[1L, 28L, 28L, 16L]]
conv_4/Relu_1 (Activation): [[1L, 28L, 28L, 16L]]
conv_4/mul (Eltwise): [[1L, 28L, 28L, 16L]]
conv_4/add (Eltwise): [[1L, 28L, 28L, 16L]]
conv_5/weights_0_b2i (BufferToImage): []
conv_5/biases_0_b2i (BufferToImage): []
conv_5/convolution (Conv2D): [[1L, 14L, 14L, 32L]]
conv_5/Relu (Activation): [[1L, 14L, 14L, 32L]]
conv_5/Neg/_4__cf__4_0_b2i (BufferToImage): []
conv_5/Neg_1 (Eltwise): [[1L, 14L, 14L, 32L]]
conv_5/Relu_1 (Activation): [[1L, 14L, 14L, 32L]]
conv_5/mul (Eltwise): [[1L, 14L, 14L, 32L]]
conv_5/add (Eltwise): [[1L, 14L, 14L, 32L]]
conv_6/convolution_input_transform (WinogradTransform): [[36L, 32L, 16L]]
conv_6/convolution_matmul (MatMul): [[36L, 64L, 16L]]
conv_6/biases_0_b2i (BufferToImage): []
conv_6/convolution_inverse_transform (WinogradInverseTransform): [[1L, 14L, 14L, 64L]]
conv_6/Relu (Activation): [[1L, 14L, 14L, 64L]]
conv_6/Neg/_5__cf__5_0_b2i (BufferToImage): []
conv_6/Neg_1 (Eltwise): [[1L, 14L, 14L, 64L]]
conv_6/Relu_1 (Activation): [[1L, 14L, 14L, 64L]]
conv_6/mul (Eltwise): [[1L, 14L, 14L, 64L]]
conv_6/add (Eltwise): [[1L, 14L, 14L, 64L]]
conv_7/weights_0_b2i (BufferToImage): []
conv_7/biases_0_b2i (BufferToImage): []
conv_7/convolution (Conv2D): [[1L, 7L, 7L, 64L]]
conv_7/Relu (Activation): [[1L, 7L, 7L, 64L]]
conv_7/Neg/_6__cf__6_0_b2i (BufferToImage): []
conv_7/Neg_1 (Eltwise): [[1L, 7L, 7L, 64L]]
conv_7/Relu_1 (Activation): [[1L, 7L, 7L, 64L]]
conv_7/mul (Eltwise): [[1L, 7L, 7L, 64L]]
conv_7/add (Eltwise): [[1L, 7L, 7L, 64L]]
conv_8/convolution_input_transform (WinogradTransform): [[36L, 64L, 4L]]
conv_8/convolution_matmul (MatMul): [[36L, 128L, 4L]]
conv_8/biases_0_b2i (BufferToImage): []
conv_8/convolution_inverse_transform (WinogradInverseTransform): [[1L, 7L, 7L, 128L]]
conv_8/Relu (Activation): [[1L, 7L, 7L, 128L]]
conv_8/Neg/_7__cf__7_0_b2i (BufferToImage): []
conv_8/Neg_1 (Eltwise): [[1L, 7L, 7L, 128L]]
conv_8/Relu_1 (Activation): [[1L, 7L, 7L, 128L]]
conv_8/mul (Eltwise): [[1L, 7L, 7L, 128L]]
conv_8/add (Eltwise): [[1L, 7L, 7L, 128L]]
max_pooling_1/MaxPool (Pooling): [[1L, 3L, 3L, 128L]]
fc/fc_0/MatMul (MatMul): [[1L, 512L]]
fc/fc_0/biases_0_b2i (BufferToImage): []
fc/fc_0/BiasAdd (BiasAdd): [[1L, 512L]]
fc/fc_0/Relu (Activation): [[1L, 512L]]
fc/fc_0/Neg/_8__cf__8_0_b2i (BufferToImage): []
fc/fc_0/Neg_1 (Eltwise): [[1L, 512L]]
fc/fc_0/Relu_1 (Activation): [[1L, 512L]]
fc/fc_0/mul (Eltwise): [[1L, 512L]]
fc/fc_0/add (Eltwise): [[1L, 512L]]
fc/fc_3/weights_0_b2i (BufferToImage): []
fc/fc_3/biases_0_b2i (BufferToImage): []
fc/fc_3/MatMul (FullyConnected): [[1L, 166L]]
fc/fc_2/weights_0_b2i (BufferToImage): []
fc/fc_2/biases_0_b2i (BufferToImage): []
fc/fc_2/MatMul (FullyConnected): [[1L, 128L]]
fc/fc_2/Relu (Activation): [[1L, 128L]]
fc/fc_2/Neg/_10__cf__10_0_b2i (BufferToImage): []
fc/fc_2/Neg_1 (Eltwise): [[1L, 128L]]
fc/fc_2/Relu_1 (Activation): [[1L, 128L]]
fc/fc_2/mul (Eltwise): [[1L, 128L]]
fc/fc_2/add (Eltwise): [[1L, 128L]]
fc/fc_4/weights_0_b2i (BufferToImage): []
fc/fc_4/biases_0_b2i (BufferToImage): []
fc/fc_4/MatMul (FullyConnected): [[1L, 2L]]
fc/fc_1/MatMul (MatMul): [[1L, 128L]]
fc/fc_1/biases_0_b2i (BufferToImage): []
fc/fc_1/BiasAdd (BiasAdd): [[1L, 128L]]
fc/fc_1/Relu (Activation): [[1L, 128L]]
fc/fc_1/Neg/_9__cf__9_0_b2i (BufferToImage): []
fc/fc_1/Neg_1 (Eltwise): [[1L, 128L]]
fc/fc_1/Relu_1 (Activation): [[1L, 128L]]
fc/fc_1/mul (Eltwise): [[1L, 128L]]
fc/fc_1/add (Eltwise): [[1L, 128L]]
fc/fc_5/weights_0_b2i (BufferToImage): []
fc/fc_5/biases_0_b2i (BufferToImage): []
fc/fc_5/MatMul (FullyConnected): [[1L, 3L]]
network_output (Concat): [[1L, 171L]]
final_output (Reshape): [[1L, 171L]]
mace_output_node_final_output (ImageToBuffer): []
start optimize gpu memory.
Traceback (most recent call last):
  File "/Users/ouzhijie/Documents/WorkSpace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 300, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/Users/ouzhijie/Documents/WorkSpace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 158, in main
    memory_optimizer.optimize_gpu_memory(output_graph_def)
  File "/Users/ouzhijie/Documents/WorkSpace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/memory_optimizer.py", line 227, in optimize_gpu_memory
    mem_optimizer.optimize()
  File "/Users/ouzhijie/Documents/WorkSpace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/memory_optimizer.py", line 112, in optimize
    op.output_shape[i].dims)
  File "/Users/ouzhijie/Documents/WorkSpace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/memory_optimizer.py", line 192, in get_op_mem_block
    mem_block[0] = output_shape[2]
  File "/private/var/tmp/_bazel_ouzhijie/e37d1db59dd99bf6e7b4652ee6375961/execroot/mace/bazel-out/darwin-fastbuild/bin/mace/python/tools/converter.runfiles/com_google_protobuf/python/google/protobuf/internal/containers.py", line 204, in __getitem__
    return self._values[key]
IndexError: list index out of range
Traceback (most recent call last):
  File "tools/converter.py", line 1595, in <module>
    flags.func(flags)
  File "tools/converter.py", line 785, in convert_func
    convert_model(configs)
  File "tools/converter.py", line 711, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/Users/ouzhijie/Documents/WorkSpace/mace/tools/sh_commands.py", line 524, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1:

  RAN: /usr/local/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=/Users/ouzhijie/Downloads/1.1.0.170918_alpha_landmark.pb --weight_file= --model_checksum=e77bbd3a2cfe071eef174df696956866c75eced9960a9425ea369294c0944a99 --weight_checksum= --input_node=input_imgs --output_node=final_output --runtime=cpu+gpu --template=mace/python/tools --model_tag=mobilenet_v1 --input_shape=1,112,112,3 --dsp_mode=0 --embed_model_data=False --winograd=4 --obfuscate=0 --output_dir=mace/codegen/models/mobilenet_v1 --model_graph_format=file --data_type=fp16_fp32 --graph_optimize_options=

  STDOUT:


  STDERR: 
```

**Comment by nolanliou** [comment]
```
max_pooling_1/MaxPool (Pooling): [[1L, 3L, 3L, 128L]]
fc/fc_0/MatMul (MatMul): [[1L, 512L]]
```
Is there a `Rehape` Op between above two layers in you tensorflow model?

**Comment by liyinhgqw** [comment]
Can you provide models snippet of your proto text around `max_pooling_1/MaxPool` and
`fc/fc_0/MatMul (MatMul): [[1L, 512L]]`

**Comment by rogerou** [comment]
I am not sure is this node:
 ```bash
node {
  name: "flat_1/Reshape"
  op: "Reshape"
  input: "max_pooling_1/MaxPool"
  input: "flat_1/concat"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "Tshape"
    value {
      type: DT_INT32
    }
  }
}
```

**Comment by rogerou** [comment]
node {
  name: "gradients_1/max_pooling_1/MaxPool_grad/MaxPoolGrad"
  op: "MaxPoolGrad"
  input: "conv_8/add"
  input: "max_pooling_1/MaxPool"
  input: "gradients_1/flat_1/Reshape_grad/Reshape"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }

**Comment by wuyajun19900627** [comment]
I have the same problem,have you solved it ?@rogerou

**Comment by liyinhgqw** [comment]
@rogerou ， the model you pasted, is it the model after optimization (using tensorflow transform_graph)?

**Comment by rogerou** [comment]
model struct with optimization @liyinhgqw 
```tensorboard
graph/max_pooling_1
Subgraph: 1 nodes
Attributes (0)
Inputs (1)
graph/conv_8/add ?×?×?×128
Outputs (1)
graph/flat_1/Reshape ?×?×?×128
```
```tensorboard
graph/flat_1/Reshape/shape
Operation: Const
Attributes (2)
dtype
{"type":"DT_INT32"}
value
{"tensor":{"dtype":"DT_INT32","tensor_shape":{"dim":[{"size":2}]},"tensor_content":"\\377\\377\\377\\377\\200\\004\\000\\000"}}
Inputs (0)
Outputs (0)
```
```tensorboard
graph/flat_1/Reshape
Operation: Reshape
Attributes (2)
T
{"type":"DT_FLOAT"}
Tshape
{"type":"DT_INT32"}
Inputs (2)
graph/max_pooling_1/MaxPool ?×?×?×128
graph/flat_1/Reshape/shape 2
Outputs (3)
graph/fc/fc_2/MatMul ?×1152
graph/fc/fc_1/MatMul ?×1152
graph/fc/fc_0/MatMul ?×1152

```

**Comment by liyinhgqw** [comment]
Could you attach your optimized model to help us debug this issue?

**Comment by rogerou** [comment]
I comment op MatMul and Everything goes well

```python
 def get_op_mem_block(self, op_type, output_shape):
        mem_block = [0, 0]
        if op_type == 'WinogradTransform' :#or op_type == 'MatMul':
            mem_block[0] = output_shape[2]
            mem_block[1] = output_shape[0] * int((output_shape[1] + 3) / 4)
        else:
            if len(output_shape) == 2:  # only support fc/softmax
                mem_block[0] = int((output_shape[1] + 3) / 4)
                mem_block[1] = output_shape[0]
            else:
                mem_block[0] = output_shape[2] * int((output_shape[3] + 3) / 4)
                mem_block[1] = output_shape[0] * output_shape[1]
        return mem_block
```

**Comment by liyinhgqw** [comment]
We will fix it and let you know in the first time.

Thanks.

**Comment by nolanliou** [comment]
Fixed, please try `master` branch again.

**Comment by rogerou** [comment]
Convert successfully.
But CreateMaceEngineFromProto always return MACE_INVALID_ARGS with pb file or data file.
How can I load model files with CreateMaceEngineFromProto?

**Comment by liyinhgqw** [comment]
Try this?
```c++
  std::shared_ptr<mace::MaceEngine> engine;
    create_engine_status =
        CreateMaceEngineFromProto(model_pb_data,
                                  FLAGS_model_data_file,
                                  input_names,
                                  output_names,
                                  device_type,
                                  &engine);
```

**Comment by rogerou** [comment]
@liyinhgqw  not worked, the second param is string path not memory data

**Comment by liyinhgqw** [comment]
Yes, it should be string path of data file.
Why do you want it be memory data?

**Comment by rogerou** [comment]
if  compiled into apk ,how can i get the path of the file?

**Comment by liyinhgqw** [comment]
You can refer to the mace demo.

If you want to embed the model into mace library, you should use `CreateMaceEngineFromCode`.
See Advanced Usage in MACE doc.

**Comment by nolanliou** [comment]
You could define multiple models in model-deployment file(.yml), then convert, only one model library will be generated.
