### ISSUE TITLE
failed when exec the bash in the location--  /mace/mace/examples/android/build.sh

### ISSUE THREAD

**Issue by skertiver** [XiaoMi/mace#112]
### System information
- **OS Platform and Distribution :Linux Ubuntu 14.04**:
- **NDK version : r15c**:
- **GCC version: gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4**:
- **MACE version v0.8.1-172-g915d38c**:
- **Python version(2.7)**: 
- **Bazel version 0.13.1**:

### Model deploy file (*.yml)
```yaml
library_name: mobilenet
target_abis: [arm64-v8a]
model_graph_format: code
model_data_format: code
models:
  mobilenet_v1:
    platform: tensorflow
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v1/mobilenet-v1-1.0.pb
    model_sha256_checksum: 71b10f540ece33c49a7b51f5d4095fc9bd78ce46ebf0300487b2ee23d71294e6
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,224,224,3
        output_tensors:
          - MobilenetV1/Predictions/Reshape_1
        output_shapes:
          - 1,1001
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
  mobilenet_v2:
    platform: tensorflow
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v2/mobilenet-v2-1.0.pb
    model_sha256_checksum: 369f9a5f38f3c15b4311c1c84c032ce868da9f371b5f78c13d3ea3c537389bb4
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,224,224,3
        output_tensors:
          - MobilenetV2/Predictions/Reshape_1
        output_shapes:
          - 1,1001
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
```

### Describe the problem
when i exec the bash, it failed in the cmd "python tools/converter.py convert --config=mace/examples/android/mobilenet.yml --target_abis=$TARGET_ABI"

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /mace/mace/examples/android
2. bash ./build.sh
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
Traceback (most recent call last):
  File "tools/converter.py", line 1595, in <module>
    flags.func(flags)
  File "tools/converter.py", line 785, in convert_func
    convert_model(configs)
  File "tools/converter.py", line 711, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/apple/Downloads/mace/tools/sh_commands.py", line 524, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.SignalException_SIGKILL: 

  RAN: /usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=builds/downloads/f330dec17e45a8626cfb225ddce95051.pb --weight_file= --model_checksum=71b10f540ece33c49a7b51f5d4095fc9bd78ce46ebf0300487b2ee23d71294e6 --weight_checksum= --input_node=input --output_node=MobilenetV1/Predictions/Reshape_1 --runtime=cpu+gpu --template=mace/python/tools --model_tag=mobilenet_v1 --input_shape=1,224,224,3 --dsp_mode=0 --embed_model_data=True --winograd=0 --obfuscate=0 --output_dir=mace/codegen/models/mobilenet_v1 --model_graph_format=code --data_type=fp16_fp32 --graph_optimize_options=

  STDOUT:


  STDERR:


```

### Additional context
i want to deploy the demo on the android os platform,therefore i need to generate sth like mobilenet.a

**Comment by lee-bin** [comment]
Building demo app itself needs almost 6 GB RAM. So make sure you have enough RAM.
