### ISSUE TITLE
Convert Tensorflow model failed -- if Shape OP's output len is 1, error return when optimizing gpu memory.

### ISSUE THREAD

**Issue by cutejerry** [XiaoMi/mace#116]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **NDK version(e.g., 15c)**: r15c
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:  master - commit c2b069755d3
- **Python version(2.7)**:  Python 2.7.12
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
library_name: hq_model
target_abis: [armeabi-v7a]
target_socs: []
embed_model_data: 0
model_graph_format: file
model_data_format: file
models:
  classifier0:
    platform: tensorflow
    model_file_path: ...
    model_sha256_checksum:  ...
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,120,160,3
        output_tensors:
          - output
        output_shapes:
          - 1,7
    runtime: gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
```

### Describe the problem
This module include OP's len is 1. When optimizing gpu memory, output_shape[]'s index out of range.

### To Reproduce
Steps to reproduce the problem:
```bash
python tools/converter.py convert --config=./hq_model.yml
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
Traceback (most recent call last):
  File "/home/rui01.wang/task_force_187/mace_latest/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 298, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/rui01.wang/task_force_187/mace_latest/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 156, in main
    memory_optimizer.optimize_gpu_memory(output_graph_def)
  File "/home/rui01.wang/task_force_187/mace_latest/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/memory_optimizer.py", line 228, in optimize_gpu_memory
    mem_optimizer.optimize()
  File "/home/rui01.wang/task_force_187/mace_latest/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/memory_optimizer.py", line 112, in optimize
    op.output_shape[i].dims)
  File "/home/rui01.wang/task_force_187/mace_latest/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/memory_optimizer.py", line 200, in get_op_mem_block
    mem_block[0] = output_shape[2] * int((output_shape[3] + 3) / 4)
  File "/home/rui01.wang/.cache/bazel/_bazel_rui01.wang/a39146827b3c31009993b10aec7bacf1/execroot/mace/bazel-out/k8-fastbuild/bin/mace/python/tools/converter.runfiles/com_google_protobuf/python/google/protobuf/internal/containers.py", line 204, in __getitem__
    return self._values[key]
IndexError: list index out of range
Traceback (most recent call last):
  File "tools/converter.py", line 1595, in <module>
    flags.func(flags)
  File "tools/converter.py", line 785, in convert_func
    convert_model(configs)
  File "tools/converter.py", line 711, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/rui01.wang/task_force_187/mace_latest/mace/tools/sh_commands.py", line 524, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1:

  RAN: /usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=/home/rui01.wang/task_force_187/mace_latest/models/classifier_05/graph.pb --weight_file= --model_checksum=196ceb0498b6092570c0b08079680271bb496a9357952e73a3abdf9f8a774d71 --weight_checksum= --input_node=input --output_node=output --runtime=cpu+gpu --template=mace/python/tools --model_tag=classifier0 --input_shape=1,120,160,3 --dsp_mode=0 --embed_model_data=False --winograd=0 --obfuscate=0 --output_dir=mace/codegen/models/classifier0 --model_graph_format=file --data_type=fp16_fp32 --graph_optimize_options=

  STDOUT:


  STDERR:
```

### Additional context
These are final Ops list:
```bash
...
net/conv2d_7/kernel_0_b2i (BufferToImage): []
net/conv2d_7/bias_0_b2i (BufferToImage): []
net/conv2d_7/Relu6 (Conv2D): [[1L, 15L, 20L, 16L]]
net/max_pooling2d_3/MaxPool (Pooling): [[1L, 7L, 10L, 16L]]
net/flatten/Shape (Shape): [[4L]] 
net/flatten/strided_slice (StridedSlice): [[]]
net/flatten/Reshape/shape (Stack): [[2L]]
net/flatten/Reshape (Reshape): [[1L, 1120L]]
...
```
We can see Shape's output len is only 1. Seems the converter not support it.

Codes:
```python
    def get_op_mem_block(self, op_type, output_shape):
        mem_block = [0, 0]
        if op_type == 'WinogradTransform' or op_type == 'MatMul':
            mem_block[0] = output_shape[2]
            mem_block[1] = output_shape[0] * int((output_shape[1] + 3) / 4)
        else:
            if len(output_shape) == 2:  # only support fc/softmax
                mem_block[0] = int((output_shape[1] + 3) / 4)
                mem_block[1] = output_shape[0]
            else:
                mem_block[0] = output_shape[2] * int((output_shape[3] + 3) / 4)
                mem_block[1] = output_shape[0] * output_shape[1]
        return mem_block
```

**Comment by llhe** [comment]
Duplicated with #109?

**Comment by cutejerry** [comment]
Similarly, I think. Only issued OPs are different.

**Comment by cutejerry** [comment]
Checked on commit 86ef00bb2ac, it's fixed. Thank you all.
