### ISSUE TITLE
It semms my deploy file has something wrong,but I can`t find it out.

### ISSUE THREAD

**Issue by lyp0413** [XiaoMi/mace#127]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:16.04
- **NDK version(e.g., 15c)**:r16b
- **GCC version(if compiling for host, e.g., 5.4.0)**:5.4.0
- **MACE version (Use the command: git describe --long --tags)**:8.1
- **Python version(2.7)**: 2.7
- **Bazel version (e.g., 0.13.0)**:0.15.0

### Model deploy file (*.yml)
```yml
library_name: hdrnet
target_abis: [armeabi-v7a, arm64-v8a]
target_socs: [msm8996]
model_graph_format: code
model_data_format: code
models: 
  hdrnet: 
    platform: tensorflow
    model_file_path: /home/lyp/mace-master/mace-models/pb/optimized_graph.pb
    model_sha256_checksum: d274cb6205c6a426a10b32f9aa2feec4251da39862230a698b2b44b60fcf44ca
    subgraphs:
      - input_tensors: 
	  - lowres_input
        input_shapes: 
	  - 1,256,256,3
      	validation_inputs_data:
          - /home/lyp/mace/images/hdr.npy        
	output_tensors: 
	  - local_output
          - global_output
        output_shapes:
          - 16,16,64
          - 64
       
    runtime: cpu
    limit_opencl_kernel_time: 0
    dsp_mode: 0
    obfuscate: 0
    winograd: 4
```

### Describe the problem

I can`t convert my model with two output tensors

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
```
Traceback (most recent call last):
  File "tools/converter.py", line 1595, in <module>
    flags.func(flags)
  File "tools/converter.py", line 781, in convert_func
    configs = format_model_config(flags)
  File "tools/converter.py", line 279, in format_model_config
    configs = yaml.load(f)
  File "/home/lyp/.local/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/home/lyp/.local/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/home/lyp/.local/lib/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/lyp/.local/lib/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/lyp/.local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/lyp/.local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/lyp/.local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/lyp/.local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/lyp/.local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/lyp/.local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/lyp/.local/lib/python2.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/home/lyp/.local/lib/python2.7/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/home/lyp/.local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/lyp/.local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/lyp/.local/lib/python2.7/site-packages/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "/home/lyp/.local/lib/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/lyp/.local/lib/python2.7/site-packages/yaml/parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "/home/lyp/.local/lib/python2.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/lyp/.local/lib/python2.7/site-packages/yaml/scanner.py", line 257, in fetch_more_tokens
    % ch.encode('utf-8'), self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "mace-models/hdrnet.yml", line 13, column 1
```
### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by llhe** [comment]
Pay attention to the error message:
```
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
```
This means your model config file is invalid YAML file. See the read tabs in your config file.

Here is tool to validate your file: http://www.yamllint.com/
