### ISSUE TITLE
How to generate inception_v3_q_2015.pb for DSP runtime? (again)

### ISSUE THREAD

**Issue by springishere** [XiaoMi/mace#136]
This is reopen of issue #59 
I followed the steps there and had the same result. mace tree is synced today and mace docker rebuilt.
transform_graph is from tensorflow 1.6 binary docker image from tensor flow website (tag is tensorflow/tensorflow:1.6.0-devel).
mace is using docker built from mainline.

Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yams
    model_file_path: /models/inception-v3/inception-v3.opt.pb
    model_sha256_checksum: 93a44a93ef9027b7e3bfafe41f6f706ba5a263abd5ffec6ae09aca8e366673b3
    subgraphs:
      - input_tensors:
          - Mul
        input_shapes:
          - 1,299,299,3
        output_tensors:
          - softmax
        output_shapes:
          - 1,1,1,1008

```

### Describe the problem

Transform the graph from xiaomi's inceptionv3 model, which is downloaded from https://cnbj1.fds.api.xiaomi.com/mace/miai-models/inception-v3/inception-v3.pb

/tensorflow# bazel-bin/tensorflow/tools/graph_transforms/transform_graph --in_graph=/xiaomi/mace-models/inception-v3/inception-v3.pb --out_graph=/xiaomi/mace-models/inception-v3/inception-v3.opt.pb --inputs='input' --outputs='InceptionV3/Predictions/Reshape_1' --transforms='strip_unused_nodes(type=float, shape="1,299,299,3") strip_unused_nodes(type=float, shape="1,299,299,3") remove_nodes(op=Identity, op=CheckNumerics)
               fold_constants(ignore_errors=true)
               fold_batch_norms
               fold_old_batch_norms
               backport_concatv2
               quantize_weights(minimum_size=2)
               quantize_nodes
               strip_unused_nodes
               sort_by_execution_order'

Run mace from the Dockerfile at mace/docker/mace-dev-lite (mainline)

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
/mace# python tools/converter.py convert --config=/models/inception-v3/inception-v3-dsp.yml
/usr/local/lib/python2.7/dist-packages/scipy/sparse/lil.py:19: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _csparsetools
/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:165: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._shortest_path import shortest_path, floyd_warshall, dijkstra,\
/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/_validation.py:5: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._tools import csgraph_to_dense, csgraph_from_dense,\
/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:167: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._traversal import breadth_first_order, depth_first_order, \
/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:169: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._min_spanning_tree import minimum_spanning_tree
/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:170: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._reordering import reverse_cuthill_mckee, maximum_bipartite_matching, \
/usr/local/lib/python2.7/dist-packages/scipy/spatial/__init__.py:95: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .ckdtree import *
/usr/local/lib/python2.7/dist-packages/scipy/spatial/__init__.py:96: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .qhull import *
/usr/local/lib/python2.7/dist-packages/scipy/spatial/_spherical_voronoi.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _voronoi
/usr/local/lib/python2.7/dist-packages/scipy/spatial/distance.py:122: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _hausdorff
/usr/local/lib/python2.7/dist-packages/scipy/linalg/basic.py:17: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._solve_toeplitz import levinson
/usr/local/lib/python2.7/dist-packages/scipy/linalg/__init__.py:207: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._decomp_update import *
/usr/local/lib/python2.7/dist-packages/scipy/special/__init__.py:640: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ufuncs import *
/usr/local/lib/python2.7/dist-packages/scipy/special/_ellip_harm.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
/usr/local/lib/python2.7/dist-packages/scipy/interpolate/_bsplines.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _bspl
/usr/local/lib/python2.7/dist-packages/scipy/optimize/_trlib/__init__.py:1: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._trlib import TRLIBQuadraticSubproblem
/usr/local/lib/python2.7/dist-packages/scipy/optimize/_numdiff.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._group_columns import group_dense, group_sparse
/usr/local/lib/python2.7/dist-packages/scipy/stats/_continuous_distns.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _stats
---------------------------------------
          Common Configuration         
---------------------------------------
|        key        |      value      |
=======================================
|       library_name| inception-v3-dsp|
---------------------------------------
|        target_abis|  ['armeabi-v7a']|
---------------------------------------
|        target_socs|       ['sdm660']|
---------------------------------------
| model_graph_format|             file|
---------------------------------------
|  model_data_format|             file|
---------------------------------------

**************************************************
          Convert inception_v3_dsp model          
**************************************************

INFO: Analysed target //mace/python/tools:converter (19 packages loaded).
INFO: Found 1 target...
Target //mace/python/tools:converter up-to-date:
  bazel-bin/mace/python/tools/converter
INFO: Elapsed time: 2.335s, Critical Path: 0.11s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

Transform model to one that can better run on device
/usr/local/lib/python2.7/dist-packages/scipy/sparse/lil.py:19: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _csparsetools
/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:165: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._shortest_path import shortest_path, floyd_warshall, dijkstra,\
/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/_validation.py:5: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._tools import csgraph_to_dense, csgraph_from_dense,\
/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:167: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._traversal import breadth_first_order, depth_first_order, \
/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:169: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._min_spanning_tree import minimum_spanning_tree
/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:170: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._reordering import reverse_cuthill_mckee, maximum_bipartite_matching, \
/usr/local/lib/python2.7/dist-packages/scipy/linalg/basic.py:17: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._solve_toeplitz import levinson
/usr/local/lib/python2.7/dist-packages/scipy/linalg/__init__.py:207: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._decomp_update import *
/usr/local/lib/python2.7/dist-packages/scipy/special/__init__.py:640: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ufuncs import *
/usr/local/lib/python2.7/dist-packages/scipy/special/_ellip_harm.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
/usr/local/lib/python2.7/dist-packages/scipy/interpolate/_bsplines.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _bspl
/usr/local/lib/python2.7/dist-packages/scipy/spatial/__init__.py:95: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .ckdtree import *
/usr/local/lib/python2.7/dist-packages/scipy/spatial/__init__.py:96: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .qhull import *
/usr/local/lib/python2.7/dist-packages/scipy/spatial/_spherical_voronoi.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _voronoi
/usr/local/lib/python2.7/dist-packages/scipy/spatial/distance.py:122: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _hausdorff
/usr/local/lib/python2.7/dist-packages/scipy/ndimage/measurements.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _ni_label
('Op: ', u'InceptionV3/Mixed_7c/Branch_2/Conv2d_0b_3x3/weights_quantized_const', u'Const', TensorShape([Dimension(3), Dimension(3), Dimension(448), Dimension(384)]))
('Add const node: ', u'InceptionV3/Mixed_7c/Branch_2/Conv2d_0b_3x3/weights_quantized_const')
('Op: ', u'InceptionV3/Mixed_6e/Branch_2/Conv2d_0a_1x1/weights_quantized_const', u'Const', TensorShape([Dimension(1), Dimension(1), Dimension(768), Dimension(192)]))
('Add const node: ', u'InceptionV3/Mixed_6e/Branch_2/Conv2d_0a_1x1/weights_quantized_const')
('Op: ', u'InceptionV3/InceptionV3/Mixed_6b/Branch_1/Conv2d_0c_7x1/Conv2D_bn_offset_quantized_min', u'Const', TensorShape([]))
('Add const node: ', u'InceptionV3/InceptionV3/Mixed_6b/Branch_1/Conv2d_0c_7x1/Conv2D_bn_offset_quantized_min')
('Op: ', u'InceptionV3/InceptionV3/Mixed_6e/Branch_1/Conv2d_0b_1x7/Conv2D_bn_offset_quantized_const', u'Const', TensorShape([Dimension(192)]))
('Add const node: ', u'InceptionV3/InceptionV3/Mixed_6e/Branch_1/Conv2d_0b_1x7/Conv2D_bn_offset_quantized_const')
('Op: ', u'InceptionV3/Mixed_5c/Branch_2/Conv2d_0a_1x1/weights_quantized_min', u'Const', TensorShape([]))
('Add const node: ', u'InceptionV3/Mixed_5c/Branch_2/Conv2d_0a_1x1/weights_quantized_min')
('Op: ', u'InceptionV3/Mixed_7a/Branch_1/Conv2d_1a_3x3/weights_quantized_min', u'Const', TensorShape([]))
('Add const node: ', u'InceptionV3/Mixed_7a/Branch_1/Conv2d_1a_3x3/weights_quantized_min')
('Op: ', u'InceptionV3/Mixed_6d/Branch_1/Conv2d_0a_1x1/weights_quantized_const', u'Const', TensorShape([Dimension(1), Dimension(1), Dimension(768), Dimension(160)]))
('Add const node: ', u'InceptionV3/Mixed_6d/Branch_1/Conv2d_0a_1x1/weights_quantized_const')
('Op: ', u'InceptionV3/Mixed_5b/Branch_0/Conv2d_0a_1x1/weights_quantized_min', u'Const', TensorShape([]))
('Add const node: ', u'InceptionV3/Mixed_5b/Branch_0/Conv2d_0a_1x1/weights_quantized_min')
('Op: ', u'InceptionV3/InceptionV3/Mixed_5d/Branch_1/Conv2d_0b_5x5/Conv2D_bn_offset_quantized_const', u'Const', TensorShape([Dimension(64)]))
('Add const node: ', u'InceptionV3/InceptionV3/Mixed_5d/Branch_1/Conv2d_0b_5x5/Conv2D_bn_offset_quantized_const')
('Op: ', u'InceptionV3/Mixed_6b/Branch_1/Conv2d_0c_7x1/weights_quantized_min', u'Const', TensorShape([]))
('Add const node: ', u'InceptionV3/Mixed_6b/Branch_1/Conv2d_0c_7x1/weights_quantized_min')
('Op: ', u'InceptionV3/Mixed_6b/Branch_2/Conv2d_0a_1x1/weights_quantized_min', u'Const', TensorShape([]))
('Add const node: ', u'InceptionV3/Mixed_6b/Branch_2/Conv2d_0a_1x1/weights_quantized_min')
('Op: ', u'InceptionV3/Mixed_6e/Branch_2/Conv2d_0a_1x1/weights_quantized_min', u'Const', TensorShape([]))
('Add const node: ', u'InceptionV3/Mixed_6e/Branch_2/Conv2d_0a_1x1/weights_quantized_min')
('Op: ', u'InceptionV3/InceptionV3/Mixed_6d/Branch_1/Conv2d_0a_1x1/Conv2D_bn_offset_quantized_min', u'Const', TensorShape([]))
('Add const node: ', u'InceptionV3/InceptionV3/Mixed_6d/Branch_1/Conv2d_0a_1x1/Conv2D_bn_offset_quantized_min')
('Op: ', u'InceptionV3/Mixed_5c/Branch_2/Conv2d_0b_3x3/weights_quantized_const', u'Const', TensorShape([Dimension(3), Dimension(3), Dimension(64), Dimension(96)]))
('Add const node: ', u'InceptionV3/Mixed_5c/Branch_2/Conv2d_0b_3x3/weights_quantized_const')
('Op: ', u'InceptionV3/InceptionV3/Conv2d_1a_3x3/Conv2D_eightbit/input__port__0/reshape_dims', u'Const', TensorShape([Dimension(1)]))
('Add const node: ', u'InceptionV3/InceptionV3/Conv2d_1a_3x3/Conv2D_eightbit/input__port__0/reshape_dims')
Traceback (most recent call last):
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 305, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 129, in main
    output_graph_def = converter.run()
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tf_dsp_converter.py", line 664, in run
    dsp_ops)
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tf_dsp_converter.py", line 203, in convert_ops
    tf_tensor = first_op.outputs[0].eval()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 710, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 5180, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input' with dtype float and shape [?,299,299,3]
[[Node: input = Placeholder[dtype=DT_FLOAT, shape=[?,299,299,3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op u'input', defined at:
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 305, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 128, in main
    option, FLAGS.model_file)
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tf_dsp_converter.py", line 645, in __init__
    tf.import_graph_def(tf_graph_def, name='')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 513, in import_graph_def
    _ProcessNewOps(graph)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 303, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3540, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3428, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'input' with dtype float and shape [?,299,299,3]
[[Node: input = Placeholder[dtype=DT_FLOAT, shape=[?,299,299,3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Traceback (most recent call last):
  File "tools/converter.py", line 1595, in <module>
    flags.func(flags)
  File "tools/converter.py", line 785, in convert_func
    convert_model(configs)
  File "tools/converter.py", line 711, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/mace/tools/sh_commands.py", line 524, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=/models/inception-v3/inception-v3.opt.pb --weight_file= --model_checksum=93a44a93ef9027b7e3bfafe41f6f706ba5a263abd5ffec6ae09aca8e366673b3 --weight_checksum= --input_node=Mul --output_node=softmax --runtime=dsp --template=mace/python/tools --model_tag=inception_v3_dsp --input_shape=1,299,299,3 --dsp_mode=4 --embed_model_data=False --winograd=0 --obfuscate=1 --output_dir=mace/codegen/models/inception_v3_dsp --model_graph_format=file --data_type=uint8 --graph_optimize_options=

  STDOUT:


  STDERR:
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

I wonder if you have tested this?
If you tested and it's ok, then I suspect this is related to setup, for example I used two docker, one is tensorflow and another is mace.

**Comment by springishere** [comment]
Not sure why the docker/mace-dev-lite/Dockerfile uses tensorflow 1.8. Anyway I tried to optimise graph with tensorflow 1.8 (tensorflow/tensorflow:1.8.0-devel) and I have the same error.
Since the source pb is already frozen, freeze graph is not the solution. I also tried to use the tensorflow  frozen model directly from tensorflow website and the result is same.

**Comment by lydoc** [comment]
It seems that there may be some control dependencies issue in the "transform graph" phase. Could you have a try for adding 'remove_control_dependecies" in transform_graph again?
e.g.:
bazel-bin/tensorflow/tools/graph_transforms/transform_graph --in_graph=/xiaomi/mace-models/inception-v3/inception-v3.pb --out_graph=/xiaomi/mace-models/inception-v3/inception-v3.opt.pb --inputs='input' --outputs='InceptionV3/Predictions/Reshape_1' --transforms='strip_unused_nodes(type=float, shape="1,299,299,3") strip_unused_nodes(type=float, shape="1,299,299,3") remove_nodes(op=Identity, op=CheckNumerics)
fold_constants(ignore_errors=true)
fold_batch_norms
fold_old_batch_norms
backport_concatv2
quantize_weights(minimum_size=2)
quantize_nodes
strip_unused_nodes
sort_by_execution_order
remove_control_dependecies'

BTW, you can use tensorboard to visualize the graph to check the problematic node.

**Comment by springishere** [comment]
Added (have to use tensorflow 1.10-rc0 since this option only exists there), now it's a different error:

('Add const node: ', u'InceptionV3/Mixed_7c/Branch_2/Conv2d_0a_1x1/weights_quantized_const')
('Op: ', u'InceptionV3/Mixed_5d/Branch_1/Conv2d_0a_1x1/weights_quantized_max', u'Const', TensorShape([]))
('Add const node: ', u'InceptionV3/Mixed_5d/Branch_1/Conv2d_0a_1x1/weights_quantized_max')
('Op: ', u'InceptionV3/InceptionV3/Mixed_7a/Branch_0/Conv2d_0a_1x1/Conv2D_bn_offset_quantized_max', u'Const', TensorShape([]))
('Add const node: ', u'InceptionV3/InceptionV3/Mixed_7a/Branch_0/Conv2d_0a_1x1/Conv2D_bn_offset_quantized_max')
('Op: ', u'InceptionV3/InceptionV3/Mixed_5c/Branch_2/Conv2d_0a_1x1/Conv2D_bn_offset_quantized_const', u'Const', TensorShape([Dimension(64)]))
('Add const node: ', u'InceptionV3/InceptionV3/Mixed_5c/Branch_2/Conv2d_0a_1x1/Conv2D_bn_offset_quantized_const')
('Op: ', u'InceptionV3/Mixed_5c/Branch_2/Conv2d_0c_3x3/weights_quantized_max', u'Const', TensorShape([]))
('Add const node: ', u'InceptionV3/Mixed_5c/Branch_2/Conv2d_0c_3x3/weights_quantized_max')
('Op: ', u'InceptionV3/Mixed_7b/Branch_2/Conv2d_0b_3x3/weights_quantized_min', u'Const', TensorShape([]))
('Add const node: ', u'InceptionV3/Mixed_7b/Branch_2/Conv2d_0b_3x3/weights_quantized_min')
('Op: ', u'InceptionV3/InceptionV3/Mixed_6c/Branch_1/Conv2d_0a_1x1/Conv2D_bn_offset_quantized_const', u'Const', TensorShape([Dimension(160)]))
('Add const node: ', u'InceptionV3/InceptionV3/Mixed_6c/Branch_1/Conv2d_0a_1x1/Conv2D_bn_offset_quantized_const')
('Op: ', u'InceptionV3/InceptionV3/Mixed_6b/Branch_2/Conv2d_0c_1x7/Conv2D_bn_offset_quantized_max', u'Const', TensorShape([]))
('Add const node: ', u'InceptionV3/InceptionV3/Mixed_6b/Branch_2/Conv2d_0c_1x7/Conv2D_bn_offset_quantized_max')
('Op: ', u'InceptionV3/Mixed_5d/Branch_2/Conv2d_0b_3x3/weights_quantized_max', u'Const', TensorShape([]))
('Add const node: ', u'InceptionV3/Mixed_5d/Branch_2/Conv2d_0b_3x3/weights_quantized_max')
('Op: ', u'input', u'Placeholder', TensorShape([Dimension(None), Dimension(299), Dimension(299), Dimension(3)]))
Traceback (most recent call last):
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 305, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 129, in main
    output_graph_def = converter.run()
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tf_dsp_converter.py", line 670, in run
    dsp_ops)
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tf_dsp_converter.py", line 417, in convert_ops
    convert_op_outputs(op_def, first_op)
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tf_dsp_converter.py", line 178, in convert_op_outputs
    [max_elem_size(output) for output in tf_op.outputs])
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tf_dsp_converter.py", line 138, in max_elem_size
    return reduce(mul, tensor.shape.as_list()) * tensor.dtype.size
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
Traceback (most recent call last):
  File "tools/converter.py", line 1595, in <module>
    flags.func(flags)
  File "tools/converter.py", line 785, in convert_func
    convert_model(configs)
  File "tools/converter.py", line 711, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/mace/tools/sh_commands.py", line 524, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=/models/inception-v3/inception-v3.opt.pb --weight_file= --model_checksum=c2978a4353a4ae4fa96ad7ca93339938b5b84efa150f868b3b26d866c9e34b09 --weight_checksum= --input_node=Mul --output_node=softmax --runtime=dsp --template=mace/python/tools --model_tag=inception_v3_dsp --input_shape=1,299,299,3 --dsp_mode=4 --embed_model_data=False --winograd=0 --obfuscate=1 --output_dir=mace/codegen/models/inception_v3_dsp --model_graph_format=file --data_type=uint8 --graph_optimize_options=

**Comment by lydoc** [comment]
Hi @springishere ,

This problem is caused by inconsistent parameters. The model from https://cnbj1.fds.api.xiaomi.com/mace/miai-models/inception-v3/inception-v3.pb is different from the model deploy in inception-v3-dsp.yml. In the transform graph tool, --inputs='input' and --outputs='InceptionV3/Predictions/Reshape_1'. But in your model deploy file (*.yml), - input_tensors is Mul and output_tensors is softmax, which caused this issue. Again, make sure output_shapes in the yml file is correct, it should be "- 1,1,1,1001" if you use inception-v3.pb model. Failure to do so may result in an incorrect result.

please use the model deploy file below and try again.
```yams
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,299,299,3
        output_tensors:
          - InceptionV3/Predictions/Reshape_1
        output_shapes:
          - 1,1,1,1001

```

We will update the inception-v3-dsp.yml and model later.

**Comment by liyinhgqw** [comment]
Updated.

**Comment by liyinhgqw** [comment]
@springishere check it again?

**Comment by springishere** [comment]
Yes it now converts ok.
run failed, but that's a different issue:
F mace.cc:247 Check failed: hexagon_controller_->Config() hexagon config error
Aborted
