### ISSUE TITLE
Can you help to add ops Minimum and Maximum?

### ISSUE THREAD

**Issue by wayen820** [XiaoMi/mace#140]
Our models use LeakyReLU activation，but it's not currently supported. We want to implement it manually using op Minimum and Maximum, but it's not supported also.Thanks

**Comment by liyinhgqw** [comment]
Minimum and Maximum are supported. You can try it out.

**Comment by lydoc** [comment]
@wayen820 You can use MIN and MAX in the  ELEMENT_WISE operator.

**Comment by wayen820** [comment]
@lydoc   
Thanks, you are right, this problem has been solved, but there is another problem:
`****************************************
          Convert my_net model          
****************************************

WARNING: ignoring LD_PRELOAD in environment.
Starting local Bazel server and connecting to it...
.......................................................
INFO: Analysed target //mace/python/tools:converter (20 packages loaded).
INFO: Found 1 target...
Target //mace/python/tools:converter up-to-date:
  bazel-bin/mace/python/tools/converter
INFO: Elapsed time: 7.376s, Critical Path: 0.22s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

Transform model to one that can better run on device
Traceback (most recent call last):
  File "/home/wayen/program/mace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 305, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/wayen/program/mace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 144, in main
    output_graph_def = converter.run()
  File "/home/wayen/program/mace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 223, in run
    self.convert_ops()
  File "/home/wayen/program/mace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 267, in convert_ops
    % tf_op.type)
  File "/home/wayen/program/mace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/convert_util.py", line 20, in mace_check
    raise Exception(msg)
Exception: Mace does not support tensorflow op type ExpandDims yet
Traceback (most recent call last):
  File "tools/converter.py", line 1595, in <module>
    flags.func(flags)
  File "tools/converter.py", line 785, in convert_func
    convert_model(configs)
  File "tools/converter.py", line 711, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/wayen/program/mace/mace/tools/sh_commands.py", line 524, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=/home/wayen/program/MMdnn/mymodel/model-y1-test2/tf-pb/my_net.pb --weight_file= --model_checksum=55dc1ce2babe5b3ef29d2ebbfe549c9943fcc3658ead00d12b7ef3cfad2435a0 --weight_checksum= --input_node=data --output_node=fc1/add_1 --runtime=gpu --template=mace/python/tools --model_tag=my_net --input_shape=1,112,112,3 --dsp_mode=0 --embed_model_data=False --winograd=0 --obfuscate=0 --output_dir=mace/codegen/models/my_net --model_graph_format=file --data_type=fp16_fp32 --graph_optimize_options=

  STDOUT:


  STDERR:
`

**Comment by TonyMou** [comment]
Exception: Mace does not support tensorflow op type ExpandDims yet

**Comment by liyinhgqw** [comment]
@wayen820 What is the use of ExpandDims ? There might be some way to get a workaround.

**Comment by TonyMou** [comment]
@hzwangjl https://github.com/XiaoMi/mace/blob/c2523ee2ace8ce846b6279b0680a52a1050022b8/mace/python/tools/converter_tool/tensorflow_converter.py#L58
