### ISSUE TITLE
convert caffe model failed,MemoryError.

### ISSUE THREAD

**Issue by leeburt** [XiaoMi/mace#162]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. The form below must be filled.

------------------------

### System information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04.10
NDK version(e.g., 15c):15c
GCC version(if compiling for host, e.g., 5.4.0): GCC 5.4.0
MACE version (Use the command: git describe --long --tags): master
Python version(2.7): 2.7
Bazel version (e.g., 0.13.0):0.13.0

### Model deploy file (*.yml)
# The name of library
```yml
library_name: openposecaffe
target_abis: [arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  openposecaffe: # model tag, which will be used in model loading and must be specific.
    platform: caffe
    # support local path, http:// and https://
    model_file_path: /home/songbiao/libo/model/openpose/caffe/1.prototxt
    weight_file_path: /home/songbiao/libo/model/openpose/caffe/1.caffemodel
    # sha256_checksum of your model's graph and data files.
    # get the sha256_checksum: sha256sum path/to/your/file
    model_sha256_checksum: 52bc10ec3d309514b36be8c4f382a5e7b1cfc8cbd3f995c2b580cf0a17aeb7ef
    weight_sha256_checksum: b4cf475576abd7b15d5316f1ee65eb492b5c9f5865e70a2e7882ed31fb682549
    # define your model's interface
    # if there multiple inputs or outputs, write like blow:
    # subgraphs:
    # - input_tensors:
    #     - input0
    #     - input1
    #   input_shapes:
    #     - 1,224,224,3
    #     - 1,224,224,3
    #    output_tensors:
    #      - output0
    #      - output1
    #    output_shapes:
    #      - 1,1001
    #      - 1,1001
    subgraphs:
      - input_tensors:
          - image
        input_shapes:
          - 1,368,368,3
        output_tensors:
          - Mconv7_stage6_L2
        output_shapes:
          - 1,46,46,19
    runtime: cpu
    winograd: 0
```
### Describe the problem
convert caffe model failed。

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2.python tools/converter.py convert --config=/home/songbiao/libo/model/openpose/caffe/1.yml 
```

### Error information / logs
```
/home/songbiao/anaconda2/lib/python2.7/site-packages/scipy/sparse/lil.py:16: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _csparsetools
/home/songbiao/anaconda2/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:167: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._shortest_path import shortest_path, floyd_warshall, dijkstra,\
/home/songbiao/anaconda2/lib/python2.7/site-packages/scipy/sparse/csgraph/_validation.py:5: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._tools import csgraph_to_dense, csgraph_from_dense,\
/home/songbiao/anaconda2/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:169: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._traversal import breadth_first_order, depth_first_order, \
/home/songbiao/anaconda2/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:171: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._min_spanning_tree import minimum_spanning_tree
/home/songbiao/anaconda2/lib/python2.7/site-packages/scipy/sparse/csgraph/__init__.py:172: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._reordering import reverse_cuthill_mckee, maximum_bipartite_matching, \
/home/songbiao/anaconda2/lib/python2.7/site-packages/scipy/spatial/__init__.py:94: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .ckdtree import *
/home/songbiao/anaconda2/lib/python2.7/site-packages/scipy/spatial/__init__.py:95: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .qhull import *
/home/songbiao/anaconda2/lib/python2.7/site-packages/scipy/spatial/_spherical_voronoi.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _voronoi
/home/songbiao/anaconda2/lib/python2.7/site-packages/scipy/linalg/basic.py:17: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._solve_toeplitz import levinson
/home/songbiao/anaconda2/lib/python2.7/site-packages/scipy/linalg/__init__.py:191: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._decomp_update import *
/home/songbiao/anaconda2/lib/python2.7/site-packages/scipy/spatial/distance.py:121: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _hausdorff
/home/songbiao/anaconda2/lib/python2.7/site-packages/scipy/special/__init__.py:640: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ufuncs import *
/home/songbiao/anaconda2/lib/python2.7/site-packages/scipy/special/_ellip_harm.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
/home/songbiao/anaconda2/lib/python2.7/site-packages/scipy/optimize/_numdiff.py:8: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._group_columns import group_dense, group_sparse
/home/songbiao/anaconda2/lib/python2.7/site-packages/scipy/interpolate/_bsplines.py:9: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _bspl
/home/songbiao/anaconda2/lib/python2.7/site-packages/scipy/stats/_continuous_distns.py:17: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _stats
------------------------------------
        Common Configuration        
------------------------------------
|        key        |    value     |
====================================
|       library_name| openposecaffe|
------------------------------------
|        target_abis| ['arm64-v8a']|
------------------------------------
|        target_socs|            []|
------------------------------------
| model_graph_format|          file|
------------------------------------
|  model_data_format|          file|
------------------------------------

***********************************************
          Convert openposecaffe model          
***********************************************

Starting local Bazel server and connecting to it...
............................................................................
INFO: Analysed target //mace/python/tools:converter (19 packages loaded).
INFO: Found 1 target...
Target //mace/python/tools:converter up-to-date:
  bazel-bin/mace/python/tools/converter
INFO: Elapsed time: 9.921s, Critical Path: 0.82s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

Transform model to one that can better run on device
Fold activation: conv1_1(Conv2D)
Fold activation: conv1_2(Conv2D)
Fold activation: conv2_1(Conv2D)
Fold activation: conv2_2(Conv2D)
Fold activation: conv3_1(Conv2D)
Fold activation: conv3_2(Conv2D)
Fold activation: conv3_3(Conv2D)
Fold activation: conv3_4(Conv2D)
Fold activation: conv4_1(Conv2D)
Fold activation: conv4_2(Conv2D)
Fold activation: conv4_3_CPM(Conv2D)
Fold activation: conv4_4_CPM(Conv2D)
Fold activation: conv5_1_CPM_L1(Conv2D)
Fold activation: conv5_1_CPM_L2(Conv2D)
Fold activation: conv5_2_CPM_L1(Conv2D)
Fold activation: conv5_2_CPM_L2(Conv2D)
Fold activation: conv5_3_CPM_L1(Conv2D)
Fold activation: conv5_3_CPM_L2(Conv2D)
Fold activation: conv5_4_CPM_L1(Conv2D)
Fold activation: conv5_4_CPM_L2(Conv2D)
Fold activation: Mconv1_stage2_L1(Conv2D)
Fold activation: Mconv1_stage2_L2(Conv2D)
Fold activation: Mconv2_stage2_L1(Conv2D)
Fold activation: Mconv2_stage2_L2(Conv2D)
Fold activation: Mconv3_stage2_L1(Conv2D)
Fold activation: Mconv3_stage2_L2(Conv2D)
Fold activation: Mconv4_stage2_L1(Conv2D)
Fold activation: Mconv4_stage2_L2(Conv2D)
Fold activation: Mconv5_stage2_L1(Conv2D)
Fold activation: Mconv5_stage2_L2(Conv2D)
Fold activation: Mconv6_stage2_L1(Conv2D)
Fold activation: Mconv6_stage2_L2(Conv2D)
Fold activation: Mconv1_stage3_L1(Conv2D)
Fold activation: Mconv1_stage3_L2(Conv2D)
Fold activation: Mconv2_stage3_L1(Conv2D)
Fold activation: Mconv2_stage3_L2(Conv2D)
Fold activation: Mconv3_stage3_L1(Conv2D)
Fold activation: Mconv3_stage3_L2(Conv2D)
Fold activation: Mconv4_stage3_L1(Conv2D)
Fold activation: Mconv4_stage3_L2(Conv2D)
Fold activation: Mconv5_stage3_L1(Conv2D)
Fold activation: Mconv5_stage3_L2(Conv2D)
Fold activation: Mconv6_stage3_L1(Conv2D)
Fold activation: Mconv6_stage3_L2(Conv2D)
Fold activation: Mconv1_stage4_L1(Conv2D)
Fold activation: Mconv1_stage4_L2(Conv2D)
Fold activation: Mconv2_stage4_L1(Conv2D)
Fold activation: Mconv2_stage4_L2(Conv2D)
Fold activation: Mconv3_stage4_L1(Conv2D)
Fold activation: Mconv3_stage4_L2(Conv2D)
Fold activation: Mconv4_stage4_L1(Conv2D)
Fold activation: Mconv4_stage4_L2(Conv2D)
Fold activation: Mconv5_stage4_L1(Conv2D)
Fold activation: Mconv5_stage4_L2(Conv2D)
Fold activation: Mconv6_stage4_L1(Conv2D)
Fold activation: Mconv6_stage4_L2(Conv2D)
Fold activation: Mconv1_stage5_L1(Conv2D)
Fold activation: Mconv1_stage5_L2(Conv2D)
Fold activation: Mconv2_stage5_L1(Conv2D)
Fold activation: Mconv2_stage5_L2(Conv2D)
Fold activation: Mconv3_stage5_L1(Conv2D)
Fold activation: Mconv3_stage5_L2(Conv2D)
Fold activation: Mconv4_stage5_L1(Conv2D)
Fold activation: Mconv4_stage5_L2(Conv2D)
Fold activation: Mconv5_stage5_L1(Conv2D)
Fold activation: Mconv5_stage5_L2(Conv2D)
Fold activation: Mconv6_stage5_L1(Conv2D)
Fold activation: Mconv6_stage5_L2(Conv2D)
Fold activation: Mconv1_stage6_L2(Conv2D)
Fold activation: Mconv2_stage6_L2(Conv2D)
Fold activation: Mconv3_stage6_L2(Conv2D)
Fold activation: Mconv4_stage6_L2(Conv2D)
Fold activation: Mconv5_stage6_L2(Conv2D)
Fold activation: Mconv6_stage6_L2(Conv2D)
Transpose filters to OIHW
Transpose input/output to NCHW
Reshape fully connected weight shape
update op with float data type
Sort by execution
Final ops:
image (Transpose): [[1L, 3L, 368L, 368L]]
relu1_1 (Conv2D): [[1L, 64L, 368L, 368L]]
relu1_2 (Conv2D): [[1L, 64L, 368L, 368L]]
pool1_stage1 (Pooling): [[1L, 64L, 184L, 184L]]
relu2_1 (Conv2D): [[1L, 128L, 184L, 184L]]
relu2_2 (Conv2D): [[1L, 128L, 184L, 184L]]
pool2_stage1 (Pooling): [[1L, 128L, 92L, 92L]]
relu3_1 (Conv2D): [[1L, 256L, 92L, 92L]]
relu3_2 (Conv2D): [[1L, 256L, 92L, 92L]]
relu3_3 (Conv2D): [[1L, 256L, 92L, 92L]]
relu3_4 (Conv2D): [[1L, 256L, 92L, 92L]]
pool3_stage1 (Pooling): [[1L, 256L, 46L, 46L]]
relu4_1 (Conv2D): [[1L, 512L, 46L, 46L]]
relu4_2 (Conv2D): [[1L, 512L, 46L, 46L]]
relu4_3_CPM (Conv2D): [[1L, 256L, 46L, 46L]]
relu4_4_CPM (Conv2D): [[1L, 128L, 46L, 46L]]
relu5_1_CPM_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
relu5_2_CPM_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
relu5_3_CPM_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
relu5_4_CPM_L1 (Conv2D): [[1L, 512L, 46L, 46L]]
conv5_5_CPM_L1 (Conv2D): [[1L, 38L, 46L, 46L]]
relu5_1_CPM_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
relu5_2_CPM_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
relu5_3_CPM_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
relu5_4_CPM_L2 (Conv2D): [[1L, 512L, 46L, 46L]]
conv5_5_CPM_L2 (Conv2D): [[1L, 19L, 46L, 46L]]
concat_stage2 (Concat): [[1L, 223L, 46L, 46L]]
Mrelu1_stage2_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu2_stage2_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu3_stage2_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu4_stage2_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu5_stage2_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu6_stage2_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
Mconv7_stage2_L1 (Conv2D): [[1L, 38L, 46L, 46L]]
Mrelu1_stage2_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu2_stage2_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu3_stage2_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu4_stage2_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu5_stage2_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu6_stage2_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mconv7_stage2_L2 (Conv2D): [[1L, 19L, 46L, 46L]]
concat_stage3 (Concat): [[1L, 223L, 46L, 46L]]
Mrelu1_stage3_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu2_stage3_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu3_stage3_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu4_stage3_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu5_stage3_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu6_stage3_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
Mconv7_stage3_L1 (Conv2D): [[1L, 38L, 46L, 46L]]
Mrelu1_stage3_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu2_stage3_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu3_stage3_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu4_stage3_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu5_stage3_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu6_stage3_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mconv7_stage3_L2 (Conv2D): [[1L, 19L, 46L, 46L]]
concat_stage4 (Concat): [[1L, 223L, 46L, 46L]]
Mrelu1_stage4_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu2_stage4_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu3_stage4_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu4_stage4_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu5_stage4_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu6_stage4_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
Mconv7_stage4_L1 (Conv2D): [[1L, 38L, 46L, 46L]]
Mrelu1_stage4_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu2_stage4_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu3_stage4_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu4_stage4_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu5_stage4_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu6_stage4_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mconv7_stage4_L2 (Conv2D): [[1L, 19L, 46L, 46L]]
concat_stage5 (Concat): [[1L, 223L, 46L, 46L]]
Mrelu1_stage5_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu2_stage5_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu3_stage5_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu4_stage5_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu5_stage5_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu6_stage5_L1 (Conv2D): [[1L, 128L, 46L, 46L]]
Mconv7_stage5_L1 (Conv2D): [[1L, 38L, 46L, 46L]]
Mrelu1_stage5_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu2_stage5_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu3_stage5_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu4_stage5_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu5_stage5_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu6_stage5_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mconv7_stage5_L2 (Conv2D): [[1L, 19L, 46L, 46L]]
concat_stage6 (Concat): [[1L, 223L, 46L, 46L]]
Mrelu1_stage6_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu2_stage6_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu3_stage6_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu4_stage6_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu5_stage6_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mrelu6_stage6_L2 (Conv2D): [[1L, 128L, 46L, 46L]]
Mconv7_stage6_L2 (Conv2D): [[1L, 19L, 46L, 46L]]
mace_output_node_Mconv7_stage6_L2 (Transpose): [[1L, 46L, 46L, 19L]]
start optimize memory.
total op: 95
0 CPU_BUFFER [8667136L]
1 CPU_BUFFER [8667136L]
2 CPU_BUFFER [1083392L]
3 CPU_BUFFER [1083392L]
origin mem: 63306488, optimized mem: 19501056
Memory optimization done.
Traceback (most recent call last):
  File "/home/songbiao/libo/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 319, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/songbiao/libo/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 208, in main
    FLAGS.model_graph_format)
  File "/home/songbiao/libo/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/model_saver.py", line 286, in save_model
    save_model_data(net_def, model_tag, output_dir)
  File "/home/songbiao/libo/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/model_saver.py", line 176, in save_model_data
    model_data = extract_model_data(net_def)
  File "/home/songbiao/libo/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/model_saver.py", line 169, in extract_model_data
    model_data.extend(tensor_info.data)
MemoryError
Traceback (most recent call last):
  File "tools/converter.py", line 1726, in <module>
    flags.func(flags)
  File "tools/converter.py", line 817, in convert_func
    convert_model(configs)
  File "tools/converter.py", line 743, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/songbiao/libo/mace/tools/sh_commands.py", line 528, in gen_model_code
    _fg=True)
  File "/home/songbiao/anaconda2/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/songbiao/anaconda2/bin/python bazel-bin/mace/python/tools/converter -u --platform=caffe --model_file=/home/songbiao/libo/model/openpose/caffe/1.prototxt --weight_file=/home/songbiao/libo/model/openpose/caffe/1.caffemodel --model_checksum=52bc10ec3d309514b36be8c4f382a5e7b1cfc8cbd3f995c2b580cf0a17aeb7ef --weight_checksum=b4cf475576abd7b15d5316f1ee65eb492b5c9f5865e70a2e7882ed31fb682549 --input_node=image --output_node=Mconv7_stage6_L2 --runtime=cpu --template=mace/python/tools --model_tag=openposecaffe --input_shape=1,368,368,3 --dsp_mode=0 --embed_model_data=False --winograd=0 --quantize=0 --quantize_range_file= --obfuscate=0 --output_dir=mace/codegen/models/openposecaffe --model_graph_format=file --data_type=fp32 --graph_optimize_options=
```

**Comment by nolanliou** [comment]
It seems the memory is out of range. how much memory in your machine?

**Comment by leeburt** [comment]
I change mymachine`s memory from 4g to 6g,then bug is fixed.thanks.
