### ISSUE TITLE
 fatal error: 'omp.h' file not found

### ISSUE THREAD

**Issue by imu-hupeng** [XiaoMi/mace#18]
运行命令：
> python tools/converter.py build --config=/home/hupeng/model.yaml

应该是在交叉编译阶段，找不到头文件，错误信息如下：
```
ERROR: /home/hupeng/mace-0.8.1/mace/core/BUILD:19:1: C++ compilation of rule '//mace/core:core' failed (Exit 1): clang failed: error executing command 
  (cd /home/hupeng/.cache/bazel/_bazel_hupeng/38fa9861103f3de5771ea45d946ddd14/execroot/mace && \
  exec env - \
    PATH=/home/hupeng/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin:/home/hupeng/bin:/home/hupeng/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin \
    PWD=/proc/self/cwd \
  external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 -target aarch64-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fpic -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -O2 -g -DNDEBUG -MD -MF bazel-out/arm64-v8a-opt/bin/mace/core/_objs/core/mace/core/runtime/cpu/cpu_runtime.d '-frandom-seed=bazel-out/arm64-v8a-opt/bin/mace/core/_objs/core/mace/core/runtime/cpu/cpu_runtime.o' -iquote . -iquote bazel-out/arm64-v8a-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/arm64-v8a-opt/genfiles/external/bazel_tools -iquote external/com_google_protobuf -iquote bazel-out/arm64-v8a-opt/genfiles/external/com_google_protobuf -iquote external/opencl_clhpp -iquote bazel-out/arm64-v8a-opt/genfiles/external/opencl_clhpp -iquote external/opencl_headers -iquote bazel-out/arm64-v8a-opt/genfiles/external/opencl_headers -iquote external/half -iquote bazel-out/arm64-v8a-opt/genfiles/external/half -Ibazel-out/arm64-v8a-opt/bin/external/opencl_headers/_virtual_includes/opencl20_headers -isystem external/com_google_protobuf/src -isystem bazel-out/arm64-v8a-opt/genfiles/external/com_google_protobuf/src -isystem bazel-out/arm64-v8a-opt/bin/external/com_google_protobuf/src '-std=c++11' -D_GLIBCXX_USE_C99_MATH_TR1 -DMACE_OBFUSCATE_LITERALS -O3 -ffunction-sections -fdata-sections -Werror -Wextra -Wno-missing-field-initializers -fopenmp -DMACE_ENABLE_OPENMP -DMACE_ENABLE_OPENCL -DMACE_ENABLE_NEON '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm64' -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -c mace/core/runtime/cpu/cpu_runtime.cc -o bazel-out/arm64-v8a-opt/bin/mace/core/_objs/core/mace/core/runtime/cpu/cpu_runtime.o)

Use --sandbox_debug to see verbose messages from the sandbox
mace/core/runtime/cpu/cpu_runtime.cc:18:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^
1 error generated.
Target //mace/tools/validation:mace_run_static failed to build
INFO: Elapsed time: 136.445s, Critical Path: 109.80s
INFO: 186 processes: 186 linux-sandbox.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "tools/converter.py", line 1348, in <module>
    flags.func(flags)
  File "tools/converter.py", line 888, in build_library
    flags.disable_openmp, flags.address_sanitizer)
  File "tools/converter.py", line 851, in generate_library
    tuning, enable_openmp, address_sanitizer)
  File "tools/converter.py", line 720, in build_specific_lib
    address_sanitizer=address_sanitizer
  File "/home/hupeng/mace-0.8.1/tools/sh_commands.py", line 323, in bazel_build
    *bazel_args)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/bazel build //mace/tools/validation:mace_run_static --config android --cpu=arm64-v8a --define neon=true --define openmp=true --define hexagon=false --config optimization

  STDOUT:


  STDERR:
```

**Comment by llhe** [comment]
OpenMP的依赖问题。

请检查一下Bazel和NDK的版本： https://mace.readthedocs.io/en/latest/getting_started/how_to_build.html

**Comment by TonyMou** [comment]
ndk 用12b或15c或16b版本。

**Comment by imu-hupeng** [comment]
最后用了r16b,成功了。
总结下在转换pb文件到c++代码的时候踩的各种坑，argmax这个op文档上说支持，用的时候报错不支持，还好这个op是网络图的最后一个节点，直接删了关系也不大。大坑就是跑的时候需要至少5个G的内存，否则会出现各种killed~
最后感谢大牛帮忙解决了 omp.h 的坑，没仔细看文档的锅，用错了ndk版本
