### ISSUE TITLE
tensorflow batch normalization layer support problem

### ISSUE THREAD

**Issue by oneTaken** [XiaoMi/mace#181]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **NDK version(e.g., 15c)**: r12b
- **GCC version(if compiling for host, e.g., 5.4.0)**: 5.4.0
- **MACE version (Use the command: git describe --long --tags)**: v0.9.0-67-g0a14e02
- **Python version(2.7)**: 2.7
- **Bazel version (e.g., 0.13.0)**:0.13.0

### Model deploy file (*.yml)
```yaml
library_name: exp_test_16
target_abis: [armeabi-v7a]
# target_socs: [msm8996]
embed_model_data: 1
build_type: code
model_graph_format: code
model_data_format: code
vlog_level: 5
models:
  super_resolution_x1:
    platform: tensorflow
    model_file_path: /home/deepmind/projects/mace/test/model/pbfile/exp_test_16/model-text-false.pb
    model_sha256_checksum: e89e278f87d8761986c5e3dbdad87008647109378dd9f91638dcdd120aff4af6
    subgraphs:
      - input_tensors:
          - Placeholder
        input_shapes:
          - 1,216,216,3
        output_tensors:
          - sub
        output_shapes:
          - 1,216,216,3
    runtime: cpu+gpu
    winograd: 0
    limit_opencl_kernel_time: 1
    nnlib_graph_mode: 0
    obfuscate: 1
    winograd: 0
```

### Describe the problem
When use model with `tf.layers.batch_normalization` layer, it would raise `ValueError: cannot call `vectorize` on size 0 inputs unless `otypes` is set` when converting model `.pb` file using `python tools/convert.py ocnvert --config my_config_show_above.yml`.

In the error message, I found problem in the [convert_fused_batchnorm](https://github.com/XiaoMi/mace/blob/master/mace/python/tools/converter_tool/tensorflow_converter.py/#L493~L507/) function, the `mean_value` and the `var_value` are empty array, so the `np.vectorize` function would raise error.

In the `.pb` file with `as_text=True`, the corresponding batch_norm lines are as follow:
```yaml
node {
  name: "block_0/bn_1/Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
          }
        }
      }
    }
  }
}
node {
  name: "block_0/bn_1/Const_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
          }
        }
      }
    }
  }
}
node {
  name: "block_0/bn_1/FusedBatchNorm"
  op: "FusedBatchNorm"
  input: "block_0/identity_conv/Conv2D"
  input: "block_0/bn_1/gamma/read"
  input: "block_0/bn_1/beta/read"
  input: "block_0/bn_1/Const"
  input: "block_0/bn_1/Const_1"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "data_format"
    value {
      s: "NHWC"
    }
  }
  attr {
    key: "epsilon"
    value {
      f: 0.0010000000474974513
    }
  }
  attr {
    key: "is_training"
    value {
      b: true
    }
  }
}
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/sparse/lil.py:16: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _csparsetools
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/spatial/__init__.py:94: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .ckdtree import *
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/spatial/__init__.py:95: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .qhull import *
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/spatial/_spherical_voronoi.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _voronoi
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/spatial/distance.py:121: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _hausdorff
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/linalg/basic.py:17: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._solve_toeplitz import levinson
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/linalg/__init__.py:202: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._decomp_update import *
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/special/__init__.py:640: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ufuncs import *
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/special/_ellip_harm.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/optimize/_trlib/__init__.py:1: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._trlib import TRLIBQuadraticSubproblem
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/optimize/_numdiff.py:8: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._group_columns import group_dense, group_sparse
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/interpolate/_bsplines.py:9: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _bspl
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/stats/_continuous_distns.py:17: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _stats
--------------------------------------
         Common Configuration         
--------------------------------------
|        key        |     value      |
======================================
|       library_name|     exp_test_16|
--------------------------------------
|        target_abis| ['armeabi-v7a']|
--------------------------------------
|        target_socs|              []|
--------------------------------------
| model_graph_format|            code|
--------------------------------------
|  model_data_format|            code|
--------------------------------------

* Generate mace engine creator source
Generate mace engine creator source done!

*****************************************************
          Convert super_resolution_x2 model          
*****************************************************

INFO: Analysed target //mace/python/tools:converter (0 packages loaded).
INFO: Found 1 target...
Target //mace/python/tools:converter up-to-date:
  bazel-bin/mace/python/tools/converter
INFO: Elapsed time: 0.433s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

Transform model to one that can better run on device
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/sparse/lil.py:16: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _csparsetools
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/linalg/basic.py:17: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._solve_toeplitz import levinson
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/linalg/__init__.py:202: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._decomp_update import *
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/special/__init__.py:640: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ufuncs import *
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/special/_ellip_harm.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/optimize/_trlib/__init__.py:1: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._trlib import TRLIBQuadraticSubproblem
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/optimize/_numdiff.py:8: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._group_columns import group_dense, group_sparse
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/interpolate/_bsplines.py:9: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _bspl
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/spatial/__init__.py:94: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .ckdtree import *
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/spatial/__init__.py:95: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .qhull import *
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/spatial/_spherical_voronoi.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _voronoi
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/spatial/distance.py:121: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _hausdorff
/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/scipy/ndimage/measurements.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _ni_label
(array([], dtype=float32), 0.0010000000474974513, array([0.9290327 , 0.91793925, 1.0876399 , 0.860036  , 0.96557355,
       1.0966089 , 0.9426421 , 0.9513479 ], dtype=float32))
Traceback (most recent call last):
  File "/home/deepmind/projects/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 319, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/deepmind/projects/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 146, in main
    output_graph_def = converter.run()
  File "/home/deepmind/projects/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 221, in run
    self.convert_ops()
  File "/home/deepmind/projects/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 266, in convert_ops
    self._op_converters[tf_op.type](tf_op)
  File "/home/deepmind/projects/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 482, in convert_fused_batchnorm
    var_value + epsilon_value)) * gamma_value)
  File "/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/numpy/lib/function_base.py", line 1972, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/numpy/lib/function_base.py", line 2042, in _vectorize_call
    ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
  File "/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/numpy/lib/function_base.py", line 1998, in _get_ufunc_and_otypes
    raise ValueError('cannot call `vectorize` on size 0 inputs '
ValueError: cannot call `vectorize` on size 0 inputs unless `otypes` is set
Traceback (most recent call last):
  File "tools/converter.py", line 1754, in <module>
    flags.func(flags)
  File "tools/converter.py", line 841, in convert_func
    convert_model(configs)
  File "tools/converter.py", line 766, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/deepmind/projects/mace/tools/sh_commands.py", line 531, in gen_model_code
    _fg=True)
  File "/home/deepmind/anaconda3/envs/mace/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/deepmind/anaconda3/envs/mace/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=/home/deepmind/projects/mace/test/model/pbfile/exp_test_16/model-text-false.pb --weight_file= --model_checksum=f9e3eb0196a4342b4a1563f645642f0f0627b1ff4b5e96c3fd82ebbe4d44058a --weight_checksum= --input_node=Placeholder --output_node=sub --runtime=cpu+gpu --template=mace/python/tools --model_tag=super_resolution_x2 --input_shape=1,216,216,3 --dsp_mode=0 --embed_model_data=True --winograd=0 --quantize=0 --quantize_range_file= --obfuscate=1 --output_dir=mace/codegen/models/super_resolution_x2 --model_graph_format=code --data_type=fp16_fp32 --graph_optimize_options=

  STDOUT:


  STDERR:

```

### Additional context
I saw the ops list in the document that the `batch norm Fusion with activation is supported.` I do not clearly know about this. And I think it's the `batch_norm` layer `fuse=True` mode. If I use `fuse=False` mode, more operations are not support.

**Comment by liyinhgqw** [comment]
Can you provide the input shape of this BN op ? It is weird the 'mean' and 'var' are scalar instead of a vector.

And which version of tensorflow you use to generate proto model ?

**Comment by oneTaken** [comment]
@liyinhgqw 
All the tensors flow the graph is of shape` [n,64,64,c]`, controlled by the `conv` parameter `padding=same`,
There is only three kinds of layers in the model, `conv`,`relu`,`bn`.
If only remove `bn`, the mace convert the model rightly.

And the version to generate proto model is `1.10.0`. And I use the mace virtualenv `python=2.7` & `tensorflow=1.6.0 ` convert again, same situation.

What about the showed value in the error info is that,

> (array([], dtype=float32), 0.0010000000474974513, array([0.9290327 , 0.91793925, 1.0876399 , 0.860036  , 0.96557355,
       1.0966089 , 0.9426421 , 0.9513479 ], dtype=float32))

I add `print` function `print(var_value, epsilon_value, gamma_value)` to show what's wrong in the next line of the convert code file:
`scale_value = (
            (1.0 / np.vectorize(math.sqrt)(
                var_value + epsilon_value)) * gamma_value)`

**Comment by liyinhgqw** [comment]
Problem is 
```
  attr {
    key: "is_training"
    value {
      b: true
    }
  }
```

you should set `is_training` to false when export inference model.

**Comment by oneTaken** [comment]
Hmm, thx.
I will fix this and report what's going.
