### ISSUE TITLE
Convert resnet_v1_50 error!!

### ISSUE THREAD

**Issue by WenguoLi** [XiaoMi/mace#219]
(1) resnet_v1_50.yml

library_name: resnet_v1_50
target_abis: [armeabi-v7a, arm64-v8a]
model_graph_format: code
model_data_format: file
models:
  resnet_v1_50:
    platform: tensorflow
    model_file_path: /home/apuser/deeplearning/XiaoMi/mace-models/resnet_v1_50/resnet_v1_50.pb
    model_sha256_checksum: b991adf5db5bb68f5d739627a8a561689095c133e8649fe725c8a407d924e7ea
    subgraphs:
      - input_tensors:
          - input
        output_tensors:
          - resnet_v1_50/predictions/Reshape_1
        input_shapes:
          - 1,224,224,3
        output_shapes:
          - 1,1000
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0

(2) python tools/converter.py convert --config=../mace-models/resnet_v1_50/resnet_v1_50.yml
....
resnet_v1_50/block4/unit_3/bottleneck_v1/add (Eltwise): [[1L, 2048L, 7L, 7L]]
resnet_v1_50/block4/unit_3/bottleneck_v1/Relu (Activation): [[1L, 2048L, 7L, 7L]]
resnet_v1_50/pool5 (ReduceMean): [[1L, 2048L, 1L, 1L]]
resnet_v1_50/logits/Conv2D (Conv2D): [[1L, 1000L, 1L, 1L]]
resnet_v1_50/SpatialSqueeze (Squeeze): [[1L, 1000L]]
resnet_v1_50/predictions/Softmax (Softmax): [[1L, 1000L]]
mace_output_node_resnet_v1_50/predictions/Reshape_1 (Identity): [[1L, 1000L]]
start optimize cpu memory.
total op: 99
0 [802816L]
1 [802816L]
2 [802816L]
origin mem: 19464588, optimized mem: 2408448
CPU memory optimization done.
Merge cpu and gpu ops together
Merge done
Traceback (most recent call last):
  File "tools/converter.py", line 1595, in <module>
    flags.func(flags)
  File "tools/converter.py", line 785, in convert_func
    convert_model(configs)
  File "tools/converter.py", line 711, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/apuser/deeplearning/XiaoMi/mace/tools/sh_commands.py", line 524, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.SignalException_SIGSEGV: 

  RAN: /usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=/home/apuser/deeplearning/XiaoMi/mace-models/resnet_v1_50/resnet_v1_50.pb --weight_file= --model_checksum=b991adf5db5bb68f5d739627a8a561689095c133e8649fe725c8a407d924e7ea --weight_checksum= --input_node=input --output_node=resnet_v1_50/predictions/Reshape_1 --runtime=cpu+gpu --template=mace/python/tools --model_tag=resnet_v1_50 --input_shape=1,224,224,3 --dsp_mode=0 --embed_model_data=False --winograd=0 --obfuscate=0 --output_dir=mace/codegen/models/resnet_v1_50 --model_graph_format=code --data_type=fp16_fp32 --graph_optimize_options=

  STDOUT:

  STDERR:

**Comment by yejw5** [comment]
@WenguoLi Please reformat your issue description. You can refer to [Mace template](https://github.com/XiaoMi/mace/blob/master/ISSUE_TEMPLATE.md)
