### ISSUE TITLE
Error converting ResNet_v1_50 Tensorflow model

### ISSUE THREAD

**Issue by muendelezaji** [XiaoMi/mace#225]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **NDK version(e.g., 15c)**: 16b
- **GCC version(if compiling for host, e.g., 5.4.0)**: N/A
- **MACE version (Use the command: git describe --long --tags)**: v0.9.0-246-g1d40ca5
- **Python version(2.7)**: 2.7.12
- **Bazel version (e.g., 0.13.0)**: 0.13.0

### Environment
```shell
$ uname -v -m
#35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64

$ git describe --long --tags
v0.9.0-246-g1d40ca5

$ python --version
Python 2.7.12

$ bazel version
Starting local Bazel server and connecting to it...
...........
Build label: 0.13.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Oct 18 21:33:40 +50297 (1525078013620)
Build timestamp: 1525078013620
Build timestamp as int: 1525078013620

$ cmake --version
cmake version 3.11.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).

$ pip list | egrep -i '^(jinja2|pyyaml|sh|numpy|six|tensorflow|scipy|filelock) '
filelock                           3.0.0
Jinja2                             2.10
numpy                              1.14.0
PyYAML                             3.12
scipy                              1.0.0
sh                                 1.12.14
six                                1.11.0
tensorflow                         1.6.0

$ sed -n '/^Pkg.Revision/p' $ANDROID_NDK_HOME/source.properties
Pkg.Revision = 16.1.4479499

$ adb --version
Android Debug Bridge version 1.0.40
Version 4797878
Installed as /home/ML/.android/platform-tools/adb
```

### Model deploy file (*.yml)
```yaml
library_name: resnet-v1-50-tf
target_abis: [arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  resnet_v1_50_tf:
    platform: tensorflow
    model_file_path: https://deepdetect.com/models/tf/resnet_v1_50/resnet_v1_50.pb
    model_sha256_checksum: 10dd47ec8402ffc8905b6df89b06373cb38ce7ac3b3cf099bca2f97442c1346c
    subgraphs:
      - input_tensors: input
        output_tensors: resnet_v1_50/predictions/Reshape_1
        input_shapes: 1,224,224,3
        output_shapes: 1,1001
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
```

### Describe the problem
I tried following [the user guide](https://mace.readthedocs.io/en/latest/user_guide/basic_usage.html#prepare-your-model) to convert a Tensorflow [ResNet v1 50 model](https://deepdetect.com/models/tf/resnet_v1_50/resnet_v1_50.pb) provided by [DeepDetect](https://deepdetect.com/) but it fails with the following error:
```python
  File "/home/ML/xiaomi/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'InputImage' with dtype float
         [[Node: InputImage = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config=../mace-models/resnet-v1-50/resnet-v1-50-tf.yml --target_abis=arm64-v8a
```

### Error information / logs
```bash
$ python tools/converter.py convert --config=../mace-models/resnet-v1-50/resnet-v1-50-tf.yml --target_abis=arm64-v8a
--------------------------------------
         Common Configuration         
--------------------------------------
|        key        |     value      |
======================================
|       library_name| resnet-v1-50-tf|
--------------------------------------
|        target_abis|   ['arm64-v8a']|
--------------------------------------
|        target_socs|              []|
--------------------------------------
| model_graph_format|            file|
--------------------------------------
|  model_data_format|            file|
--------------------------------------

*************************************************
          Convert resnet_v1_50_tf model          
*************************************************

INFO: Analysed target //mace/python/tools:converter (0 packages loaded).
INFO: Found 1 target...
Target //mace/python/tools:converter up-to-date:
  bazel-bin/mace/python/tools/converter
INFO: Elapsed time: 0.274s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

Transform model to one that can better run on device
Traceback (most recent call last):
  File "/home/ML/xiaomi/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 352, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/ML/xiaomi/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 165, in main
    output_graph_def = converter.run()
  File "/home/ML/xiaomi/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 241, in run
    self.convert_ops(session)
  File "/home/ML/xiaomi/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 293, in convert_ops
    self.update_output_shapes(sess)
  File "/home/ML/xiaomi/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 283, in update_output_shapes
    feed_dict=self._placeholders)
  File "/home/ML/xiaomi/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/ML/xiaomi/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ML/xiaomi/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/home/ML/xiaomi/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'InputImage' with dtype float
         [[Node: InputImage = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op u'InputImage', defined at:
  File "/home/ML/xiaomi/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 352, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/ML/xiaomi/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 154, in main
    option, FLAGS.model_file)
  File "/home/ML/xiaomi/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 231, in __init__
    tf.import_graph_def(tf_graph_def, name='')
  File "/home/ML/xiaomi/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/home/ML/xiaomi/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 553, in import_graph_def
    op_def=op_def)
  File "/home/ML/xiaomi/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/home/ML/xiaomi/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'InputImage' with dtype float
         [[Node: InputImage = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Traceback (most recent call last):
  File "tools/converter.py", line 1778, in <module>
    flags.func(flags)
  File "tools/converter.py", line 856, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 781, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/ML/xiaomi/mace/tools/sh_commands.py", line 601, in gen_model_code
    _fg=True)
  File "/home/ML/xiaomi/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/ML/xiaomi/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=builds/downloads/949dc80fb249840230c673e6a665fd16.pb --weight_file= --model_checksum=10dd47ec8402ffc8905b6df89b06373cb38ce7ac3b3cf099bca2f97442c1346c --weight_checksum= --input_node=input --output_node=resnet_v1_50/predictions/Reshape_1 --runtime=cpu+gpu --template=mace/python/tools --model_tag=resnet_v1_50_tf --input_shape=1,224,224,3 --input_range= --dsp_mode=0 --embed_model_data=False --winograd=0 --quantize=0 --quantize_range_file= --change_concat_ranges=0 --obfuscate=0 --output_dir=mace/codegen/models/resnet_v1_50_tf --model_graph_format=file --data_type=fp16_fp32 --graph_optimize_options= --cl_mem_type=image

  STDOUT:


  STDERR:

```

**Comment by yejw5** [comment]
It seems that you haven't optimize the model with [TensorFlow Transform Graph](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md).

**Comment by muendelezaji** [comment]
Sorry to raise this again, but even after optimisation with TensorFlow Transform Graph, it appears that I get the same error.
Are there any specific operations that need to be optimised/removed in the model? (or sample ```transform_graph``` command line for resnet50)
