### ISSUE TITLE
InvalidArgumentError: You must feed a value for placeholder tensor 'rnet/input' with dtype float and shape [?,24,24,3]

### ISSUE THREAD

**Issue by hmztl976** [XiaoMi/mace#231]
### System information
- **Linux Ubuntu 16.04 x64
- **NDK version 15c
- **gcc version 5.4.1 20160904 (Ubuntu 5.4.1-2ubuntu1~16.04)
- **MACE version 0.9.0
- **Python version 2.7.12
- **Bazel version (0.13.0)

### Model deploy file (*.yml)
```yaml
library_name: face-detection
target_abis: [host]
model_graph_format: file
model_data_format: file
models:
  face_detection:
    platform: tensorflow
    model_file_path: /home/lxy/MACE/MACE-Face-Detection-Demo/model/saved_model_dir_signature/MTCNN.pb
    model_sha256_checksum: ace5461cadc1f359b528a8198f1a0acebae3c53a08d4c389f42086ec1f3a974a
    subgraphs:
      - input_tensors:
          - pnet/input:0
        input_shapes:
          - 1,480,640,3
        output_tensors:
          - pnet/conv4-2/BiasAdd:0
          - pnet/prob1:0
        output_shapes:
          - 1,480,640,4
          - 1,480,640,2
      - input_tensors:
          - rnet/input:0
        input_shapes:
          - 240,24,24,3
        output_tensors:
          - rnet/conv5-2/conv5-2:0
          - rnet/prob1:0
        output_shapes:
          - 640,4
          - 640,2
      - input_tensors:
          - onet/input:0
        input_shapes:
          - 20,48,48,3
        output_tensors:
          - onet/conv6-2/conv6-2:0
          - onet/conv6-3/conv6-3:0
          - onet/prob1:0
        output_shapes:
          - 100,100
          - 100,100
          - 100,100
    runtime: cpu
    limit_opencl_kernel_time: 0
    dsp_mode: 0
    obfuscate: 1
    winograd: 0
```

### Describe the problem
InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'rnet/input' with dtype float and shape [?,24,24,3]
	 [[Node: rnet/input = Placeholder[dtype=DT_FLOAT, shape=[?,24,24,3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Why does the converter fail to recognize the shape of 'rnet/input'?
How to solve this?

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
$ python tools/converter.py convert --config=../MACE-Face-Detection-Demo/model/face-detection.yml
-------------------------------------
         Common Configuration        
-------------------------------------
|        key        |     value     |
=====================================
|       library_name| face-detection|
-------------------------------------
|        target_abis|       ['host']|
-------------------------------------
|        target_socs|             []|
-------------------------------------
| model_graph_format|           file|
-------------------------------------
|  model_data_format|           file|
-------------------------------------

************************************************
          Convert face_detection model          
************************************************

INFO: Analysed target //mace/python/tools:converter (0 packages loaded).
INFO: Found 1 target...
Target //mace/python/tools:converter up-to-date:
  bazel-bin/mace/python/tools/converter
INFO: Elapsed time: 0.624s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

Transform model to one that can better run on device
Traceback (most recent call last):
  File "/home/lxy/MACE/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 305, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/lxy/MACE/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 144, in main
    output_graph_def = converter.run()
  File "/home/lxy/MACE/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 217, in run
    self.convert_ops()
  File "/home/lxy/MACE/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 262, in convert_ops
    self._op_converters[tf_op.type](tf_op)
  File "/home/lxy/MACE/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 353, in convert_conv2d
    op = self.convert_general_op(tf_op)
  File "/home/lxy/MACE/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 320, in convert_general_op
    output_shape.dims.extend(self.infer_tensor_shape(tf_output))
  File "/home/lxy/MACE/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 306, in infer_tensor_shape
    tensor_shape = tf.shape(tensor).eval(feed_dict=self._placeholders)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 656, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 4901, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'rnet/input' with dtype float and shape [?,24,24,3]
	 [[Node: rnet/input = Placeholder[dtype=DT_FLOAT, shape=[?,24,24,3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op u'rnet/input', defined at:
  File "/home/lxy/MACE/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 305, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/lxy/MACE/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 134, in main
    option, FLAGS.model_file)
  File "/home/lxy/MACE/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 210, in __init__
    tf.import_graph_def(tf_graph_def, name='')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 553, in import_graph_def
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'rnet/input' with dtype float and shape [?,24,24,3]
	 [[Node: rnet/input = Placeholder[dtype=DT_FLOAT, shape=[?,24,24,3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Traceback (most recent call last):
  File "tools/converter.py", line 1595, in <module>
    flags.func(flags)
  File "tools/converter.py", line 785, in convert_func
    convert_model(configs)
  File "tools/converter.py", line 711, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/lxy/MACE/mace/tools/sh_commands.py", line 524, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=/home/lxy/MACE/MACE-Face-Detection-Demo/model/saved_model_dir_signature/MTCNN.pb --weight_file= --model_checksum=ace5461cadc1f359b528a8198f1a0acebae3c53a08d4c389f42086ec1f3a974a --weight_checksum= --input_node=pnet/input:0 --output_node=pnet/conv4-2/BiasAdd:0,pnet/prob1:0 --runtime=cpu --template=mace/python/tools --model_tag=face_detection --input_shape=1,480,640,3 --dsp_mode=0 --embed_model_data=False --winograd=0 --obfuscate=1 --output_dir=mace/codegen/models/face_detection --model_graph_format=file --data_type=fp32 --graph_optimize_options=

  STDOUT:


  STDERR:
```

**Comment by 395062753** [comment]
请问你解决这个问题了么，我也遇到了同样的问题了
