### ISSUE TITLE
请问python tools/converter.py run --config=/path/to/model_deployment_file.yml --validate失败是什么原因

### ISSUE THREAD

**Issue by jolinlinlin** [XiaoMi/mace#249]
### System information
- **Linux Ubuntu 16.04 LTS**:
- **NDK version: 15c**:
- **GCC version:5.4.0**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version:0.13.0**:

### Model deploy file (*.yml)
```library_name: mobilenet-v2
target_abis: [armeabi-v7a, arm64-v8a]
model_graph_format: code
model_data_format: code
models:
  mobilenet_v2:
    platform: tensorflow
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v2/mobilenet-v2-1.0.pb
    model_sha256_checksum: 369f9a5f38f3c15b4311c1c84c032ce868da9f371b5f78c13d3ea3c537389bb4
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,224,224,3
        output_tensors:
          - MobilenetV2/Predictions/Reshape_1
        output_shapes:
          - 1,1001
        validation_inputs_data:
          - /home/zhoulin/MACE/mace/mace-models/mobilenet-v2/mobilenet-v2.yml
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
......
```
###问题
我按照官网教程搭建好了mace环境,并将mace-models文件夹中的mobilenet-v2转化成功,python tools/converter.py run --config=/home/zhoulin/MACE/mace/mace-models/mobilenet-v2/mobilenet-v2.yml --round=100 命令也运行成功,但在执行命令python tools/converter.py run --config=/home/zhoulin/MACE/mace/mace-models/mobilenet-v2/mobilenet-v2.yml --validate时,
###出现以下错误:

```
* Build //mace/tools/validation:mace_run_static with ABI armeabi-v7a
('build', '//mace/tools/validation:mace_run_static', '--config', 'android', '--cpu=armeabi-v7a', '--define', 'neon=true', '--define', 'openmp=true', '--define', 'opencl=true', '--define', 'hexagon=false', '--config', 'optimization', '--per_file_copt=mace/tools/validation/mace_run.cc@-DMODEL_GRAPH_FORMAT_CODE')
WARNING: Processed legacy workspace file /home/zhoulin/MACE/mace/tools/bazel.rc. This file will not be processed in the next release of Bazel. Please read https://github.com/bazelbuild/bazel/issues/6319 for further information, including how to upgrade.
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //mace/tools/validation:mace_run_static (0 packages loaded).
INFO: Found 1 target...
Target //mace/tools/validation:mace_run_static up-to-date:
  bazel-bin/mace/tools/validation/mace_run_static
INFO: Elapsed time: 1.269s, Critical Path: 0.06s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
Build done!

**************************************************
          Run model mobilenet_v2 on MI5X          
**************************************************

Generate input file:  builds/mobilenet-v2/_tmp/mobilenet_v2/d4e627ce1b15ed6f96aefffe315a8dc8/general/armeabi-v7a/model_input_input
Generate input file done.
* Run 'mobilenet_v2' with round=1, restart_round=1, tuning=False, out_of_range_check=False, omp_num_threads=(-1,), cpu_affinity_policy=(1,), gpu_perf_hint=(3,), gpu_priority_hint=(3,)
Push builds/mobilenet-v2/_tmp/mobilenet_v2/d4e627ce1b15ed6f96aefffe315a8dc8/general/armeabi-v7a/model_input_input to /data/local/tmp/mace_run
Push third_party/nnlib/libhexagon_controller.so to /data/local/tmp/mace_run
Push builds/mobilenet-v2/_tmp/armeabi-v7a/mace_run_static to /data/local/tmp/mace_run
Push /tmp/cmd_file-mobilenet_v2-1541664322.51 to /data/local/tmp/mace_run/cmd_file-mobilenet_v2-1541664322.51
WARNING: linker: /data/local/tmp/mace_run/mace_run_static: unused DT entry: type 0xf arg 0x885
I mace_run.cc:428 model name: mobilenet_v2
I mace_run.cc:429 mace version: v0.9.0-0-gb23889d-20181017
I mace_run.cc:430 input node: input
I mace_run.cc:431 input shape: 1,224,224,3
I mace_run.cc:432 output node: MobilenetV2/Predictions/Reshape_1
I mace_run.cc:433 output shape: 1,1001
I mace_run.cc:434 input_file: /data/local/tmp/mace_run/model_input
I mace_run.cc:435 output_file: /data/local/tmp/mace_run/model_out
I mace_run.cc:436 model_data_file: /data/local/tmp/mace_run/mobilenet_v2.data
I mace_run.cc:437 model_file:
I mace_run.cc:438 device: CPU
I mace_run.cc:439 round: 1
I mace_run.cc:440 restart_round: 1
I mace_run.cc:441 gpu_perf_hint: 3
I mace_run.cc:442 gpu_priority_hint: 3
I mace_run.cc:443 omp_num_threads: -1
I mace_run.cc:444 cpu_affinity_policy: 1
I mace_run.cc:467 restart round 0
I mace.cc:203 Creating MaceEngine, MACE version: v0.9.0-0-gb23889d-20181017
I mace.cc:211 Initializing MaceEngine
I mace_run.cc:273 Total init latency: 48.551 ms
I mace_run.cc:313 Warm up run
I mace_run.cc:343 1st warm up run latency: 220.972 ms
I mace_run.cc:350 Run model
I mace_run.cc:392 Average latency: 149.057 ms
========================================
            init      warmup     run_avg
========================================
time      48.551     220.972     149.057
I mace_run.cc:415 Write output file /data/local/tmp/mace_run/model_out_MobilenetV2_Predictions_Reshape_1 with size 1001 done.
I mace.cc:299 Destroying MaceEngine
Running finished!

* Validate with tensorflow
Pull /data/local/tmp/mace_run/model_out_MobilenetV2_Predictions_Reshape_1 to builds/mobilenet-v2/_tmp/mobilenet_v2/d4e627ce1b15ed6f96aefffe315a8dc8/general/armeabi-v7a
Traceback (most recent call last):
  File "tools/converter.py", line 1595, in <module>
    flags.func(flags)
  File "tools/converter.py", line 1248, in run_mace
    target_soc, serial_num)
  File "tools/converter.py", line 1168, in run_specific_target
    caffe_env=flags.caffe_env)
  File "/home/zhoulin/MACE/mace/tools/sh_commands.py", line 815, in validate_model
    ",".join(input_nodes), ",".join(output_nodes))
  File "/home/zhoulin/MACE/mace/tools/validate.py", line 180, in validate
    output_names)
  File "/home/zhoulin/MACE/mace/tools/validate.py", line 102, in validate_tf_model
    input_value = input_value.reshape(input_shapes[i])
ValueError: cannot reshape array of size 198 into shape (1,224,224,3)

```
请问出现这个问题的原因是什么,该怎么解决?

**Comment by TonyMou** [comment]
validation_inputs_data:
          - /home/zhoulin/MACE/mace/mace-models/mobilenet-v2/mobilenet-v2.yml

输入数据应该是npy的

**Comment by jolinlinlin** [comment]
@TonyMou 非常谢谢您的回答,我的问题解决了
