### ISSUE TITLE
[sdm660][Inception-v3]Failed to disable DSP DCVS: 2c  

### ISSUE THREAD

**Issue by samsun639** [XiaoMi/mace#25]
**step1,** 
diff --git a/inception-v3/inception-v3-dsp.yml b/inception-v3/inception-v3-dsp.yml
index edba4cb..50d3f7a 100644
--- a/inception-v3/inception-v3-dsp.yml
+++ b/inception-v3/inception-v3-dsp.yml
@@ -1,6 +1,6 @@
 library_name: inception-v3-dsp
 target_abis: [armeabi-v7a]
-target_socs: [sdm845]
+target_socs: [all]
 embed_model_data: 0
 build_type: code
 models:

**step2.** 
python tools/converter.py build --config=mace-models/inception-v3/inception-v3-dsp.yml

**step3.**
python tools/converter.py run --config=mace-models/inception-v3/inception-v3-dsp.yml

--------After step3 -----------
It shows error as below:

Init hexagon with max attributes.

Failed to disable DSP DCVS: 2c

F mace.cc:165 Check failed: hexagon_controller_->Config() hexagon config error
Aborted
Traceback (most recent call last):
  File "tools/converter.py", line 1348, in <module>
    flags.func(flags)
  File "tools/converter.py", line 1087, in run_mace
    target_soc, serial_num)
  File "tools/converter.py", line 1038, in run_specific_target
    linkshared=linkshared,
  File "/local/mnt/mace/tools/sh_commands.py", line 792, in tuning_run
    _err_to_out=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 774, in __init__
    self.wait()
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_134: 

  RAN: /usr/bin/adb -s a358dab1 shell sh /data/local/tmp/mace_run/cmd_file-inception_v3_dsp-1530522619.74

  STDOUT:

  STDERR:

Could you help on this? Thanks!

**Comment by liyinhgqw** [comment]
Running models on Hexagon DSP need a few prerequisites for DSP developers:
1. You need make sure SOCs of your phone is manufactured by Qualcomm.
2. You need a phone that disables secure boot (once enabled, cannot be reversed, so you probably can only get that type phones from manufacturers)
3. You need sign your phone by using testsig provided by Qualcomm. (Download Qualcomm Hexagon SDK first, plugin your phone to PC, run scripts/testsig.py)
4. You need install Hexagon nnlib backend by following [nnlib]( https://source.codeaurora.org/quic/hexagon_nn/nnlib).
5. Then, there you go. You can run Mace on Hexagon DSP.

**Comment by samsun639** [comment]
@liyinhgqw  Thanks for feedback.

I can successfully run nnlib on my device now,  but still cannot run inception-v3 with MACE. New error like below.
Could you reproduce the issue on sdm660?
I noticed your DSP benchmark results are on SDM845, however i do not have SDM845.

---------------------------
Init hexagon with max attributes.

Failed to disable DSP DCVS: 8000040e

I hexagon_control_wrapper.cc:61 Hexagon init
F hexagon_control_wrapper.cc:62 Check failed: hexagon_nn_init(&nn_id_) == 0 hexagon_nn_init failed
Aborted
Traceback (most recent call last):
  File "tools/converter.py", line 1348, in <module>
    flags.func(flags)
  File "tools/converter.py", line 1087, in run_mace
    target_soc, serial_num)
  File "tools/converter.py", line 1038, in run_specific_target
    linkshared=linkshared,
  File "/local/mnt/mace/tools/sh_commands.py", line 792, in tuning_run
    _err_to_out=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 774, in __init__
    self.wait()
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_134: 

  RAN: /usr/bin/adb -s a358dab1 shell sh /data/local/tmp/mace_run/cmd_file-inception_v3_dsp-1530522326.02

  STDOUT:


  STDERR:

**Comment by liyinhgqw** [comment]
Hi samsun639,

We have reivised nnlib interface for the use of mace. We're working with opening source the nnlib backend part. We will notice you after that.

Thanks.

**Comment by llhe** [comment]
@samsun639 nnlib revised for mace is available here: https://github.com/XiaoMi/nnlib
