### ISSUE TITLE
在小米5x手机上验证模型失败

### ISSUE THREAD

**Issue by jolinlinlin** [XiaoMi/mace#250]
### System information
- **Linux Ubuntu 16.04 LTS**:
- **NDK version: 15c**:
- **GCC version:5.4.0:**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version:0.18.0**:

### Model deploy file (*.yml)
```library_name: LCNN
target_abis: [armeabi-v7a, arm64-v8a]
model_graph_format: code
model_data_format: code
models:
  LCNN:
    platform: caffe
    model_file_path: /home/zhoulin/MACE/mace/mace-models/LCNN/model/LCNN.prototxt
    weight_file_path: /home/zhoulin/MACE/mace/mace-models/LCNN/model/_iter_1428691.caffemodel
    model_sha256_checksum: 0a1c24ce57a87921ccf5f01fa3e39c7d9fea15aef6f50be877ce95846dafdcd7
    weight_sha256_checksum: 6e0fa4f40ac93552c6966032adf5b50475442be23498fd18951b91508af32874
    subgraphs:
      - input_tensors:
          - data
        input_shapes: 
          - 1,64,64,1
        output_tensors: 
          - eltwise_fc1
        output_shapes: 
          - 1,1,1,256
    runtime: gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
......
```

### problem
用搭好的MACE环境将自己的LCNN模型转化成功,在小米5X手机上run成功,但在执行python tools/converter.py run --config=/home/zhoulin/MACE/mace/mace-models/LCNN/LCNN.yml --validate
命令时,
### 出现问题:

```
* Build //mace/tools/validation:mace_run_static with ABI armeabi-v7a
('build', '//mace/tools/validation:mace_run_static', '--config', 'android', '--cpu=armeabi-v7a', '--define', 'neon=true', '--define', 'openmp=true', '--define', 'opencl=true', '--define', 'hexagon=false', '--config', 'optimization', '--per_file_copt=mace/tools/validation/mace_run.cc@-DMODEL_GRAPH_FORMAT_CODE')
WARNING: Processed legacy workspace file /home/zhoulin/MACE/mace/tools/bazel.rc. This file will not be processed in the next release of Bazel. Please read https://github.com/bazelbuild/bazel/issues/6319 for further information, including how to upgrade.
INFO: Analysed target //mace/tools/validation:mace_run_static (0 packages loaded).
INFO: Found 1 target...
Target //mace/tools/validation:mace_run_static up-to-date:
  bazel-bin/mace/tools/validation/mace_run_static
INFO: Elapsed time: 0.111s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
Build done!

******************************************
          Run model LCNN on MI5X          
******************************************

Generate input file:  builds/LCNN/_tmp/LCNN/1ad1e212eff794e80df2b8bfb6d362c0/general/armeabi-v7a/model_input_data
Generate input file done.
* Run 'LCNN' with round=1, restart_round=1, tuning=False, out_of_range_check=False, omp_num_threads=(-1,), cpu_affinity_policy=(1,), gpu_perf_hint=(3,), gpu_priority_hint=(3,)
Push builds/LCNN/_tmp/LCNN/1ad1e212eff794e80df2b8bfb6d362c0/general/armeabi-v7a/model_input_data to /data/local/tmp/mace_run
Push third_party/nnlib/libhexagon_controller.so to /data/local/tmp/mace_run
Push builds/LCNN/_tmp/armeabi-v7a/mace_run_static to /data/local/tmp/mace_run
Push /tmp/cmd_file-LCNN-1541663740.79 to /data/local/tmp/mace_run/cmd_file-LCNN-1541663740.79
WARNING: linker: /data/local/tmp/mace_run/mace_run_static: unused DT entry: type 0xf arg 0x885
I mace_run.cc:428 model name: LCNN
I mace_run.cc:429 mace version: v0.9.0-0-gb23889d-20181017
I mace_run.cc:430 input node: data
I mace_run.cc:431 input shape: 1,64,64,1
I mace_run.cc:432 output node: eltwise_fc1
I mace_run.cc:433 output shape: 1,1,1,256
I mace_run.cc:434 input_file: /data/local/tmp/mace_run/model_input
I mace_run.cc:435 output_file: /data/local/tmp/mace_run/model_out
I mace_run.cc:436 model_data_file: /data/local/tmp/mace_run/LCNN.data
I mace_run.cc:437 model_file:
I mace_run.cc:438 device: GPU
I mace_run.cc:439 round: 1
I mace_run.cc:440 restart_round: 1
I mace_run.cc:441 gpu_perf_hint: 3
I mace_run.cc:442 gpu_priority_hint: 3
I mace_run.cc:443 omp_num_threads: -1
I mace_run.cc:444 cpu_affinity_policy: 1
I mace_run.cc:467 restart round 0
W opencl_runtime.cc:302 There is no precompiled OpenCL binary file in [/data/local/tmp/mace_run/LCNN_compiled_opencl_kernel.MI5X.msm8953.bin]
I mace.cc:203 Creating MaceEngine, MACE version: v0.9.0-0-gb23889d-20181017
I mace.cc:211 Initializing MaceEngine
W tuner.h:144 Read OpenCL tuned parameters file failed.
I mace_run.cc:273 Total init latency: 3443.97 ms
I mace_run.cc:313 Warm up run
I mace_run.cc:343 1st warm up run latency: 3843.04 ms
I mace_run.cc:350 Run model
I mace_run.cc:392 Average latency: 74.783 ms
========================================
            init      warmup     run_avg
========================================
time    3443.971    3843.041      74.783
I mace_run.cc:415 Write output file /data/local/tmp/mace_run/model_out_eltwise_fc1 with size 256 done.
I mace.cc:299 Destroying MaceEngine
Running finished!

* Validate with caffe
Pull /data/local/tmp/mace_run/model_out_eltwise_fc1 to builds/LCNN/_tmp/LCNN/1ad1e212eff794e80df2b8bfb6d362c0/general/armeabi-v7a
Traceback (most recent call last):
  File "tools/converter.py", line 1595, in <module>
    flags.func(flags)
  File "tools/converter.py", line 1248, in run_mace
    target_soc, serial_num)
  File "tools/converter.py", line 1168, in run_specific_target
    caffe_env=flags.caffe_env)
  File "/home/zhoulin/MACE/mace/tools/sh_commands.py", line 833, in validate_model
    docker_image_id = sh.docker("images", "-q", image_name)
  File "/home/zhoulin/.local/lib/python2.7/site-packages/sh.py", line 3349, in __getattr__
    return self.__env[name]
  File "/home/zhoulin/.local/lib/python2.7/site-packages/sh.py", line 3226, in __getitem__
    raise CommandNotFound(k)
sh.CommandNotFound: docker
```

**Comment by TonyMou** [comment]
没有安装caffe吗？请参考文档。

**Comment by jolinlinlin** [comment]
@TonyMou 您好,请问必须要安装docker caffe吗?docker caffe只是在validate时候用还是在将转化好的caffe模型添加到安卓工程中时也需要?

**Comment by jolinlinlin** [comment]
@TonyMou 好的,谢谢您
