### ISSUE TITLE
Build Demo in Docker: convert model error

### ISSUE THREAD

**Issue by Terryhung** [XiaoMi/mace#261]
## Try to build android demo in examples folder

Run `./build.sh dynamic` in docker. 

Get Error
```
* Generate mace engine creator source
Generate mace engine creator source done!

**********************************************
          Convert mobilenet_v1 model
**********************************************

WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Analysed target //mace/python/tools:converter (20 packages loaded).
INFO: Found 1 target...
Target //mace/python/tools:converter up-to-date:
  bazel-bin/mace/python/tools/converter
INFO: Elapsed time: 5.936s, Critical Path: 0.21s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

Transform model to one that can better run on device
Traceback (most recent call last):
  File "tools/converter.py", line 1595, in <module>
    flags.func(flags)
  File "tools/converter.py", line 785, in convert_func
    convert_model(configs)
  File "tools/converter.py", line 711, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/root/mace/tools/sh_commands.py", line 524, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.SignalException_SIGILL:

  RAN: /usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=builds/downloads/f330dec17e45a8626cfb225ddce95051.pb --weight_file= --model_checksum=71b10f540ece33c49a7b51f5d4095fc9bd78ce46ebf0300487b2ee23d71294e6 --weight_checksum= --input_node=input --output_node=MobilenetV1/Predictions/Reshape_1 --runtime=cpu+gpu --template=mace/python/tools --model_tag=mobilenet_v1 --input_shape=1,224,224,3 --dsp_mode=0 --embed_model_data=True --winograd=0 --obfuscate=0 --output_dir=mace/codegen/models/mobilenet_v1 --model_graph_format=code --data_type=fp16_fp32 --graph_optimize_options=

  STDOUT:


  STDERR:


```

Then I try this one:

`/usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=builds/downloads/d4e627ce1b15ed6f96aefffe315a8dc8.pb --weight_file= --model_checksum=369f9a5f38f3c15b4311c1c84c032ce868da9f371b5f78c13d3ea3c537389bb4 --weight_checksum= --input_node=input --output_node=MobilenetV2/Predictions/Reshape_1 --runtime=cpu+gpu --template=mace/python/tools --model_tag=mobilenet_v2 --input_shape=1,224,224,3 --dsp_mode=0 --embed_model_data=False --winograd=0 --obfuscate=0 --output_dir=mace/codegen/models/mobilenet_v2`

Get:

```
Transform model to one that can better run on device
Illegal instruction (core dumped)
```

### Environment
- Docker Image: [registry.cn-hangzhou.aliyuncs.com/xiaomimace/mace-dev-lite].
- Git Branch: (HEAD detached at v0.9.0)

**Comment by lydoc** [comment]
I have tested in the docker but didn't reproduce this issue. Do you use the latest master branch MACE?
