### ISSUE TITLE
mace is looking for layer inputs that doesn't exist

### ISSUE THREAD

**Issue by YanBC** [XiaoMi/mace#263]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **NDK version(e.g., 15c)**: 15c
- **GCC version(if compiling for host, e.g., 5.4.0)**: 5.4.0
- **MACE version (Use the command: git describe --long --tags)**: v0.9.0-0-gb23889d
- **Python version(2.7)**: 2.7
- **Bazel version (e.g., 0.13.0)**: 0.13.0

### Model deploy file (*.yml)
```
library_name: ocr_recognizer
target_abis: [arm64-v8a]
target_socs: [msm8916]
model_graph_format: code
model_data_format: file
models:
  densenet:
      platform: tensorflow
      model_file_path: /workspace/mace-models/myIDCardOCR/densenet4mace.pb
      model_sha256_checksum: e27a4fdd2d4c9f3f04a05d640f4113531ed72d4b20b078d024663b29c280ef5d
      subgraphs:
        - input_tensors:
            - the_input
          input_shapes:
            - 1,32,512,1
          output_tensors:
            - out/sub
          output_shapes:
            - 1,4,64,192
      runtime: cpu+gpu
      limit_opencl_kernel_time: 0
      obfuscate: 0
      winograd: 0
```

### Model File
[https://github.com/YanBC/4mace/blob/master/densenet4mace.pb](url)

### Describe the problem
When I tried to convert it using tools/converter.py, I got prompt outputs like the followings:
```
Remove identity: dropout_4/Identity(Identity)
Traceback (most recent call last):
  File "/workspace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 305, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/workspace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 154, in main
    output_graph_def = mace_gpu_transformer.run()
  File "/workspace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 105, in run
    changed = transformer()
  File "/workspace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 1142, in transform_matmul_to_fc
    input_op = self._producer[op.input[0]]
KeyError: u'out/kernel:0'
Traceback (most recent call last):
  File "tools/converter.py", line 1595, in <module>
    flags.func(flags)
  File "tools/converter.py", line 785, in convert_func
    convert_model(configs)
  File "tools/converter.py", line 711, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/workspace/mace/tools/sh_commands.py", line 524, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
```
'out/kernel:0' isn't the input of 'dropout_4/Identity' layer, it is the input of another layer named 'out/transpose', so I am not entirely sure why it prompts something like that.
Also, I double checked the graph file (densenet4mace.pb) with tensorflow, the output is legit. I don't know what's wrong, please help!!!

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
root@DL:/workspace/mace# python tools/converter.py convert --config=../mace-models/myIDCardOCR/densenet.yml
-------------------------------------
         Common Configuration
-------------------------------------
|        key        |     value     |
=====================================
|       library_name| ocr_recognizer|
-------------------------------------
|        target_abis|  ['arm64-v8a']|
-------------------------------------
|        target_socs|    ['msm8916']|
-------------------------------------
| model_graph_format|           code|
-------------------------------------
|  model_data_format|           file|
-------------------------------------

* Generate mace engine creator source
Generate mace engine creator source done!

******************************************
          Convert densenet model
******************************************

WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Analysed target //mace/python/tools:converter (20 packages loaded).
INFO: Found 1 target...
Target //mace/python/tools:converter up-to-date:
  bazel-bin/mace/python/tools/converter
INFO: Elapsed time: 3.036s, Critical Path: 0.10s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

Transform model to one that can better run on device
Remove identity: out/bias/read(Identity)
Remove identity: out/kernel/read(Identity)
Remove identity: out/transpose(Identity)
Remove identity: batch_normalization_54/moving_variance/read(Identity)
Remove identity: batch_normalization_54/moving_mean/read(Identity)
Remove identity: batch_normalization_54/beta/read(Identity)
Remove identity: batch_normalization_54/gamma/read(Identity)
Remove identity: conv2d_54/bias/read(Identity)
Remove identity: conv2d_54/kernel/read(Identity)
Remove identity: batch_normalization_53/moving_variance/read(Identity)
Remove identity: batch_normalization_53/moving_mean/read(Identity)
Remove identity: batch_normalization_53/beta/read(Identity)
Remove identity: batch_normalization_53/gamma/read(Identity)
Remove identity: conv2d_53/bias/read(Identity)
Remove identity: conv2d_53/kernel/read(Identity)
Remove identity: batch_normalization_52/moving_variance/read(Identity)
Remove identity: batch_normalization_52/moving_mean/read(Identity)
Remove identity: batch_normalization_52/beta/read(Identity)
Remove identity: batch_normalization_52/gamma/read(Identity)
Remove identity: conv2d_52/bias/read(Identity)
Remove identity: conv2d_52/kernel/read(Identity)
Remove identity: batch_normalization_51/moving_variance/read(Identity)
Remove identity: batch_normalization_51/moving_mean/read(Identity)
Remove identity: batch_normalization_51/beta/read(Identity)
Remove identity: batch_normalization_51/gamma/read(Identity)
Remove identity: conv2d_51/bias/read(Identity)
Remove identity: conv2d_51/kernel/read(Identity)
Remove identity: batch_normalization_50/moving_variance/read(Identity)
Remove identity: batch_normalization_50/moving_mean/read(Identity)
Remove identity: batch_normalization_50/beta/read(Identity)
Remove identity: batch_normalization_50/gamma/read(Identity)
Remove identity: conv2d_50/bias/read(Identity)
Remove identity: conv2d_50/kernel/read(Identity)
Remove identity: batch_normalization_49/moving_variance/read(Identity)
Remove identity: batch_normalization_49/moving_mean/read(Identity)
Remove identity: batch_normalization_49/beta/read(Identity)
Remove identity: batch_normalization_49/gamma/read(Identity)
Remove identity: conv2d_49/bias/read(Identity)
Remove identity: conv2d_49/kernel/read(Identity)
Remove identity: batch_normalization_48/moving_variance/read(Identity)
Remove identity: batch_normalization_48/moving_mean/read(Identity)
Remove identity: batch_normalization_48/beta/read(Identity)
Remove identity: batch_normalization_48/gamma/read(Identity)
Remove identity: conv2d_48/bias/read(Identity)
Remove identity: conv2d_48/kernel/read(Identity)
Remove identity: batch_normalization_47/moving_variance/read(Identity)
Remove identity: batch_normalization_47/moving_mean/read(Identity)
Remove identity: batch_normalization_47/beta/read(Identity)
Remove identity: batch_normalization_47/gamma/read(Identity)
Remove identity: conv2d_47/bias/read(Identity)
Remove identity: conv2d_47/kernel/read(Identity)
Remove identity: batch_normalization_46/moving_variance/read(Identity)
Remove identity: batch_normalization_46/moving_mean/read(Identity)
Remove identity: batch_normalization_46/beta/read(Identity)
Remove identity: batch_normalization_46/gamma/read(Identity)
Remove identity: conv2d_46/kernel/read(Identity)
Remove identity: batch_normalization_45/moving_variance/read(Identity)
Remove identity: batch_normalization_45/moving_mean/read(Identity)
Remove identity: batch_normalization_45/beta/read(Identity)
Remove identity: batch_normalization_45/gamma/read(Identity)
Remove identity: conv2d_45/bias/read(Identity)
Remove identity: conv2d_45/kernel/read(Identity)
Remove identity: batch_normalization_44/moving_variance/read(Identity)
Remove identity: batch_normalization_44/moving_mean/read(Identity)
Remove identity: batch_normalization_44/beta/read(Identity)
Remove identity: batch_normalization_44/gamma/read(Identity)
Remove identity: conv2d_44/bias/read(Identity)
Remove identity: conv2d_44/kernel/read(Identity)
Remove identity: batch_normalization_43/moving_variance/read(Identity)
Remove identity: batch_normalization_43/moving_mean/read(Identity)
Remove identity: batch_normalization_43/beta/read(Identity)
Remove identity: batch_normalization_43/gamma/read(Identity)
Remove identity: conv2d_43/bias/read(Identity)
Remove identity: conv2d_43/kernel/read(Identity)
Remove identity: batch_normalization_42/moving_variance/read(Identity)
Remove identity: batch_normalization_42/moving_mean/read(Identity)
Remove identity: batch_normalization_42/beta/read(Identity)
Remove identity: batch_normalization_42/gamma/read(Identity)
Remove identity: conv2d_42/bias/read(Identity)
Remove identity: conv2d_42/kernel/read(Identity)
Remove identity: batch_normalization_41/moving_variance/read(Identity)
Remove identity: batch_normalization_41/moving_mean/read(Identity)
Remove identity: batch_normalization_41/beta/read(Identity)
Remove identity: batch_normalization_41/gamma/read(Identity)
Remove identity: conv2d_41/bias/read(Identity)
Remove identity: conv2d_41/kernel/read(Identity)
Remove identity: batch_normalization_40/moving_variance/read(Identity)
Remove identity: batch_normalization_40/moving_mean/read(Identity)
Remove identity: batch_normalization_40/beta/read(Identity)
Remove identity: batch_normalization_40/gamma/read(Identity)
Remove identity: conv2d_40/bias/read(Identity)
Remove identity: conv2d_40/kernel/read(Identity)
Remove identity: batch_normalization_39/moving_variance/read(Identity)
Remove identity: batch_normalization_39/moving_mean/read(Identity)
Remove identity: batch_normalization_39/beta/read(Identity)
Remove identity: batch_normalization_39/gamma/read(Identity)
Remove identity: conv2d_39/bias/read(Identity)
Remove identity: conv2d_39/kernel/read(Identity)
Remove identity: batch_normalization_38/moving_variance/read(Identity)
Remove identity: batch_normalization_38/moving_mean/read(Identity)
Remove identity: batch_normalization_38/beta/read(Identity)
Remove identity: batch_normalization_38/gamma/read(Identity)
Remove identity: conv2d_38/bias/read(Identity)
Remove identity: conv2d_38/kernel/read(Identity)
Remove identity: batch_normalization_37/moving_variance/read(Identity)
Remove identity: batch_normalization_37/moving_mean/read(Identity)
Remove identity: batch_normalization_37/beta/read(Identity)
Remove identity: batch_normalization_37/gamma/read(Identity)
Remove identity: conv2d_37/kernel/read(Identity)
Remove identity: batch_normalization_36/moving_variance/read(Identity)
Remove identity: batch_normalization_36/moving_mean/read(Identity)
Remove identity: batch_normalization_36/beta/read(Identity)
Remove identity: batch_normalization_36/gamma/read(Identity)
Remove identity: conv2d_36/bias/read(Identity)
Remove identity: conv2d_36/kernel/read(Identity)
Remove identity: batch_normalization_35/moving_variance/read(Identity)
Remove identity: batch_normalization_35/moving_mean/read(Identity)
Remove identity: batch_normalization_35/beta/read(Identity)
Remove identity: batch_normalization_35/gamma/read(Identity)
Remove identity: conv2d_35/bias/read(Identity)
Remove identity: conv2d_35/kernel/read(Identity)
Remove identity: batch_normalization_34/moving_variance/read(Identity)
Remove identity: batch_normalization_34/moving_mean/read(Identity)
Remove identity: batch_normalization_34/beta/read(Identity)
Remove identity: batch_normalization_34/gamma/read(Identity)
Remove identity: conv2d_34/bias/read(Identity)
Remove identity: conv2d_34/kernel/read(Identity)
Remove identity: batch_normalization_33/moving_variance/read(Identity)
Remove identity: batch_normalization_33/moving_mean/read(Identity)
Remove identity: batch_normalization_33/beta/read(Identity)
Remove identity: batch_normalization_33/gamma/read(Identity)
Remove identity: conv2d_33/bias/read(Identity)
Remove identity: conv2d_33/kernel/read(Identity)
Remove identity: batch_normalization_32/moving_variance/read(Identity)
Remove identity: batch_normalization_32/moving_mean/read(Identity)
Remove identity: batch_normalization_32/beta/read(Identity)
Remove identity: batch_normalization_32/gamma/read(Identity)
Remove identity: conv2d_32/bias/read(Identity)
Remove identity: conv2d_32/kernel/read(Identity)
Remove identity: batch_normalization_31/moving_variance/read(Identity)
Remove identity: batch_normalization_31/moving_mean/read(Identity)
Remove identity: batch_normalization_31/beta/read(Identity)
Remove identity: batch_normalization_31/gamma/read(Identity)
Remove identity: conv2d_31/bias/read(Identity)
Remove identity: conv2d_31/kernel/read(Identity)
Remove identity: batch_normalization_30/moving_variance/read(Identity)
Remove identity: batch_normalization_30/moving_mean/read(Identity)
Remove identity: batch_normalization_30/beta/read(Identity)
Remove identity: batch_normalization_30/gamma/read(Identity)
Remove identity: conv2d_30/bias/read(Identity)
Remove identity: conv2d_30/kernel/read(Identity)
Remove identity: batch_normalization_29/moving_variance/read(Identity)
Remove identity: batch_normalization_29/moving_mean/read(Identity)
Remove identity: batch_normalization_29/beta/read(Identity)
Remove identity: batch_normalization_29/gamma/read(Identity)
Remove identity: conv2d_29/bias/read(Identity)
Remove identity: conv2d_29/kernel/read(Identity)
Remove identity: batch_normalization_28/moving_variance/read(Identity)
Remove identity: batch_normalization_28/moving_mean/read(Identity)
Remove identity: batch_normalization_28/beta/read(Identity)
Remove identity: batch_normalization_28/gamma/read(Identity)
Remove identity: conv2d_28/kernel/read(Identity)
Remove identity: dropout_3/Identity(Identity)
Remove identity: dropout_4/Identity(Identity)
Traceback (most recent call last):
  File "/workspace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 305, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/workspace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 154, in main
    output_graph_def = mace_gpu_transformer.run()
  File "/workspace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 105, in run
    changed = transformer()
  File "/workspace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 1142, in transform_matmul_to_fc
    input_op = self._producer[op.input[0]]
KeyError: u'out/kernel:0'
Traceback (most recent call last):
  File "tools/converter.py", line 1595, in <module>
    flags.func(flags)
  File "tools/converter.py", line 785, in convert_func
    convert_model(configs)
  File "tools/converter.py", line 711, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/workspace/mace/tools/sh_commands.py", line 524, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1:

  RAN: /usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=/workspace/mace-models/myIDCardOCR/densenet4mace.pb --weight_file= --model_checksum=e27a4fdd2d4c9f3f04a05d640f4113531ed72d4b20b078d024663b29c280ef5d --weight_checksum= --input_node=the_input --output_node=out/sub --runtime=cpu+gpu --template=mace/python/tools --model_tag=densenet --input_shape=1,32,512,1 --dsp_mode=0 --embed_model_data=False --winograd=0 --obfuscate=0 --output_dir=mace/codegen/models/densenet --model_graph_format=code --data_type=fp16_fp32 --graph_optimize_options=

  STDOUT:


  STDERR:
```

### Additional context
No modification added.

**Comment by liyinhgqw** [comment]
Please use TF's transform graph tool to optimize your model. Refer to mace document / basic usage.

**Comment by YanBC** [comment]
I did. I was using the following commands to transform my graph file:
```bash
cd ../tensorflow && \
bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
--in_graph=/path/to/orginal/pb_file \
--out_graph=/path/to/transformed_pb_file \
--inputs='the_input' \
--outputs='out/sub' \
--transforms='
strip_unused_nodes(type=float, shape="1,32,512,3")
remove_nodes(op=Identity, op=CheckNumerics)
fold_constants(ignore_errors=true)
flatten_atrous_conv
fold_batch_norms
fold_old_batch_norms
remove_control_dependencies
strip_unused_nodes
sort_by_execution_order
'
```
But then I compared the outputs of orginal_pb_file and transformed_pb_file with the identical input, and they were not the same. That's why I didn't remove any Identity ops. FYI, this is how I compare the outputs:
```python
import numpy as np
import tensorflow as tf
import argparse

def run(modelPath):
    g = tf.GraphDef()
    with open(modelPath, 'rb') as f:
        g.ParseFromString(f.read())
    
    graph = tf.Graph()
    with graph.as_default():
        tf.import_graph_def(g, name='')

        np.random.seed(0)
        myIn = np.random.random([1,32,512,1])

        sess = tf.Session()
        inputTensor = sess.graph.get_tensor_by_name('the_input:0')
        outputTensor = sess.graph.get_tensor_by_name('out/sub:0')
        myOut = sess.run(outputTensor, feed_dict={inputTensor: myIn})

        sess.close()
        return myOut

if __name__=='__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('file_1')
    parser.add_argument('file_2')
    args = parser.parse_args()

    modelPath1 = args.file_1
    modelPath2 = args.file_2

    # modelPath1 = 'about/densenet.pb'
    # modelPath2 = 'about/densenet_with_myRep.pb'
    out1 = run(modelPath1)
    out2 = run(modelPath2)

    if np.sum(out1!=out2) != 0:
        print('These two graphs are NOT the same')
    else:
        print('These two graphs are the SAME')
```
Leave the problem of inconsistent output aside, I transform the graph with the transfrom_graph tool (using the same command as mentioned above) and the mace problem still exists:
```bash
root@DL:/workspace/mace# python tools/converter.py convert --config=../mace-models/myIDCardOCR/densenet.yml
-------------------------------------
         Common Configuration
-------------------------------------
|        key        |     value     |
=====================================
|       library_name| ocr_recognizer|
-------------------------------------
|        target_abis|  ['arm64-v8a']|
-------------------------------------
|        target_socs|    ['msm8916']|
-------------------------------------
| model_graph_format|           code|
-------------------------------------
|  model_data_format|           file|
-------------------------------------

* Generate mace engine creator source
Generate mace engine creator source done!

******************************************
          Convert densenet model
******************************************

WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Analysed target //mace/python/tools:converter (20 packages loaded).
INFO: Found 1 target...
Target //mace/python/tools:converter up-to-date:
  bazel-bin/mace/python/tools/converter
INFO: Elapsed time: 8.877s, Critical Path: 0.50s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

Transform model to one that can better run on device
Remove identity: out/transpose(Identity)
Traceback (most recent call last):
  File "/workspace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 305, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/workspace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 154, in main
    output_graph_def = mace_gpu_transformer.run()
  File "/workspace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 105, in run
    changed = transformer()
  File "/workspace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 1142, in transform_matmul_to_fc
    input_op = self._producer[op.input[0]]
KeyError: u'out/kernel:0'
Traceback (most recent call last):
  File "tools/converter.py", line 1595, in <module>
    flags.func(flags)
  File "tools/converter.py", line 785, in convert_func
    convert_model(configs)
  File "tools/converter.py", line 711, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/workspace/mace/tools/sh_commands.py", line 524, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1:

  RAN: /usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=/workspace/mace-models/myIDCardOCR/densenet4mace_transformed.pb --weight_file= --model_checksum=8d825ec20892735370d44db9a69134e1809529dcc7071eec82aed44bf0ddcdba --weight_checksum= --input_node=the_input --output_node=out/sub --runtime=cpu+gpu --template=mace/python/tools --model_tag=densenet --input_shape=1,32,512,1 --dsp_mode=0 --embed_model_data=False --winograd=0 --obfuscate=0 --output_dir=mace/codegen/models/densenet --model_graph_format=code --data_type=fp16_fp32 --graph_optimize_options=

  STDOUT:


  STDERR:
```
And if you looking into the graph, there ain't any identiy ops in 'out/transpose'

Link to the model file:
[https://github.com/YanBC/4mace/blob/master/densenet4mace_transformed.pb](url)

**Comment by liyinhgqw** [comment]
I looked at your model, the 'the_input' node has only 1 channel which is weird as you specify 3 channels in mace yaml

**Comment by liyinhgqw** [comment]
Hi, 
I checked your model. Currently we do not support transpose yet. The problem is at `permute/transpose`.

You can split your model into two for workaround (before and after `transpose`).

The first part should be:
library_name: abc
target_abis: [armeabi-v7a]
model_graph_format: file
model_data_format: file
models:
  abc:
    platform: tensorflow
    model_file_path: densenet4mace_transformed.pb
    model_sha256_checksum: 8d825ec20892735370d44db9a69134e1809529dcc7071eec82aed44bf0ddcdba
    subgraphs:
      - input_tensors:
          - the_input
        input_shapes:
          - 1,32,512,1
        output_tensors:
          - activation_54/Relu
        output_shapes:
          - 1,4,64,192
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0

**Comment by nolanliou** [comment]
No response for 21 days, close it temporarily, feel free to reopen it if necessary.

**Comment by smilexin** [comment]
I happened with the same error, can this issue have answer? "Currently we do not support transpose yet" what does this mean? @liyinhgqw,  the "transpose" is mean the transpose operator?  I find the key TransformerRule.TRANSPOSE_FILTERS, does this is the transpose related?
