### ISSUE TITLE
Mace master converter error

### ISSUE THREAD

**Issue by dimitryn** [XiaoMi/mace#286]
Hi , I have exception on  tensorflow model conversion in master.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Uubuntu 16
- **NDK version(e.g., 15c)**:
17
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
Master
- **Python version(2.7)**: 
2.7
- **Bazel version (e.g., 0.13.0)**:
15

### Model deploy file (*.yml)
```yaml
......
```

```
  from ._trlib import TRLIBQuadraticSubproblem
/home/dnozik/.local/lib/python2.7/site-packages/scipy/optimize/_numdiff.py:8: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._group_columns import group_dense, group_sparse
/home/dnozik/.local/lib/python2.7/site-packages/scipy/interpolate/_bsplines.py:9: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _bspl
/home/dnozik/.local/lib/python2.7/site-packages/scipy/spatial/__init__.py:94: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .ckdtree import *
/home/dnozik/.local/lib/python2.7/site-packages/scipy/spatial/__init__.py:95: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .qhull import *
/home/dnozik/.local/lib/python2.7/site-packages/scipy/spatial/_spherical_voronoi.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _voronoi
/home/dnozik/.local/lib/python2.7/site-packages/scipy/spatial/distance.py:121: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _hausdorff
/home/dnozik/.local/lib/python2.7/site-packages/scipy/ndimage/measurements.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _ni_label
Run transform_graph: ['strip_unused_nodes', 'remove_nodes(op=Identity, op=CheckNumerics)', 'fold_constants(ignore_errors=true)', 'fold_batch_norms', 'fold_old_batch_norms', 'remove_control_dependencies', 'strip_unused_nodes', 'sort_by_execution_order']
Traceback (most recent call last):
  File "/home/dnozik/Code/mace-master/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 361, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/dnozik/Code/mace-master/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 185, in main
    option, FLAGS.model_file)
  File "/home/dnozik/Code/mace-master/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 278, in __init__
    option.device])
  File "/home/dnozik/.local/lib/python2.7/site-packages/tensorflow/tools/graph_transforms/__init__.py", line 51, in TransformGraph
    transforms_string, status)
  File "/home/dnozik/.local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Transform 'remove_control_dependencies' not recognized.
Traceback (most recent call last):
  File "tools/converter.py", line 1241, in <module>
    flags.func(flags)
  File "tools/converter.py", line 760, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 690, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/dnozik/Code/mace-master/tools/sh_commands.py", line 518, in gen_model_code
    _fg=True)
  File "/home/dnozik/.local/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

Thanks.

**Comment by liyinhgqw** [comment]
You can fix it by upgrading tensorflow to 1.8.0+.

**Comment by liyinhgqw** [comment]
Hi dimitryn,

You can update code to master, it should be fixed.

**Comment by dimitryn** [comment]
thanks

**Comment by dimitryn** [comment]
@liyinhgqw I took master and converter produce same error

**Comment by dimitryn** [comment]
@TonyMou  tensorflow pb file created with 1.12 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by TonyMou** [comment]
@dimitryn which version of tensorflow are you using when running convert.py? Not the trainning one

**Comment by dimitryn** [comment]
thanks :)

**Comment by dimitryn** [comment]
@TonyMou Now I have 
 File "/home/dnozik/.local/lib/python2.7/site-packages/tensorflow/python/keras/backend/__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.backend import abs
ImportError: cannot import name abs


Beside protobuf , tensorflow  what else should I update  ?

**Comment by TonyMou** [comment]
Check the documents here: https://mace.readthedocs.io/en/latest/installation/env_requirement.html

**Comment by dimitryn** [comment]
Hi ,
After resolving all issue with environment Mace master still crash on conversion with one of our pb  files.

```
***************************************************
          Convert recognition_model model          
***************************************************

INFO: Analysed target //mace/python/tools:converter (0 packages loaded).
INFO: Found 1 target...
Target //mace/python/tools:converter up-to-date:
  bazel-bin/mace/python/tools/converter
INFO: Elapsed time: 0.283s, Critical Path: 0.02s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

Transform model to one that can better run on device
Run transform_graph: ['strip_unused_nodes', 'remove_nodes(op=Identity, op=CheckNumerics)', 'fold_constants(ignore_errors=true)', 'fold_batch_norms', 'fold_old_batch_norms', 'remove_control_dependencies', 'strip_unused_nodes', 'sort_by_execution_order']
Remove identity: output_features(Identity)
convert reshape and matmul to fc
Traceback (most recent call last):
  File "/home/dima/Code/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 355, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/dima/Code/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 196, in main
    output_graph_def, quantize_activation_info = mace_transformer.run()
  File "/home/dima/Code/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 124, in run
    changed = transformer()
  File "/home/dima/Code/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 1266, in transform_matmul_to_fc
    consumers = self._consumers[op.output[0]]
KeyError: u'output_features'
Traceback (most recent call last):
  File "tools/converter.py", line 1242, in <module>
    flags.func(flags)
  File "tools/converter.py", line 761, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 691, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/dima/Code/mace/tools/sh_commands.py", line 518, in gen_model_code
    _fg=True)
  File "/home/dima/.local/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=/home/dima/Code/pb_files/sphere28_clean.pb --weight_file= --model_checksum=65842cfed53fe0bc308852293698d77d4d46345b543fcd065bb8a86975956da4 --weight_checksum= --input_node=input --input_data_formats=NHWC --output_node=output_features --output_data_formats=NHWC --check_node= --runtime=cpu --template=mace/python/tools --model_tag=recognition_model --input_shape=1,128,128,1 --input_range= --output_shape=1,512 --check_shape= --dsp_mode=0 --embed_model_data=True --winograd=0 --quantize=0 --quantize_range_file= --change_concat_ranges=0 --obfuscate=0 --output_dir=mace/codegen/models/recognition_model --model_graph_format=code --data_type=fp32_fp32 --graph_optimize_options= --cl_mem_type=image

  STDOUT:


  STDERR:


```


Link to yml and pb file:
 https://drive.google.com/open?id=1ScJDXUuEA3-MYUJzE52OIjXAQsloveRQ

Thanks.

**Comment by TonyMou** [comment]
we'll look into it.

**Comment by dimitryn** [comment]
@gururaghavendraprasad  1.15.1

**Comment by TonyMou** [comment]
@dimitryn did you resolved your problem?

**Comment by TonyMou** [comment]
@dimitryn I've tested your model,  the result is correct. If you have any problem about it, feel free to reopen this issue.
