### ISSUE TITLE
请问怎么指定本地的交叉编译器（arm-linux）

### ISSUE THREAD

**Issue by leeburt** [XiaoMi/mace#294]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by nolanliou** [comment]
Please refer to the document : https://mace.readthedocs.io/en/latest/user_guide/advanced_usage.html#run-you-model-on-the-embedded-device-arm-linux

**Comment by leeburt** [comment]
**下载的官方的docker，编译没有问题。**

**执行了** python tools/converter.py run --config=../model/caffe/MobileNetSSD_deploy_new.yml --device_yml=../model/caffe/devices.yml 

**以下是报错信息**
```
Traceback (most recent call last):
  File "tools/converter.py", line 1242, in <module>
    flags.func(flags)
  File "tools/converter.py", line 935, in run_mace
    device_list = DeviceManager.list_devices(flags.device_yml)
  File "/home/work/mace/tools/device.py", line 996, in list_devices
    devices_list.extend(cls.list_ssh_device(yml))
  File "/home/work/mace/tools/device.py", line 978, in list_ssh_device
    devices = devices['devices']
KeyError: 'devices'
root@lee-virtual-machine:/home/work/mace# python tools/converter.py run --config=../model/caffe/MobileNetSSD_deploy_new.yml --device_yml=../model/caffe/devices.yml 
Traceback (most recent call last):
  File "tools/converter.py", line 1242, in <module>
    flags.func(flags)
  File "tools/converter.py", line 935, in run_mace
    device_list = DeviceManager.list_devices(flags.device_yml)
  File "/home/work/mace/tools/device.py", line 996, in list_devices
    devices_list.extend(cls.list_ssh_device(yml))
  File "/home/work/mace/tools/device.py", line 978, in list_ssh_device
    devices = devices['devices']
KeyError: 'devices'
```
以下是设备信息的设置
```
#devices.yml：#
linaro-developer:
    target_abis: [armv7l]
    target_socs: MSM8x74AA
    models: linaro-developer 3.4.0-eagle8074
    address: 192.168.1.1
    username: root
```

**Comment by leeburt** [comment]
> **下载的官方的docker，编译没有问题。**
> 
> **执行了** python tools/converter.py run --config=../model/caffe/MobileNetSSD_deploy_new.yml --device_yml=../model/caffe/devices.yml
> 
> **以下是报错信息**
> 
> ```
> Traceback (most recent call last):
>   File "tools/converter.py", line 1242, in <module>
>     flags.func(flags)
>   File "tools/converter.py", line 935, in run_mace
>     device_list = DeviceManager.list_devices(flags.device_yml)
>   File "/home/work/mace/tools/device.py", line 996, in list_devices
>     devices_list.extend(cls.list_ssh_device(yml))
>   File "/home/work/mace/tools/device.py", line 978, in list_ssh_device
>     devices = devices['devices']
> KeyError: 'devices'
> root@lee-virtual-machine:/home/work/mace# python tools/converter.py run --config=../model/caffe/MobileNetSSD_deploy_new.yml --device_yml=../model/caffe/devices.yml 
> Traceback (most recent call last):
>   File "tools/converter.py", line 1242, in <module>
>     flags.func(flags)
>   File "tools/converter.py", line 935, in run_mace
>     device_list = DeviceManager.list_devices(flags.device_yml)
>   File "/home/work/mace/tools/device.py", line 996, in list_devices
>     devices_list.extend(cls.list_ssh_device(yml))
>   File "/home/work/mace/tools/device.py", line 978, in list_ssh_device
>     devices = devices['devices']
> KeyError: 'devices'
> ```
> 以下是设备信息的设置
> 
> ```
> #devices.yml：#
> linaro-developer:
>     target_abis: [armv7l]
>     target_socs: MSM8x74AA
>     models: linaro-developer 3.4.0-eagle8074
>     address: 192.168.1.1
>     username: root
> ```
将devices.yml文件改为就可解决。
```
devices:  
  linaro-developer :
    target_abis: [armeabi-v7a]
    target_socs: MSM8x74AA
    models: linaro-developer 3.4.0-eagle8074
    address: 192.168.1.1
    username: root
```

**Comment by leeburt** [comment]
运行时依然报错如下：
root@lee-virtual-machine:/home/work/mace# python tools/converter.py run --config=../model/caffe/MobileNetSSD_deploy_new.yml --device_yml=/home/work/model/caffe/devices.yml
```
* Build //mace/tools/validation:mace_run_static with ABI armeabi-v7a
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Analysed target //mace/tools/validation:mace_run_static (23 packages loaded).
INFO: Found 1 target...
Target //mace/tools/validation:mace_run_static up-to-date:
  bazel-bin/mace/tools/validation/mace_run_static
INFO: Elapsed time: 158.986s, Critical Path: 15.49s
INFO: 125 processes: 125 local.
INFO: Build completed successfully, 128 total actions
Build done!

*****************************************************************************
          Run model MobileNetSSD on linaro-developer3.4.0-eagle8074          
*****************************************************************************

Generate input file:  builds/MobileNetSSD/_tmp/MobileNetSSD/a27875922bf418df62520e7ebd71a97e/linaro-developer3.4.0-eagle8074_MSM8x74AA/armeabi-v7a/model_input_data
Generate input file done.
* Run 'MobileNetSSD' with round=1, restart_round=1, tuning=False, out_of_range_check=False, omp_num_threads=(-1,), cpu_affinity_policy=(1,), gpu_perf_hint=(3,), gpu_priority_hint=(3,)
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Push builds/MobileNetSSD/_tmp/MobileNetSSD/a27875922bf418df62520e7ebd71a97e/linaro-developer3.4.0-eagle8074_MSM8x74AA/armeabi-v7a/model_input_data to /tmp/data/mace_run
Push builds/MobileNetSSD/model/MobileNetSSD.data to /tmp/data/mace_run
Push third_party/nnlib/libhexagon_controller.so to /tmp/data/mace_run
Push builds/MobileNetSSD/model/MobileNetSSD.pb to /tmp/data/mace_run/MobileNetSSD.pb
Push builds/MobileNetSSD/_tmp/armeabi-v7a/mace_run_static to /tmp/data/mace_run
Push /tmp/cmd_file-MobileNetSSD-1545893659.34 to /tmp/data/mace_run/cmd_file-MobileNetSSD-1545893659.34
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/tmp/data/mace_run/cmd_file-MobileNetSSD-1545893659.34: 1: /tmp/data/mace_run/cmd_file-MobileNetSSD-1545893659.34: /tmp/data/mace_run/mace_run_static: not found
Traceback (most recent call last):
  File "tools/converter.py", line 1242, in <module>
    flags.func(flags)
  File "tools/converter.py", line 961, in run_mace
    device.run_specify_abi(flags, configs, target_abi)
  File "/home/work/mace/tools/device.py", line 555, in run_specify_abi
    quantize_stat=flags.quantize_stat,
  File "/home/work/mace/tools/device.py", line 326, in tuning_run
    _err_to_out=True)
  File "/home/work/mace/tools/device.py", line 72, in exec_command
    command, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 774, in __init__
    self.wait()
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_127: 

  RAN: /usr/bin/ssh root@192.168.1.1 sh /tmp/data/mace_run/cmd_file-MobileNetSSD-1545893659.34

  STDOUT:


  STDERR:
```

**Comment by leeburt** [comment]
@nolanliou 运行时报错如下：
root@lee-virtual-machine:/home/work/mace# python tools/converter.py run --config=../model/caffe/MobileNetSSD_deploy_new.yml --device_yml=/home/work/model/caffe/devices.yml
```
* Build //mace/tools/validation:mace_run_static with ABI armeabi-v7a
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Analysed target //mace/tools/validation:mace_run_static (23 packages loaded).
INFO: Found 1 target...
Target //mace/tools/validation:mace_run_static up-to-date:
  bazel-bin/mace/tools/validation/mace_run_static
INFO: Elapsed time: 158.986s, Critical Path: 15.49s
INFO: 125 processes: 125 local.
INFO: Build completed successfully, 128 total actions
Build done!

*****************************************************************************
          Run model MobileNetSSD on linaro-developer3.4.0-eagle8074          
*****************************************************************************

Generate input file:  builds/MobileNetSSD/_tmp/MobileNetSSD/a27875922bf418df62520e7ebd71a97e/linaro-developer3.4.0-eagle8074_MSM8x74AA/armeabi-v7a/model_input_data
Generate input file done.
* Run 'MobileNetSSD' with round=1, restart_round=1, tuning=False, out_of_range_check=False, omp_num_threads=(-1,), cpu_affinity_policy=(1,), gpu_perf_hint=(3,), gpu_priority_hint=(3,)
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Push builds/MobileNetSSD/_tmp/MobileNetSSD/a27875922bf418df62520e7ebd71a97e/linaro-developer3.4.0-eagle8074_MSM8x74AA/armeabi-v7a/model_input_data to /tmp/data/mace_run
Push builds/MobileNetSSD/model/MobileNetSSD.data to /tmp/data/mace_run
Push third_party/nnlib/libhexagon_controller.so to /tmp/data/mace_run
Push builds/MobileNetSSD/model/MobileNetSSD.pb to /tmp/data/mace_run/MobileNetSSD.pb
Push builds/MobileNetSSD/_tmp/armeabi-v7a/mace_run_static to /tmp/data/mace_run
Push /tmp/cmd_file-MobileNetSSD-1545893659.34 to /tmp/data/mace_run/cmd_file-MobileNetSSD-1545893659.34
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/tmp/data/mace_run/cmd_file-MobileNetSSD-1545893659.34: 1: /tmp/data/mace_run/cmd_file-MobileNetSSD-1545893659.34: /tmp/data/mace_run/mace_run_static: not found
Traceback (most recent call last):
  File "tools/converter.py", line 1242, in <module>
    flags.func(flags)
  File "tools/converter.py", line 961, in run_mace
    device.run_specify_abi(flags, configs, target_abi)
  File "/home/work/mace/tools/device.py", line 555, in run_specify_abi
    quantize_stat=flags.quantize_stat,
  File "/home/work/mace/tools/device.py", line 326, in tuning_run
    _err_to_out=True)
  File "/home/work/mace/tools/device.py", line 72, in exec_command
    command, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 774, in __init__
    self.wait()
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_127: 

  RAN: /usr/bin/ssh root@192.168.1.1 sh /tmp/data/mace_run/cmd_file-MobileNetSSD-1545893659.34

  STDOUT:


  STDERR:
```

**Comment by liyinhgqw** [comment]
你的开发版不是 arm_linux 么，指定 armeabi-v7a 不行，还是对上板子的 abi

**Comment by TonyMou** [comment]
ssh能正常连接arm板子吗？

**Comment by liyinhgqw** [comment]
ssh 到设备上，看下是否真是：
` /tmp/data/mace_run/mace_run_static: not found`

**Comment by leeburt** [comment]
> ssh能正常连接arm板子吗？
我执行了。结果如下：
**root@123:/home/work/mace# ssh root@192.168.1.1**
```
Welcome to Linaro 14.04 (GNU/Linux 3.4.0-eagle8074 armv7l)

 * Documentation:  https://wiki.linaro.org/
Last login: Thu Jan  1 00:52:07 1970 from 192.168.1.47
```

**Comment by leeburt** [comment]
> ssh 到设备上，看下是否真是：
> ` /tmp/data/mace_run/mace_run_static: not found`

这是/tmp/data/mace_run/路径下的文件

```
-rw-r--r-- 1 root root 23133884 Jan  1 01:01 MobileNetSSD.data
-rw-r--r-- 1 root root    20188 Jan  1 01:01 MobileNetSSD.pb
-rw-r--r-- 1 root root     1075 Jan  1 01:02 cmd_file-MobileNetSSD-1545913009.8
drwxr-xr-x 2 root root     4096 Jan  1 00:59 interior/
-rwxr-xr-x 1 root root    15980 Jan  1 01:01 libhexagon_controller.so*
-r-xr-xr-x 1 root root  1438552 Jan  1 01:02 mace_run_static*
-rw-r--r-- 1 root root  1080000 Jan  1 00:59 model_input_data
```

**Comment by leeburt** [comment]
> 你的开发版不是 arm_linux 么，指定 armeabi-v7a 不行，还是对上板子的 abi

@liyinhgqw 确实是这个问题，利用dpkg --print-architecture 确定了类型后，device.yml和model.yml修改后，这个问题解决。

但是我发现我的abi的版本比较低，是否可以更换低版本的abi，如4.8.2

**Comment by nolanliou** [comment]
@leeburt 有什么进展吗？

**Comment by leeburt** [comment]
我这边不允许换交叉编译器版本。4.8.2版本目前还没有解决这个问题，没有思路解决。 @nolanliou

**Comment by leeburt** [comment]
我把错误中的命令单独拿出来执行报错一样，但是注释`#    PATH=/root/.cache/bazel/_bazel_root/a53bdf223f760a8c01f516dc4d940d81/execroot/mace:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/sdk/tools:/opt/sdk/platform-tools:/opt/android-ndk-r15`后这条命令不报错了。但是我不知道为什么。

```
cd /root/.cache/bazel/_bazel_root/a53bdf223f760a8c01f516dc4d940d81/execroot/mace && \
exec env - \
#PATH=/root/.cache/bazel/_bazel_root/a53bdf223f760a8c01f516dc4d940d81/execroot/mace:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/sdk/tools:/opt/sdk/platform-tools:/opt/android-ndk-r15c \
PWD=/proc/self/cwd \
tools/arm_compiler/linaro_linux_gcc/arm-linux-gnueabihf-gcc '--sysroot=external/gcc_linaro_4_8_2_arm_linux_gnueabihf/arm-linux-gnueabihf/libc' -U_FORTIFY_SOURCE -fstack-protector -fPIE '-fdiagnostics-color=always' -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -isystem external/gcc_linaro_4_8_2_arm_linux_gnueabihf/arm-linux-gnueabihf/include/c++/4.8.2/arm-linux-gnueabihf -isystem external/gcc_linaro_4_8_2_arm_linux_gnueabihf/arm-linux-gnueabihf/include/c++/4.8.2 -isystem external/gcc_linaro_4_8_2_arm_linux_gnueabihf/include/c++/4.8.2/arm-linux-gnueabihf -isystem external/gcc_linaro_4_8_2_arm_linux_gnueabihf/include/c++/4.8.2 -MD -MF bazel-out/armeabi-v7a-opt/bin/external/com_google_protobuf/_objs/protobuf_lite/status.pic.d '-frandom-seed=bazel-out/armeabi-v7a-opt/bin/external/com_google_protobuf/_objs/protobuf_lite/status.pic.o' -fPIC -iquote external/com_google_protobuf -iquote bazel-out/armeabi-v7a-opt/genfiles/external/com_google_protobuf -iquote bazel-out/armeabi-v7a-opt/bin/external/com_google_protobuf -iquote external/bazel_tools -iquote bazel-out/armeabi-v7a-opt/genfiles/external/bazel_tools -iquote bazel-out/armeabi-v7a-opt/bin/external/bazel_tools -isystem external/com_google_protobuf/src -isystem bazel-out/armeabi-v7a-opt/genfiles/external/com_google_protobuf/src -isystem bazel-out/armeabi-v7a-opt/bin/external/com_google_protobuf/src '-std=c++11' -fPIC -D_GLIBCXX_USE_C99_MATH_TR1 -DMACE_OBFUSCATE_LITERALS -DGEMMLOWP_USE_OPENMP '-std=c++11' -fPIC -D_GLIBCXX_USE_C99_MATH_TR1 -DMACE_OBFUSCATE_LITERALS -DGEMMLOWP_USE_OPENMP '-mfloat-abi=hard' '-mfpu=neon' -Wno-ignored-attributes -Wno-unused-function -Wno-sequence-point -Wno-implicit-fallthrough '-mfloat-abi=hard' '-mfpu=neon' -Wno-ignored-attributes -Wno-unused-function -Wno-sequence-point -Wno-implicit-fallthrough -O3 -ffunction-sections -fdata-sections -O3 -ffunction-sections -fdata-sections -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function -Wno-writable-strings -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_protobuf/src/google/protobuf/stubs/status.cc -o bazel-out/armeabi-v7a-opt/bin/external/com_google_protobuf/_objs/protobuf_lite/status.pic.o
```

**Comment by llhe** [comment]
@leeburt 这个问题已解决。4.8.2可以编译，稍后会发一个patch。

**Comment by llhe** [comment]
@leeburt You can use this patch for a quick workaround or wait for the official fix.
[linaro-gcc4.8.2.patch.tar.gz](https://github.com/XiaoMi/mace/files/2739303/linaro-gcc4.8.2.patch.tar.gz)

**Comment by leeburt** [comment]
@llhe 非常感谢~我先试试。

**Comment by leeburt** [comment]
更换成4.9.4版本的linaro_gcc4.9.4后，执行`python tools/converter.py run --config=../model/caffe/MobileNetSSD_deploy_new.yml --device_yml=/home/work/model/caffe/devices.yml`同样报错，对比之前7.3.1版本的错误少了一个```/tmp/data/mace_run/mace_run_static: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/data/mace_run/mace_run_static）``，具体信息如下：`。

```
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Push builds/MobileNetSSD/_tmp/MobileNetSSD/a27875922bf418df62520e7ebd71a97e/linaro-developer3.4.0-eagle8074_MSM8x74AA/armhf/model_input_data to /tmp/data/mace_run
Push builds/MobileNetSSD/model/MobileNetSSD.data to /tmp/data/mace_run
Push third_party/nnlib/libhexagon_controller.so to /tmp/data/mace_run
Push builds/MobileNetSSD/model/MobileNetSSD.pb to /tmp/data/mace_run/MobileNetSSD.pb
Push builds/MobileNetSSD/_tmp/armhf/mace_run_static to /tmp/data/mace_run
Push /tmp/cmd_file-MobileNetSSD-1547084237.02 to /tmp/data/mace_run/cmd_file-MobileNetSSD-1547084237.02
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/tmp/data/mace_run/mace_run_static: /usr/lib/arm-linux-gnueabihf/libgomp.so.1: version `GOMP_4.0' not found (required by /tmp/data/mace_run/mace_run_static)
/tmp/data/mace_run/mace_run_static: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/data/mace_run/mace_run_static)
/tmp/data/mace_run/mace_run_static: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /tmp/data/mace_run/mace_run_static)
Traceback (most recent call last):
  File "tools/converter.py", line 1242, in <module>
    flags.func(flags)
  File "tools/converter.py", line 961, in run_mace
    device.run_specify_abi(flags, configs, target_abi)
  File "/home/work/mace-0.10.0/tools/device.py", line 563, in run_specify_abi
    output_dir=flags.output_dir,
  File "/home/work/mace-0.10.0/tools/device.py", line 332, in tuning_run
    _err_to_out=True)
  File "/home/work/mace-0.10.0/tools/device.py", line 72, in exec_command
    command, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 774, in __init__
    self.wait()
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/ssh root@192.168.1.1 sh /tmp/data/mace_run/cmd_file-MobileNetSSD-1547084237.02
```

**Comment by llhe** [comment]
提供一下开发板上面的信息？
```sh
strings /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 | grep GLIBCXX
```

**Comment by leeburt** [comment]
> 提供一下开发板上面的信息？
> 
> ```shell
> strings /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 | grep GLIBCXX
> ```

```
root@linaro-developer:~# strings /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Comment by llhe** [comment]
看起来就是版本不一致，两个解决方法，一个是降低编译器版本跟系统libstdc++版本兼容，另一个是[运行时使用编译时用的那个版本的库](https://itbilu.com/linux/management/NymXRUieg.html)

**Comment by leeburt** [comment]
> 看起来就是版本不一致，两个解决方法，一个是降低编译器版本跟系统libstdc++版本兼容，另一个是[运行时使用编译时用的那个版本的库](https://itbilu.com/linux/management/NymXRUieg.html)

通过上面的方法解决了问题，同样的用上面的方法解决了类似`GOMP_4.0 not found`的问题。
`
