### ISSUE TITLE
InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'input_1' with dtype float and shape [1,256,256,3]

### ISSUE THREAD

**Issue by 395062753** [XiaoMi/mace#330]
yml
library_name: fpn-seg-net
target_abis: [armeabi-v7a, arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  fpn-seg-net:
    platform: tensorflow
    model_file_path: pathtomodel/model.pb
    model_sha256_checksum: c5b7565656bbcd216c472fe7bd18329fb1c0479b80d2f36dc1525b9c123e5eec
    subgraphs:
      - input_tensors: input_1
        output_tensors: up_sampling2d_7/ResizeBilinear
        input_shapes: 1,256,256,3
        output_shapes: 1,256,256,2
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
### Describe the problem
INFO: Analysed target //mace/python/tools:converter (0 packages loaded).
INFO: Found 1 target...
Target //mace/python/tools:converter up-to-date:
  bazel-bin/mace/python/tools/converter
INFO: Elapsed time: 0.172s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

Transform model to one that can better run on device
Traceback (most recent call last):
  File "/home/gyd/gyd/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 381, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/gyd/gyd/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 180, in main
    output_graph_def = converter.run()
  File "/home/gyd/gyd/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 246, in run
    self.convert_ops(session)
  File "/home/gyd/gyd/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 297, in convert_ops
    self._op_converters[tf_op.type](tf_op)
  File "/home/gyd/gyd/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 605, in convert_resize_bilinear
    size_value = tf_op.inputs[1].eval().astype(np.int32)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 656, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 4901, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_1' with dtype float and shape [1,256,256,3]
	 [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[1,256,256,3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op u'input_1', defined at:
  File "/home/gyd/gyd/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 381, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/gyd/gyd/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 169, in main
    option, FLAGS.model_file)
  File "/home/gyd/gyd/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 236, in __init__
    tf.import_graph_def(tf_graph_def, name='')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 553, in import_graph_def
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'input_1' with dtype float and shape [1,256,256,3]
	 [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[1,256,256,3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
model path
my model.pb is here

https://pan.baidu.com/s/1wW2JXmws5uJJliIjSEtZLA

**Comment by TonyMou** [comment]
which version of mace are you using?

**Comment by 395062753** [comment]
> which version of mace are you using?
> I have tested your model, it works all right.

Thanks for your test. Maybe the version of mine is too old. I will try to update later. Can you send  the build files (including .a and .h files or .so and .h files) to my mailbox, 13811407414@163.com. Thanks very much.
In addition, can you tell me the version of yours?

**Comment by 395062753** [comment]
Solved! 
Update to the latest version of mace
