### ISSUE TITLE
convert onnx model failed

### ISSUE THREAD

**Issue by michaelwangat** [XiaoMi/mace#365]
error:local variable 'perm' referenced before assignment

Traceback (most recent call last):
  File "/home/michaelwang/work/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 355, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/michaelwang/work/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 193, in main
    output_graph_def = converter.run()
  File "/home/michaelwang/work/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/onnx_converter.py", line 389, in run
    self.convert_ops(graph_def)
  File "/home/michaelwang/work/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/onnx_converter.py", line 444, in convert_ops
    self._op_converters[node.op_type](node)
  File "/home/michaelwang/work/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/onnx_converter.py", line 847, in convert_transpose
    if np.array_equal(perm, ordered_perm):
UnboundLocalError: local variable 'perm' referenced before assignment
Traceback (most recent call last):
  File "tools/converter.py", line 1242, in <module>
    flags.func(flags)
  File "tools/converter.py", line 761, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 691, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/michaelwang/work/mace/tools/sh_commands.py", line 518, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1:

**Comment by TonyMou** [comment]
This issue is already fixed, try out the latest code from master branch.
