### ISSUE TITLE
convert caffe model failed, sh.SignalException_SIGKILL

### ISSUE THREAD

**Issue by FeiZhu** [XiaoMi/mace#384]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
MacOS Mojave 10.14.3 (Mace built with docker image, model conversion also performed in container)
- **NDK version(e.g., 15c)**:
15c
- **GCC version(if compiling for host, e.g., 5.4.0)**:
5.4.0
- **MACE version (Use the command: git describe --long --tags)**:
v0.10.0-0-g22e40d6
- **Python version(2.7)**: 
2.7
- **Bazel version (e.g., 0.13.0)**:
0.16.0
### Model deploy file (*.yml)
```yaml
# The name of library
library_name: fcn_caffe_mace
target_abis: [armeabi-v7a]
model_graph_format: file
model_data_format: file
models:
  fcn_caffe_mace: # model tag, which will be used in model loading and must be specific.
    platform: caffe
    # support local path, http:// and https://
    model_file_path:  /fei/Code/fcn_model/caffe/caffe_mace.prototxt
    weight_file_path: /fei/Code/fcn_model/caffe/nyud-fcn32s-color-heavy.caffemodel
    # sha256_checksum of your model's graph and data files.
    # get the sha256_checksum: sha256sum path/to/your/file
    model_sha256_checksum: 17c04644175ecff7f8a4f1a6b550b488d8bd2760c1f4b8587303a8db2f28a28d
    weight_sha256_checksum: c08763827d0ef76c275084a5e2c5fd254054789a29fd31320cfea9ffc52b8714
    # define your model's interface
    subgraphs:
      - input_tensors:
          - data
        input_shapes: # NHWC
          - 1,1280,1280,3
        output_tensors:
          - prob
        output_shapes:
          - 1,1280,1280,1
    runtime: cpu+gpu
    winograd: 0
```

### Describe the problem
model convert failed, with logs in ###Error information / logs section.

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /mace
2. python tools/converter.py convert --config_file=/fei/Code/fcn_model/caffe/caffe_mace.yml
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs

--------------------------------------
         Common Configuration         
--------------------------------------
|        key        |     value      |
======================================
|       library_name|  fcn_caffe_mace|
--------------------------------------
|        target_abis| ['armeabi-v7a']|
--------------------------------------
|        target_socs|              []|
--------------------------------------
| model_graph_format|            file|
--------------------------------------
|  model_data_format|            file|
--------------------------------------

************************************************
          Convert fcn_caffe_mace model          
************************************************

WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Analysed target //mace/python/tools:converter (20 packages loaded).
INFO: Found 1 target...
Target //mace/python/tools:converter up-to-date:
  bazel-bin/mace/python/tools/converter
INFO: Elapsed time: 5.015s, Critical Path: 0.24s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

Transform model to one that can better run on device
Remove layer drop6 (Dropout)
Remove layer drop7 (Dropout)
Traceback (most recent call last):
  File "tools/converter.py", line 1242, in <module>
    flags.func(flags)
  File "tools/converter.py", line 761, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 691, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/mace/tools/sh_commands.py", line 518, in gen_model_code
    _fg=True)
  File "/root/.pyenv/versions/2.7.14/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.SignalException_SIGKILL: 

  RAN: /root/.pyenv/versions/2.7.14/bin/python bazel-bin/mace/python/tools/converter -u --platform=caffe --model_file=/fei/Code/fcn_model/caffe/caffe_mace.prototxt --weight_file=/fei/Code/fcn_model/caffe/nyud-fcn32s-color-heavy.caffemodel --model_checksum=17c04644175ecff7f8a4f1a6b550b488d8bd2760c1f4b8587303a8db2f28a28d --weight_checksum=c08763827d0ef76c275084a5e2c5fd254054789a29fd31320cfea9ffc52b8714 --input_node=data --input_data_formats=NHWC --output_node=prob --output_data_formats=NHWC --check_node= --runtime=cpu+gpu --template=mace/python/tools --model_tag=fcn_caffe_mace --input_shape=1,1280,1280,3 --input_range= --output_shape=1,1280,1280,1 --check_shape= --dsp_mode=0 --embed_model_data=False --winograd=0 --quantize=0 --quantize_range_file= --change_concat_ranges=0 --obfuscate=0 --output_dir=mace/codegen/models/fcn_caffe_mace --model_graph_format=file --data_type=fp16_fp32 --graph_optimize_options= --cl_mem_type=image

  STDOUT:


  STDERR:

```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by FeiZhu** [comment]
switched bazel verion from 0.16.0 to 0.13.0, same issue.

**Comment by FeiZhu** [comment]
Conversion succeeded by building MACE natively on MacOS instead of in docker. I'm closing the issue, although the issue  still exists in docker.
