### ISSUE TITLE
Cannot run model on Firefly RK3399, syntax error near unexpected token `( '

### ISSUE THREAD

**Issue by RoyLJH** [XiaoMi/mace#398]
## Problem Statement
I follow the instructions  in the website of  [**Advanced Usage.**](https://mace.readthedocs.io/en/latest/user_guide/advanced_usage.html#run-you-model-on-the-embedded-device-arm-linux) 

But I don't know  the proper value of  **target_abis**  in both model and device configuration files, but I think it is necessary to keep them consistent  in both files.

So I tried  two groups of  values : **arm64-v8a**  and **arm64** , and  after I converted the model successfully  and tried to  run 
**python tools/converter.py run --config=/path/to/your/model_deployment_file.yml --device_yml=/path/to/devices.yml**
 they both failed with same error info: 

=========================*Console Output *==============================
```bash
root@ljh-Inspiron-3670:/home/ljh/software/mace# python tools/converter.py run --config=mace-configures/model_yml/mobilenet-v1/mobilenet-v1.yml --device_yml=mace-configures/device_yml/firefly_rk3399.yml 
* Build //mace/tools/validation:mace_run_static with ABI arm64-v8a
INFO: Analysed target //mace/tools/validation:mace_run_static (2 packages loaded).
INFO: Found 1 target...
Target //mace/tools/validation:mace_run_static up-to-date:
  bazel-bin/mace/tools/validation/mace_run_static
INFO: Elapsed time: 164.334s, Critical Path: 28.33s
INFO: 118 processes: 117 linux-sandbox, 1 local.
INFO: Build completed successfully, 120 total actions
Build done!

*****************************************************************************************
          Run model mobilenet_v1 on RockchipRK3399FireflyBoard(LinuxOpensource)          
*****************************************************************************************

Generate input file:  builds/mobilenet-v1/_tmp/mobilenet_v1/f330dec17e45a8626cfb225ddce95051/RockchipRK3399FireflyBoard(LinuxOpensource)_RK3399/arm64-v8a/model_input_input
Generate input file done.
* Run 'mobilenet_v1' with round=1, restart_round=1, tuning=False, out_of_range_check=False, omp_num_threads=(-1,), cpu_affinity_policy=(1,), gpu_perf_hint=(3,), gpu_priority_hint=(3,)
Push builds/mobilenet-v1/_tmp/mobilenet_v1/f330dec17e45a8626cfb225ddce95051/RockchipRK3399FireflyBoard(LinuxOpensource)_RK3399/arm64-v8a/model_input_input to /tmp/data/mace_run
Push builds/mobilenet-v1/model/mobilenet_v1.data to /tmp/data/mace_run
Push third_party/nnlib/libhexagon_controller.so to /tmp/data/mace_run
Push builds/mobilenet-v1/model/mobilenet_v1.pb to /tmp/data/mace_run/mobilenet_v1.pb
Push builds/mobilenet-v1/_tmp/arm64-v8a/mace_run_static to /tmp/data/mace_run
Push /tmp/cmd_file-mobilenet_v1-1552567733.57 to /tmp/data/mace_run/cmd_file-mobilenet_v1-1552567733.57
/tmp/data/mace_run/cmd_file-mobilenet_v1-1552567733.57: 1: /tmp/data/mace_run/cmd_file-mobilenet_v1-1552567733.57: Syntax error: "(" unexpected
Traceback (most recent call last):
  File "tools/converter.py", line 1308, in <module>
    flags.func(flags)
  File "tools/converter.py", line 1003, in run_mace
    device.run_specify_abi(flags, configs, target_abi)
  File "/home/ljh/software/mace/tools/device.py", line 615, in run_specify_abi
    YAMLKeyword.model_file_path]
  File "/home/ljh/software/mace/tools/device.py", line 341, in tuning_run
    _err_to_out=True)
  File "/home/ljh/software/mace/tools/device.py", line 72, in exec_command
    command, *args, **kwargs)
  File "/home/ljh/software/anaconda2/lib/python2.7/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/home/ljh/software/anaconda2/lib/python2.7/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/home/ljh/software/anaconda2/lib/python2.7/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/ljh/software/anaconda2/lib/python2.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_2: 

  RAN: /usr/bin/ssh firefly@10.42.0.114 sh /tmp/data/mace_run/cmd_file-mobilenet_v1-1552567733.57

  STDOUT:


  STDERR:
```
=========================* End of Console Output *==============================

## My  Device  Configuration YML
```bash
devices:
    firefly:
        target_abis: [arm64-v8a]
        target_socs: RK3399
        models: Rockchip RK3399 Firefly Board (Linux Opensource)
        address: 10.42.0.114
        username: firefly
```

## My  Model Configuration YML
```bash
library_name: mobilenet-v1
target_abis: [arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  mobilenet_v1:
    platform: tensorflow
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v1/mobilenet-v1-1.0.pb
    model_sha256_checksum: 71b10f540ece33c49a7b51f5d4095fc9bd78ce46ebf0300487b2ee23d71294e6
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,224,224,3
        output_tensors:
          - MobilenetV1/Predictions/Reshape_1
        output_shapes:
          - 1,1001
        validation_inputs_data:
          - https://cnbj1.fds.api.xiaomi.com/mace/inputs/dog.npy
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0

```

Thanks a lot to anyone who can answer my question :)  :+1:

**Comment by RoyLJH** [comment]
## How to choose a proper target_abis  value ? 

In model deployment file , since the target_abis value  is constained to _host_ , _armeabi-v7a_ or _arm64-v8a_ ,  I  choose  `arm64-v8a`  

In device configuration,  I follow the  instructions and I get  `arm64`  via `dpkg --print-architecture` .
So I choose to fill in `arm64`  

However  when I run `python tools/converter.py run --config=/path/to/your/model_deployment_file.yml --device_yml=/path/to/devices.yml`  I  get  a   message saying :  

```bash

The device with soc RK3399 do not support abi arm64-v8a

```

So what is the right way  of filling in  the **target_abis**  value ?

**Comment by RoyLJH** [comment]
Problem Solved.

The Traceback info says that  
`syntax error near unexpected token `(   `

And I look at my device configuration file and realised where the problem lies.
In  [documentation](https://mace.readthedocs.io/en/latest/user_guide/advanced_usage.html#convert-model-s-to-c-code )  , we should fill in the **model** value  via  the  command `lshw`  

And I got a result of `Rockchip RK3399 Firefly Board (Linux Opensource)`   via `lshw` 
However,  the **(**   caused  the error

So  I changed  the **model** value to `Rockchip RK3399 Firefly Board`   and it worked.
