### ISSUE TITLE
Quantization fails: divison by zero

### ISSUE THREAD

**Issue by gasgallo** [XiaoMi/mace#414]
I'm working with the provided Docker image, that means:
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.5 LTS
- **NDK version(e.g., 15c)**: 15c
- **GCC version(if compiling for host, e.g., 5.4.0)**: 5.4.0
- **MACE version (Use the command: git describe --long --tags)**: v0.10.0-0-g22e40d6
- **Python version(2.7)**: 2.7.14
- **Bazel version (e.g., 0.13.0)**: 0.16.0

### Model deploy file (*.yml)
```yaml
library_name: model_test
target_abis: [armeabi-v7a]
target_socs: [sdm845]
model_graph_format: file
model_data_format: file
models:
  model:
    platform: tensorflow
    model_file_path: /model/frozen_model.pb
    model_sha256_checksum: 77d382efd2a88f9ee5b23fcd71a4888d37daf914205adc0176c25d3245c7f26e
    subgraphs:
      - input_tensors:
          - data
        input_shapes:
          - 1,112,112,3
        output_tensors:
          - fc/add
        output_shapes:
          - 1,1,1,512:0
    obfuscate: 0
    quantize: 1
    quantize_range_file: /mace/overall_range
    runtime: cpu
    winograd: 0
```

### Describe the problem
When trying to create a quantized model, the conversion fails due to the errror show in the logs below.

### To Reproduce
Steps to reproduce the problem (after having obtained the quantization stats and logs):
```bash
1. cd /path/to/mace
2. execute the whole pipeline to quantize a model
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
Add quantize tensor range
Traceback (most recent call last):
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 355, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 196, in main
    output_graph_def, quantize_activation_info = mace_transformer.run()
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 125, in run
    changed = transformer()
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 1633, in add_quantize_tensor_range
    min_val, max_val, non_zero=False)
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/quantization/quantize_util.py", line 69, in adjust_range
    scale = -out_min / zero_int
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "tools/converter.py", line 1242, in <module>
    flags.func(flags)
  File "tools/converter.py", line 761, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 691, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/mace/tools/sh_commands.py", line 518, in gen_model_code
    _fg=True)
  File "/root/.pyenv/versions/2.7.14/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /root/.pyenv/versions/2.7.14/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=/model/frozen_model.pb --weight_file= --model_checksum=c00ebcde1a6e9e012f094410404230b3f5b5b99939fd1c8dca40d8777b98d7c8 --weight_checksum= --input_node=data --input_data_formats=NHWC --output_node=fc1/add_1 --output_data_formats=NHWC --check_node= --runtime=cpu --template=mace/python/tools --model_tag=model --input_shape=1,112,112,3 --input_range= --output_shape=1,1,1,512 --check_shape= --dsp_mode=0 --embed_model_data=False --winograd=0 --quantize=1 --quantize_range_file=/model/overall_range --change_concat_ranges=0 --obfuscate=0 --output_dir=mace/codegen/models/model --model_graph_format=file --data_type=fp32_fp32 --graph_optimize_options= --cl_mem_type=image

  STDOUT:


  STDERR:
```

### Additional context
<pre>
def adjust_range(in_min, in_max, non_zero):
    out_max = max(0.0, in_max)
    out_min = min(0.0, in_min)
    if non_zero:
        out_min = min(out_min, in_min - (out_max - in_min) / 254.0)
    scale = (out_max - out_min) / 255.0
    eps = 1e-6
    if out_min < -eps and out_max > eps:
        zero = -out_min / scale
        zero_int = int(round(zero))
        if abs(zero - zero_int) > eps:
            if zero < zero_int or non_zero:
                zero_int = int(math.ceil(zero))
                scale = out_max / (255.0 - zero_int)
            else:
                <b>scale = -out_min / zero_int</b>
    elif out_min > -eps:
        zero_int = 0
    else:
        zero_int = 255

    return scale, zero_int, -zero_int*scale, (255-zero_int)*scale
</pre>
It seems like the condition of `zero_int=0` hasn't been managed yet.

**Comment by lee-bin** [comment]
Thanks, we are going to fix it.

**Comment by lee-bin** [comment]
Fixed in https://github.com/XiaoMi/mace/commit/087f7697187096a01cb4e1952e5f16029de6f6fe

**Comment by gasgallo** [comment]
Great!
