### ISSUE TITLE
cannot quantize (post train) my model or shufflenetv2 in mace-model

### ISSUE THREAD

**Issue by FrisaSZ** [XiaoMi/mace#418]
### System information
**I use docker image**
**repo**: registry.cn-hangzhou.aliyuncs.com/xiaomimace/mace-dev-lite
**tag**: latest
**image id**: 7a74a198a246
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.5 LTS
- **NDK version(e.g., 15c)**: r15c
- **GCC version(if compiling for host, e.g., 5.4.0)**: 5.4.0
- **MACE version (Use the command: git describe --long --tags)**: v0.10.0-192-gabbc3d4
- **Python version(2.7)**: 2.7.14
- **Bazel version (e.g., 0.13.0)**: 0.16.0
- **tensorflow version**: 1.12.0

#### model_host.yml
```yaml
library_name: shufflenet_seg_host
target_abis: [host]
model_graph_format: file
model_data_format: file
models:
  shufflenet_seg_host:
    platform: tensorflow
    model_file_path: /container/path/model.pb
    model_sha256_checksum: 0b3fa86c0cf0023018f58aadf1b56eec855d663fd8f05f724e3fcffb1f99d170
    subgraphs:
      - input_tensors: inputs
        output_tensors: predictions:0
        input_shapes: 1,256,256,3
        output_shapes: 1,256,256
    runtime: cpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
```
#### model_post_quant.yml
```yaml
library_name: shufflenet_seg_quant
target_abis: [armeabi-v7a]
model_graph_format: file
model_data_format: file
models:
  shufflenet_seg_quant:
    platform: tensorflow
    model_file_path: /container/path/model.pb
    model_sha256_checksum: 0b3fa86c0cf0023018f58aadf1b56eec855d663fd8f05f724e3fcffb1f99d170
    subgraphs:
      - input_tensors: inputs
        output_tensors: predictions:0
        input_shapes: 1,256,256,3
        output_shapes: 1,256,256
    runtime: cpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
    quantize: 1
    quantize_range_file: /container/path/mace/overall_range
```

### 1. Problem 1
I have built a very small model for semantic segmentation using tensorflow(version=1.12.0), exported frozen model and calculated tensor range of each activation layer statistically using sample inputs. But I failed to convert frozen model to quantized model.

#### 1.1 To Reproduce
The code of my small model can be found [here](https://gist.github.com/FrisaSZ/b24c317e2c3888b5430770c94fd9c944). 
Just run 
```bash
python shufflenetv2_seg.py
```
to generate a frozen model. Or you can directly use the .pb file I've generated [here](https://drive.google.com/open?id=1JG0UNQyUae2XhlCPaOwf-9PSdvcITR-W).
Run 
```bash
python tools/converter.py convert --config=/path/to/model_host.yml
python tools/converter.py run --config=/path/to/model_host.yml --quantize_stat --input_dir=/path/to/input_tensors > range_log
python mace/python/tools/quantization/quantize_stat.py --log_file range_log > overall_range
```
to generate quantize_range_file. You can find the range file [here](https://drive.google.com/open?id=1oHpwsFOsR_gV-3WN5x9bJy0wP-voD64L).
After that, I run
```bash
python tools/converter.py convert --config=/path/to/model_post_quant.yml
```
this conversion failed. The error information is below.

#### 1.2 Error information
```bash
-------------------------------------------
            Common Configuration           
-------------------------------------------
|        key        |        value        |
===========================================
|       library_name| shufflenet_seg_quant|
-------------------------------------------
|        target_abis|      ['armeabi-v7a']|
-------------------------------------------
|        target_socs|                   []|
-------------------------------------------
| model_graph_format|                 file|
-------------------------------------------
|  model_data_format|                 file|
-------------------------------------------

******************************************************
          Convert shufflenet_seg_quant model          
******************************************************

WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Analysed target //mace/python/tools:converter (21 packages loaded).
INFO: Found 1 target...
Target //mace/python/tools:converter up-to-date:
  bazel-bin/mace/python/tools/converter
INFO: Elapsed time: 2.573s, Critical Path: 0.10s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

Transform model to one that can better run on device
Run transform_graph: ['strip_unused_nodes', 'remove_nodes(op=Identity, op=CheckNumerics)', 'fold_constants(ignore_errors=true)', 'fold_batch_norms', 'fold_old_batch_norms', 'remove_control_dependencies', 'strip_unused_nodes', 'sort_by_execution_order']
('output keys: ', ['predictions:0'])
Transform fake quantize
Fold depthwise conv and bn: stage2/shufflenetv2_downsample/dswc_left/depthwise(DepthwiseConv2d)
Fold depthwise conv and bn: stage2/shufflenetv2_downsample/dswc_right/depthwise(DepthwiseConv2d)
Fold depthwise conv and bn: stage2/shufflenetv2_basic/dswc_right/depthwise(DepthwiseConv2d)
Fold biasadd: stage1/conv_unit/conv2d/Conv2D(Conv2D)
Fold biasadd: stage2/shufflenetv2_downsample/conv1x1_before/conv2d/Conv2D(Conv2D)
Fold biasadd: stage2/shufflenetv2_downsample/conv1x1_after/conv2d/Conv2D(Conv2D)
Fold biasadd: stage2/shufflenetv2_downsample/conv1x1/conv2d/Conv2D(Conv2D)
Fold biasadd: stage2/shufflenetv2_basic/conv1x1_before/conv2d/Conv2D(Conv2D)
Fold biasadd: stage2/shufflenetv2_basic/conv1x1_after/conv2d/Conv2D(Conv2D)
Fold biasadd: aspp/conv1x1/conv2d/Conv2D(Conv2D)
Fold biasadd: aspp/image_pooling/conv1x1/conv2d/Conv2D(Conv2D)
Fold biasadd: aspp/concat_project/conv2d/Conv2D(Conv2D)
Fold biasadd: logits/conv1x1/conv2d/Conv2D(Conv2D)
Fold activation: stage1/conv_unit/batch_normalization/FusedBatchNorm(Conv2D)
Fold activation: stage2/shufflenetv2_downsample/conv1x1_before/batch_normalization/FusedBatchNorm(Conv2D)
Fold activation: stage2/shufflenetv2_downsample/conv1x1_after/batch_normalization/FusedBatchNorm(Conv2D)
Fold activation: stage2/shufflenetv2_downsample/conv1x1/batch_normalization/FusedBatchNorm(Conv2D)
Fold activation: stage2/shufflenetv2_basic/conv1x1_before/batch_normalization/FusedBatchNorm(Conv2D)
Fold activation: stage2/shufflenetv2_basic/conv1x1_after/batch_normalization/FusedBatchNorm(Conv2D)
Fold activation: aspp/conv1x1/batch_normalization/FusedBatchNorm(Conv2D)
Fold activation: aspp/image_pooling/conv1x1/batch_normalization/FusedBatchNorm(Conv2D)
Fold activation: aspp/concat_project/batch_normalization/FusedBatchNorm(Conv2D)
Transpose filters to OHWI
Add OpenCL informations
Sort by execution
Final ops:
stage1/conv_unit/Relu (Conv2D, index:0): [[1L, 128L, 128L, 24L]]
stage1/max_pooling2d/MaxPool (Pooling, index:1): [[1L, 64L, 64L, 24L]]
stage2/shufflenetv2_downsample/dswc_left/depthwise (DepthwiseConv2d, index:2): [[1L, 32L, 32L, 24L]]
stage2/shufflenetv2_downsample/conv1x1/Relu (Conv2D, index:3): [[1L, 32L, 32L, 24L]]
stage2/shufflenetv2_downsample/split_shuffle/split (Split, index:4): [[1L, 32L, 32L, 12L], [1L, 32L, 32L, 12L]]
stage2/shufflenetv2_downsample/conv1x1_before/Relu (Conv2D, index:5): [[1L, 64L, 64L, 24L]]
stage2/shufflenetv2_downsample/dswc_right/depthwise (DepthwiseConv2d, index:6): [[1L, 32L, 32L, 24L]]
stage2/shufflenetv2_downsample/conv1x1_after/Relu (Conv2D, index:7): [[1L, 32L, 32L, 24L]]
stage2/shufflenetv2_downsample/split_shuffle/split_1 (Split, index:8): [[1L, 32L, 32L, 12L], [1L, 32L, 32L, 12L]]
stage2/shufflenetv2_downsample/split_shuffle/concat (Concat, index:9): [[1L, 32L, 32L, 48L]]
stage2/shufflenetv2_basic/split (Split, index:10): [[1L, 32L, 32L, 24L], [1L, 32L, 32L, 24L]]
stage2/shufflenetv2_basic/split_shuffle/split (Split, index:11): [[1L, 32L, 32L, 12L], [1L, 32L, 32L, 12L]]
stage2/shufflenetv2_basic/conv1x1_before/Relu (Conv2D, index:12): [[1L, 32L, 32L, 24L]]
stage2/shufflenetv2_basic/dswc_right/depthwise (DepthwiseConv2d, index:13): [[1L, 32L, 32L, 24L]]
stage2/shufflenetv2_basic/conv1x1_after/Relu (Conv2D, index:14): [[1L, 32L, 32L, 24L]]
stage2/shufflenetv2_basic/split_shuffle/split_1 (Split, index:15): [[1L, 32L, 32L, 12L], [1L, 32L, 32L, 12L]]
stage2/shufflenetv2_basic/split_shuffle/concat (Concat, index:16): [[1L, 32L, 32L, 48L]]
aspp/image_pooling/AvgPool2D/AvgPool (Pooling, index:17): [[1L, 1L, 1L, 48L]]
aspp/image_pooling/conv1x1/Relu (Conv2D, index:18): [[1L, 1L, 1L, 192L]]
aspp/image_pooling/ResizeBilinear (ResizeBilinear, index:19): [[1L, 32L, 32L, 192L]]
aspp/conv1x1/Relu (Conv2D, index:20): [[1L, 32L, 32L, 192L]]
aspp/concat (Concat, index:21): [[1L, 32L, 32L, 384L]]
aspp/concat_project/Relu (Conv2D, index:22): [[1L, 32L, 32L, 192L]]
logits/conv1x1/conv2d/BiasAdd (Conv2D, index:23): [[1L, 32L, 32L, 4L]]
logits/logits (ResizeBilinear, index:24): [[1L, 256L, 256L, 4L]]
predictions (ArgMax, index:25): [[1L, 256L, 256L]]
update data format
Add quantize tensor range
Add default quantize info for input
Input range inputs: [-1.0, 1.0]
Add default quantize info for ops like Pooling, Softmax
Add mace quantize and dequantize nodes
Quantize weights
Sort by execution
Final ops:
mace_input_node_inputs (Quantize, index:): [[1L, 256L, 256L, 3L]]
stage1/conv_unit/Relu (Conv2D, index:0): [[1L, 128L, 128L, 24L]]
stage1/max_pooling2d/MaxPool (Pooling, index:1): [[1L, 64L, 64L, 24L]]
stage2/shufflenetv2_downsample/dswc_left/depthwise (DepthwiseConv2d, index:2): [[1L, 32L, 32L, 24L]]
stage2/shufflenetv2_downsample/conv1x1/Relu (Conv2D, index:3): [[1L, 32L, 32L, 24L]]
stage2/shufflenetv2_downsample/split_shuffle/split (Split, index:4): [[1L, 32L, 32L, 12L], [1L, 32L, 32L, 12L]]
stage2/shufflenetv2_downsample/conv1x1_before/Relu (Conv2D, index:5): [[1L, 64L, 64L, 24L]]
stage2/shufflenetv2_downsample/dswc_right/depthwise (DepthwiseConv2d, index:6): [[1L, 32L, 32L, 24L]]
stage2/shufflenetv2_downsample/conv1x1_after/Relu (Conv2D, index:7): [[1L, 32L, 32L, 24L]]
stage2/shufflenetv2_downsample/split_shuffle/split_1 (Split, index:8): [[1L, 32L, 32L, 12L], [1L, 32L, 32L, 12L]]
stage2/shufflenetv2_downsample/split_shuffle/concat (Concat, index:9): [[1L, 32L, 32L, 48L]]
stage2/shufflenetv2_basic/split (Split, index:10): [[1L, 32L, 32L, 24L], [1L, 32L, 32L, 24L]]
stage2/shufflenetv2_basic/split_shuffle/split (Split, index:11): [[1L, 32L, 32L, 12L], [1L, 32L, 32L, 12L]]
stage2/shufflenetv2_basic/conv1x1_before/Relu (Conv2D, index:12): [[1L, 32L, 32L, 24L]]
stage2/shufflenetv2_basic/dswc_right/depthwise (DepthwiseConv2d, index:13): [[1L, 32L, 32L, 24L]]
stage2/shufflenetv2_basic/conv1x1_after/Relu (Conv2D, index:14): [[1L, 32L, 32L, 24L]]
stage2/shufflenetv2_basic/split_shuffle/split_1 (Split, index:15): [[1L, 32L, 32L, 12L], [1L, 32L, 32L, 12L]]
stage2/shufflenetv2_basic/split_shuffle/concat (Concat, index:16): [[1L, 32L, 32L, 48L]]
aspp/image_pooling/AvgPool2D/AvgPool (Pooling, index:17): [[1L, 1L, 1L, 48L]]
aspp/image_pooling/conv1x1/Relu (Conv2D, index:18): [[1L, 1L, 1L, 192L]]
aspp/image_pooling/ResizeBilinear (ResizeBilinear, index:19): [[1L, 32L, 32L, 192L]]
aspp/conv1x1/Relu (Conv2D, index:20): [[1L, 32L, 32L, 192L]]
aspp/concat (Concat, index:21): [[1L, 32L, 32L, 384L]]
aspp/concat_project/Relu (Conv2D, index:22): [[1L, 32L, 32L, 192L]]
logits/conv1x1/conv2d/BiasAdd (Conv2D, index:23): [[1L, 32L, 32L, 4L]]
logits/logits (ResizeBilinear, index:24): [[1L, 256L, 256L, 4L]]
mace_output_node_predictions (ArgMax, index:25): [[1L, 256L, 256L]]
predictions_0 (Dequantize, index:): [[1L, 256L, 256L]]
Check quantize info
Op output mace_input_node_inputs range: [-1.007874, 1.000000]
Op output stage1/conv_unit/Relu:0 range: [0.000000, 6.546060]
Op output stage1/max_pooling2d/MaxPool:0 range: [0.000000, 6.546060]
Op output stage2/shufflenetv2_downsample/dswc_left/depthwise:0 range: [-22.317579, 18.044000]
Op output stage2/shufflenetv2_downsample/conv1x1/Relu:0 range: [0.000000, 38.997600]
Traceback (most recent call last):
  File "/container/path/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 391, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/container/path/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 224, in main
    output_graph_def, quantize_activation_info = mace_transformer.run()
  File "/container/path/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 129, in run
    changed = transformer()
  File "/container/path/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 1819, in check_quantize_info
    "missing quantize info: %s" % op)
  File "/container/path/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/convert_util.py", line 20, in mace_check
    raise Exception(msg)
Exception: missing quantize info: input: "stage2/shufflenetv2_downsample/conv1x1/Relu:0"
output: "stage2/shufflenetv2_downsample/split_shuffle/split:0"
output: "stage2/shufflenetv2_downsample/split_shuffle/split:1"
name: "stage2/shufflenetv2_downsample/split_shuffle/split"
type: "Split"
arg {
  name: "T"
  i: 2
}
arg {
  name: "framework_type"
  i: 0
}
arg {
  name: "axis"
  i: 3
}
arg {
  name: "num_split"
  i: 2
}
arg {
  name: "has_data_format"
  i: 1
}
output_shape {
  dims: 1
  dims: 32
  dims: 32
  dims: 12
}
output_shape {
  dims: 1
  dims: 32
  dims: 32
  dims: 12
}
quantize_info {
  scale: 0.143708627451
  zero_point: 0
  minval: 0.0
  maxval: 36.6457
}
quantize_info {
  scale: 0.152931764706
  zero_point: 0
  minval: 0.0
  maxval: 38.9976
}
quantize_info {
  scale: 0.143708627451
  zero_point: 0
  minval: 0.0
  maxval: 36.6457
}
quantize_info {
  scale: 0.152931764706
  zero_point: 0
  minval: 0.0
  maxval: 38.9976
}

Traceback (most recent call last):
  File "tools/converter.py", line 1354, in <module>
    flags.func(flags)
  File "tools/converter.py", line 816, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 745, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/container/path/mace/tools/sh_commands.py", line 541, in gen_model_code
    _fg=True)
  File "/root/.pyenv/versions/2.7.14/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /root/.pyenv/versions/2.7.14/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=/container/path/model.pb --weight_file= --model_checksum=0b3fa86c0cf0023018f58aadf1b56eec855d663fd8f05f724e3fcffb1f99d170 --weight_checksum= --input_node=inputs --input_data_formats=NHWC --output_node=predictions:0 --output_data_formats=NHWC --check_node= --runtime=cpu --template=mace/python/tools --model_tag=shufflenet_seg_quant --input_shape=1,256,256,3 --input_range= --output_shape=1,256,256 --check_shape= --dsp_mode=0 --embed_model_data=False --winograd=0 --quantize=1 --quantize_range_file=/container/path/mace/overall_range --change_concat_ranges=0 --obfuscate=0 --output_dir=mace/codegen/models/shufflenet_seg_quant --model_graph_format=file --data_type=fp32_fp32 --graph_optimize_options= --cl_mem_type=image

  STDOUT:


  STDERR:
```

#### 1.3 Solution
I have found the error above is caused by a wrong indent.
Modify the conversion code [here](https://github.com/XiaoMi/mace/blob/abbc3d4d8e5f769b66a0da76414123b459e439c3/mace/python/tools/converter_tool/transformer.py#L1702-L1708)
from 
```python
for output in op.output:
    mace_check(output in self._quantize_activation_info,
                         "%s does not have quantize activation info"
                         % op)
    op.quantize_info.extend([
           self._quantize_activation_info[output]
           for output in op.output])
```
to
```python
for output in op.output:
    mace_check(output in self._quantize_activation_info,
                         "%s does not have quantize activation info"
                         % op)
op.quantize_info.extend([
       self._quantize_activation_info[output]
       for output in op.output])
```
Now the conversion succeed. But there is another problem.

### 2. Problem 2
After converting frozen model to quantized model I can't run it on my phone(小米MIX2).
#### 2.1 To Reproduce
Run
```bash
python tools/converter.py run --config=/path/to/model_post_quant.yml --example
```
the error information is below.
#### 2.2 Error information
```bash
* Build //mace/libmace:libmace_static with ABI armeabi-v7a
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Analysed target //mace/libmace:libmace_static (35 packages loaded).
INFO: Found 1 target...
Target //mace/libmace:libmace_static up-to-date:
  bazel-genfiles/mace/libmace/libmace.a
INFO: Elapsed time: 8.831s, Critical Path: 0.30s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
Build done!

* Build //mace/examples/cli:example_static with ABI armeabi-v7a
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
INFO: Analysed target //mace/examples/cli:example_static (17 packages loaded).
INFO: Found 1 target...
Target //mace/examples/cli:example_static up-to-date:
  bazel-bin/mace/examples/cli/example_static
INFO: Elapsed time: 7.645s, Critical Path: 0.33s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
Build done!

**********************************************************
          Run model shufflenet_seg_quant on MIX2          
**********************************************************

Generate input file:  builds/shufflenet_seg_quant/_tmp/shufflenet_seg_quant/7d1686d3058f15cefab33cfd42d32cec/MIX2_msm8998/armeabi-v7a/model_input_inputs
Generate input file done.
* Run 'shufflenet_seg_quant' with round=1, restart_round=1, tuning=False, out_of_range_check=False, omp_num_threads=(-1,), cpu_affinity_policy=(1,), gpu_perf_hint=(3,), gpu_priority_hint=(3,)
Push builds/shufflenet_seg_quant/_tmp/shufflenet_seg_quant/7d1686d3058f15cefab33cfd42d32cec/MIX2_msm8998/armeabi-v7a/model_input_inputs to /data/local/tmp/mace_run
Push builds/shufflenet_seg_quant/model/shufflenet_seg_quant.data to /data/local/tmp/mace_run
Push builds/shufflenet_seg_quant/model/shufflenet_seg_quant.pb to /data/local/tmp/mace_run/shufflenet_seg_quant.pb
Push builds/shufflenet_seg_quant/_tmp/armeabi-v7a/example_static to /data/local/tmp/mace_run
Push /tmp/cmd_file-shufflenet_seg_quant-1554284316.9 to /data/local/tmp/mace_run/cmd_file-shufflenet_seg_quant-1554284316.9
WARNING: linker: "/data/local/tmp/mace_run/example_static" unused DT entry: type 0xf arg 0x8e1
mace version: v0.10.0-192-gabbc3d4
input node: inputs
input shape: 1,256,256,3
output node: predictions:0
output shape: 1,256,256
input_file: /data/local/tmp/mace_run/model_input
output_file: /data/local/tmp/mace_run/model_out
input_dir:
output dir:
model_data_file: /data/local/tmp/mace_run/shufflenet_seg_quant.data
model_file: /data/local/tmp/mace_run/shufflenet_seg_quant.pb
device: CPU
round: 1
restart_round: 1
gpu_perf_hint: 3
gpu_priority_hint: 3
omp_num_threads: -1
cpu_affinity_policy: 1
restart round 0
I mace/libmace/mace.cc:776] Create MaceEngine from model graph proto and weights data
I mace/libmace/mace.cc:414] Creating MaceEngine, MACE version: v0.10.0-192-gabbc3d4
I mace/libmace/mace.cc:446] Initializing MaceEngine
F mace/core/operator.cc:293] Key not registered: Split0T_DT_UINT8
F mace/core/operator.cc:293] backtrace:
F mace/core/operator.cc:293]  pc 0xb5fe04b6
F mace/core/operator.cc:293]  pc 0xb5fe11c8
F mace/core/operator.cc:293]  pc 0xb5fe113a
F mace/core/operator.cc:293]  pc 0xb5fe1578
F mace/core/operator.cc:293]  pc 0xb5fe1692
F mace/core/operator.cc:293]  pc 0xb60ae068
F mace/core/operator.cc:293]  pc 0xb60afd82
F mace/core/operator.cc:293]  pc 0xb60b0382
F mace/core/operator.cc:293]  pc 0xb5fe2de4
F mace/core/operator.cc:293]  pc 0xb5fe6b4a
F mace/core/operator.cc:293]  pc 0xb5fcc956
F mace/core/operator.cc:293]  pc 0xb5fd012a
F mace/core/operator.cc:293]  pc 0xb5fd0c50
F mace/core/operator.cc:293]  pc 0xe9736e4a __libc_init
Aborted
ERROR: [Mace Run] /container/path/mace/tools/device.py:354: Mace run failed.
```
It seems that the **Split** op is not supported in quantized model. I have tried to remove the Split op in my network. But some other "Key not registered" errors occur, such as ArgMax, Activation..etc
I want to know whether it is because these ops are not supported or there are bugs in mace cpp cores.

**Comment by lee-bin** [comment]
Thanks.
Quantized Split op is not supported.
We have tested quantized MobileNets, InceptionV3, and DeeplabV3+.

**Comment by FrisaSZ** [comment]
Thanks. Guess I'll have to use ops in those models.
