### ISSUE TITLE
Tensorflow ssd-mobilenet-v1模型转换失败

### ISSUE THREAD

**Issue by aliqing0122** [XiaoMi/mace#434]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
ubuntu:14.04
- **NDK version(e.g., 15c)**:
ndk16b
- **GCC version(if compiling for host, e.g., 5.4.0)**:
4.8.5
- **MACE version (Use the command: git describe --long --tags)**:
v0.10.0-241-g9b0b03c
- **Python version(2.7)**: 
2.7
- **Bazel version (e.g., 0.13.0)**:
0.19.2
### Model deploy file (*.yml)
```yaml
library_name: ssd_mobilenet-v1_tf                                                                                                                                                              
target_abis: [armeabi-v7a, arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  ssd_mobilenet_v1_tf:
    platform: tensorflow
    model_file_path: /home/user/iwork/test/ssd_mobilenet_v1_coco_tf/frozen_inference_graph.pb
    model_sha256_checksum: 0cb4161a6310632814cd25afe11c261cff9a7d55487a813acd54772285b54850
    subgraphs:
      - input_tensors:
          - Preprocessor/sub
        input_shapes:
          - 1,300,300,3
        output_tensors:
          - detection_classes
          - detection_boxes
          - detection_scores
        output_shapes:
          - 1,1,1,100
          - 1,1,100,4
          - 1,1,1,100
    runtime: cpu 
    #input_data_types: int32
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
......
```

### Describe the problem
# 模型下载地址
http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2018_01_28.tar.gz
# 转换命令
python tools/converter.py convert --config=/home/user/iwork/test/ssd_mobilenet_v1_coco_tf/mobilenet-v1.yml

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
Transform model to one that can better run on device
Run transform_graph: ['strip_unused_nodes', 'remove_nodes(op=Identity, op=CheckNumerics)', 'fold_constants(ignore_errors=true)', 'fold_batch_norms', 'fold_old_batch_norms', 'remove_control_dependencies', 'strip_unused_nodes', 'sort_by_execution_order']
('output keys: ', ['detection_classes', 'detection_boxes', 'detection_scores'])
2019-05-07 17:29:48.944007: E tensorflow/tools/graph_transforms/transform_graph.cc:332] fold_constants: Ignoring error You must feed a value for placeholder tensor 'image_tensor' with dtype uint8 and shape [?,?,?,3]
	 [[{{node image_tensor}}]]
Traceback (most recent call last):
  File "/home/user/iwork/AI/Mace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 404, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/user/iwork/AI/Mace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 210, in main
    option, FLAGS.model_file)
  File "/home/user/iwork/AI/Mace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 308, in __init__
    self.update_output_shapes(session)
  File "/home/user/iwork/AI/Mace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 376, in update_output_shapes
    feed_dict=self._placeholders)
  File "/home/user/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/user/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/user/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/user/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: node Postprocessor/BatchMultiClassNonMaxSuppression/map/while/Merge (defined at /home/user/iwork/AI/Mace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py:306)  has inputs from different frames. The input node Postprocessor/BatchMultiClassNonMaxSuppression/map/while/NextIteration (defined at /home/user/iwork/AI/Mace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py:306)  is in frame ''. The input node Postprocessor/BatchMultiClassNonMaxSuppression/map/while/Enter (defined at /home/user/iwork/AI/Mace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py:306)  is in frame 'Postprocessor/BatchMultiClassNonMaxSuppression/map/while/while_context'.
Traceback (most recent call last):
  File "tools/converter.py", line 1317, in <module>
    flags.func(flags)
  File "tools/converter.py", line 824, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 753, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/user/iwork/AI/Mace/mace/tools/sh_commands.py", line 549, in gen_model_code
    _fg=True)
  File "/home/user/.local/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=/home/user/iwork/AI/Mace/test/ssd_mobilenet_v1_coco_tf/frozen_inference_graph.pb --weight_file= --model_checksum=0cb4161a6310632814cd25afe11c261cff9a7d55487a813acd54772285b54850 --weight_checksum= --input_node=Preprocessor/sub --input_data_types=float32 --input_data_formats=NHWC --output_node=detection_classes,detection_boxes,detection_scores --output_data_types=float32,float32,float32 --output_data_formats=NHWC,NHWC,NHWC --check_node= --runtime=cpu --template=mace/python/tools --model_tag=ssd_mobilenet_v1_tf --input_shape=1,300,300,3 --input_range= --output_shape=1,1,1,100:1,1,100,4:1,1,1,100 --check_shape= --dsp_mode=0 --embed_model_data=False --winograd=0 --quantize=0 --quantize_range_file= --change_concat_ranges=0 --obfuscate=0 --output_dir=mace/codegen/models/ssd_mobilenet_v1_tf --model_graph_format=file --data_type=fp32_fp32 --graph_optimize_options= --cl_mem_type=image

  STDOUT:


  STDERR:
```

### Additional context
请教一下以上错误是什么原因，如何解决？
谢谢！

**Comment by lydoc** [comment]
该模型Postprocess部分包含很多逻辑运算的op，mace不支持，可以选择使用ClassPredictor和BoxEncodingPredictor作为output，然后得到计算结果后在mace外面写后处理的部分。
