### ISSUE TITLE
转换yushiqi人脸检测caffe模型不成功

### ISSUE THREAD

**Issue by ABlueLight** [XiaoMi/mace#445]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
mace docker-dev-lite

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
Transform model to one that can better run on device
Remove layer data (AnnotatedData)
Remove layer mbox_loss (MultiBoxLoss)
Traceback (most recent call last):
  File "/mnt/mace_new/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 422, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/mnt/mace_new/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 228, in main
    output_graph_def = converter.run()
  File "/mnt/mace_new/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/caffe_converter.py", line 221, in run
    self.convert_ops()
  File "/mnt/mace_new/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/caffe_converter.py", line 342, in convert_ops
    % layer.type)
  File "/mnt/mace_new/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/convert_util.py", line 20, in mace_check
    raise Exception(msg)
Exception: Mace does not support caffe op type Normalize yet
Traceback (most recent call last):
  File "tools/converter.py", line 1353, in <module>
    flags.func(flags)
  File "tools/converter.py", line 851, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 780, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/mnt/mace_new/tools/sh_commands.py", line 551, in gen_model_code
    _fg=True)
  File "/root/.pyenv/versions/2.7.14/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /root/.pyenv/versions/2.7.14/bin/python bazel-bin/mace/python/tools/converter -u --platform=caffe --model_file=/mnt/libfacedetection/libface.prototxt --weight_file=/mnt/libfacedetection/libface.caffemodel --model_checksum=ddc8224f6cc3ad16adb2aba40c9fc9d01a8ac2a5255fdd272cc275a0bd642907 --weight_checksum=645cbf7b4534383ba1ccd9573849c4be5a2ca25a354cae0c4242772093e8b5d5 --input_node=data --input_data_types=float32 --input_data_formats=NHWC --output_node=mbox_loc,mbox_conf_flatten,mbox_priorbox --output_data_types=float32,float32,float32 --output_data_formats=NHWC,NHWC,NHWC --check_node= --runtime=cpu --template=mace/python/tools --model_tag=libface --input_shape=1,240,320,3 --input_range= --output_shape=1,7668:1,40257:1,2,7668 --check_shape= --dsp_mode=0 --embed_model_data=False --winograd=0 --quantize=0 --quantize_large_weights=0 --quantize_range_file= --change_concat_ranges=0 --obfuscate=0 --output_dir=mace/codegen/models/libface --model_graph_format=file --data_type=fp32_fp32 --graph_optimize_options= --cl_mem_type=image

  STDOUT:


  STDERR:

```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lee-bin** [comment]
Duplicated with #350
