### ISSUE TITLE
Error on converting mobilenet ssd model

### ISSUE THREAD

**Issue by alexst07** [XiaoMi/mace#447]
### System information
- OS Platform and Distribution: Linux Ubuntu 16.04
- NDK version: 19c
- GCC version: 5.4.0
- MACE version: v0.10.0
- Python version: 2.7
- Bazel version: 0.13.0

### Model deploy file (*.yml)
```yaml
library_name: mobilenet-ssd
target_abis: [arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  mobilenet_v1: # model tag, which will be used in model loading and must be specific.
    platform: tensorflow
    # path to your tensorflow model's pb file. Support local path, http:// and https://
    model_file_path: /workspace/model/frozen_inference_graph.pb
    # sha256_checksum of your model's pb file.
    # use this command to get the sha256_checksum: sha256sum path/to/your/pb/file
    model_sha256_checksum: 74c6e4d38e2fb30f09d487160a41141c2625a435179b00e26df2ee543fac04bc
    # define your model's interface
    subgraphs:
      - input_tensors:
          - image_tensor
        input_shapes:
          - 1,300,300,3
        output_tensors:
          - detection_boxes
          - detection_classes
          - detection_scores
        output_shapes:
          - 1, 100, 4
          - 1, 100
          - 1, 100
    # cpu, gpu or cpu+gpu
    runtime: cpu+gpu
    winograd: 0
```

### Describe the problem
NodeDef mentions attr 'Truncate' not in Op.

### To Reproduce

```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config=/workspace/model/mobile-net-ssd.yml
```

### Error information / logs

```bash
Traceback (most recent call last):
  File "/root/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 414, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/root/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 213, in main
    option, FLAGS.model_file)
  File "/root/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 309, in __init__
    tf.import_graph_def(transformed_graph_def, name='')
  File "/root/.pyenv/versions/2.7.12/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/root/.pyenv/versions/2.7.12/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 493, in import_graph_def
    raise ValueError(str(e))
ValueError: NodeDef mentions attr 'Truncate' not in Op<name=Cast; signature=x:SrcT -> y:DstT; attr=SrcT:type; attr=DstT:type>; NodeDef: ToFloat = Cast[DstT=DT_FLOAT, SrcT=DT_UINT8, Truncate=false](image_tensor). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
Traceback (most recent call last):
  File "tools/converter.py", line 1346, in <module>
    flags.func(flags)
  File "tools/converter.py", line 853, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 782, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/root/mace/tools/sh_commands.py", line 549, in gen_model_code
    _fg=True)
  File "/root/.pyenv/versions/2.7.12/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 
```

**Comment by lu229** [comment]
This error occured when call the tensorflow's import_graph_def function: tf.import_graph_def(transformed_graph_def, name='').
It seems that the model is invalid? can you load the model in tensorflow successfuly?

**Comment by lu229** [comment]
@alexst07 by the way, the output_shapes in yml should not have whitespaces.

**Comment by alexst07** [comment]
@lu229 Yes, I can. In fact all models that I am trying can be found here: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md 
These are models from oficial tensorflow repositroy.

**Comment by lydoc** [comment]
The Postprocess of this model include some logical operations which mace does not support. You can use ClassPredictor and BoxEncodingPredictor as output nodes.
