### ISSUE TITLE
converter.py run my own models aborted on XiaoMI 8 device

### ISSUE THREAD

**Issue by valwang** [XiaoMi/mace#454]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **NDK version(e.g., 15c)**: 18b
- **GCC version(if compiling for host, e.g., 5.4.0)**: 7.4.0
- **MACE version (Use the command: git describe --long --tags)**: v0.11.0-rc0-0-g2d650b67
- **Python version(2.7)**: 2.7
- **Bazel version (e.g., 0.13.0)**: 0.13.1

### Model deploy file (*.yml)
```
library_name: my_model
target_abis: [armeabi-v7a, arm64-v8a]
model_graph_format: file
model_data_format: file
models:
  mobilenet_v2:
    platform: tensorflow
    model_file_path: /home/valwang/project/mace-models/my_model/my_model.pb
    model_sha256_checksum: c3bdfd44b526673474858bdbb76aba58ab217db8b6a854e1a1836f268a0d6a97
    subgraphs:
      - input_tensors:
          - batch_normalization_1_input
        input_shapes:
          - 1,352,15,1
        output_tensors:
          - dense_1/Sigmoid
        output_shapes:
          - 1,88
        validation_inputs_data:
          - /home/valwang/project/mace-models/my_model/spec_txt.npy
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
......
```

### Describe the problem
converter.py run aborted on XiaoMI 8 device. Please help to identify the possible reasons and suggest the corrections. Thanks!

### To Reproduce
Steps to reproduce the problem:
```
1. cd /path/to/mace
2. python tools/converter.py run --config=/home/valwang/project/mace-models/my_model/my_model.yml --round=100
```

### Error information / logs
Please include the **full** log and/or traceback here.
```
python tools/converter.py run --config=/home/valwang/project/mace-models/my_model/my_model.yml --round=100
tools/converter.py:242: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  configs = yaml.load(f)
* Build //mace/tools/validation:mace_run_static with ABI armeabi-v7a
WARNING: The major revision of the Android NDK referenced by android_ndk_repository rule 'androidndk' is 18. The major revisions supported by Bazel are [10, 11, 12, 13, 14, 15, 16]. Bazel will attempt to treat the NDK as if it was r16. This may cause compilation and linkage problems. Please download a supported NDK version.
INFO: Analysed target //mace/tools/validation:mace_run_static (0 packages loaded).
INFO: Found 1 target...
Target //mace/tools/validation:mace_run_static up-to-date:
  bazel-bin/mace/tools/validation/mace_run_static
INFO: Elapsed time: 0.331s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
Build done!

*************************************************
          Run model mobilenet_v2 on MI8          
*************************************************

* Run 'mobilenet_v2' with round=100, restart_round=1, tuning=False, out_of_range_check=False, omp_num_threads=(-1,), cpu_affinity_policy=(1,), gpu_perf_hint=(3,), gpu_priority_hint=(3,)
Push builds/my_model/_tmp/mobilenet_v2/fff6d47355c5ae993ab15638fe6dedb2/MI8_sdm845/armeabi-v7a/model_input_batch_normalization_1_input to /data/local/tmp/mace_run
Push builds/my_model/model/mobilenet_v2.data to /data/local/tmp/mace_run
Push builds/my_model/model/mobilenet_v2.pb to /data/local/tmp/mace_run/mobilenet_v2.pb
Push builds/my_model/_tmp/armeabi-v7a/mace_run_static to /data/local/tmp/mace_run
Push /tmp/cmd_file-mobilenet_v2-1559487566.18 to /data/local/tmp/mace_run/cmd_file-mobilenet_v2-1559487566.18
Aborted
Traceback (most recent call last):
  File "tools/converter.py", line 1346, in <module>
    flags.func(flags)
  File "tools/converter.py", line 1031, in run_mace
    device.run_specify_abi(flags, configs, target_abi)
  File "/home/valwang/project/mace/tools/device.py", line 714, in run_specify_abi
    output_config, runtime, tuning)
  File "/home/valwang/project/mace/tools/device.py", line 556, in run_model
    YAMLKeyword.model_file_path]
  File "/home/valwang/project/mace/tools/device.py", line 355, in tuning_run
    _err_to_out=True)
  File "/home/valwang/project/mace/tools/device.py", line 73, in exec_command
    sh.adb('-s', self.address, 'shell', command, *args, **kwargs)
  File "/home/valwang/.local/lib/python2.7/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/home/valwang/.local/lib/python2.7/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/home/valwang/.local/lib/python2.7/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/valwang/.local/lib/python2.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_134: 

  RAN: /home/valwang/Android/Sdk/platform-tools/adb -s dd032b6c shell sh /data/local/tmp/mace_run/cmd_file-mobilenet_v2-1559487566.18

  STDOUT:


  STDERR:

```
I tried to run the printed out shell command on device
sh /data/local/tmp/mace_run/cmd_file-mobilenet_v2-1559487566.18
and get following printout:
```
dipper:/ $ sh /data/local/tmp/mace_run/cmd_file-mobilenet_v2-1559487566.18
I mace/tools/validation/mace_run.cc:451] model name: mobilenet_v2
I mace/tools/validation/mace_run.cc:452] mace version: v0.11.0-rc0-0-g2d650b67
I mace/tools/validation/mace_run.cc:453] input node: batch_normalization_1_input
I mace/tools/validation/mace_run.cc:454] input shape: 1,352,15,1
I mace/tools/validation/mace_run.cc:455] output node: dense_1/Sigmoid
I mace/tools/validation/mace_run.cc:456] output shape: 1,88
I mace/tools/validation/mace_run.cc:457] input_file: /data/local/tmp/mace_run/model_input
I mace/tools/validation/mace_run.cc:458] output_file: /data/local/tmp/mace_run/model_out
I mace/tools/validation/mace_run.cc:459] model_data_file: /data/local/tmp/mace_run/mobilenet_v2.data
I mace/tools/validation/mace_run.cc:460] model_file: /data/local/tmp/mace_run/mobilenet_v2.pb
I mace/tools/validation/mace_run.cc:461] device: CPU
I mace/tools/validation/mace_run.cc:462] round: 100
I mace/tools/validation/mace_run.cc:463] restart_round: 1
I mace/tools/validation/mace_run.cc:464] gpu_perf_hint: 3
I mace/tools/validation/mace_run.cc:465] gpu_priority_hint: 3
I mace/tools/validation/mace_run.cc:466] omp_num_threads: -1
I mace/tools/validation/mace_run.cc:467] cpu_affinity_policy: 1
I mace/libmace/mace.cc:431] Creating MaceEngine, MACE version: v0.11.0-rc0-0-g2d650b67
I mace/libmace/mace.cc:470] Initializing MaceEngine
I mace/libmace/mace.cc:603] Destroying MaceEngine
I mace/tools/validation/mace_run.cc:508] restart round 0
I mace/libmace/mace.cc:876] Create MaceEngine from model graph proto and weights data
I mace/libmace/mace.cc:431] Creating MaceEngine, MACE version: v0.11.0-rc0-0-g2d650b67
I mace/libmace/mace.cc:470] Initializing MaceEngine
F mace/core/operator.cc:324] Key not registered: Reduce0T_DT_INT32
F mace/core/operator.cc:324] backtrace:
F mace/core/operator.cc:324]  pc 0xaf04054a 
F mace/core/operator.cc:324]  pc 0xaf042690 
F mace/core/operator.cc:324]  pc 0xaf04264c 
F mace/core/operator.cc:324]  pc 0xaf042902 
F mace/core/operator.cc:324]  pc 0xaf042a46 
F mace/core/operator.cc:324]  pc 0xaf017fb2 
F mace/core/operator.cc:324]  pc 0xaf008c24 
F mace/core/operator.cc:324]  pc 0xaef0fd00 
F mace/core/operator.cc:324]  pc 0xaef13f1a 
F mace/core/operator.cc:324]  pc 0xaeef9e12 
F mace/core/operator.cc:324]  pc 0xaeefc2e6 
F mace/core/operator.cc:324]  pc 0xaeefc7bc 
F mace/core/operator.cc:324]  pc 0xf391b15e __libc_init
Aborted 
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by TonyMou** [comment]
Your model has a Reduce Op with int32 type which is not supported yet in MACE. Which type of reduce op are you using, reduce mean?

**Comment by valwang** [comment]
I did not use reduce directly. My tensorflow model was converted from one Keras model. In Keras, Flatten() is used, and according to graph summary, it seems Reduce OP is converted:  
  80    flatten_1/Prod    Reduce

**Comment by TonyMou** [comment]
@valwang Could you paste your model and configure file here? We'll look into it.

**Comment by tian9246** [comment]
Use Reshape instead Flatten in keras , do not  calculate dynamically

**Comment by lee-bin** [comment]
Feel free to reopen if the issue is still there.
