### ISSUE TITLE
cannot convert model for dsp

### ISSUE THREAD

**Issue by yangfei963158659** [XiaoMi/mace#479]
Hi,I cannot convert deeplabv3 model for dsp.Error info is following:
INFO: Analysed target //mace/python/tools:converter (0 packages loaded).
INFO: Found 1 target...
Target //mace/python/tools:converter up-to-date:
  bazel-bin/mace/python/tools/converter
INFO: Elapsed time: 1.580s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

Transform model to one that can better run on device
Run transform_graph: ['strip_unused_nodes', 'remove_nodes(op=Identity, op=CheckNumerics)', 'fold_constants(ignore_errors=true)', 'fold_batch_norms', 'fold_old_batch_norms', 'remove_control_dependencies', 'strip_unused_nodes', 'sort_by_execution_order']
('output keys: ', ['SemanticPredictions:0'])
Traceback (most recent call last):
  File "/home/yangfei/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 414, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/yangfei/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 227, in main
    output_graph_def = converter.run()
  File "/home/yangfei/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 324, in run
    self.convert_ops(session)
  File "/home/yangfei/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 388, in convert_ops
    self._op_converters[tf_op.type](tf_op)
  File "/home/yangfei/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 860, in convert_squeeze
    op = self.convert_general_op(tf_op)
  File "/home/yangfei/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 457, in convert_general_op
    mace_check(False, "data type %s not supported" % dtype)
  File "/home/yangfei/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/convert_util.py", line 20, in mace_check
    raise Exception(msg)
Exception: data type <dtype: 'uint8'> not supported
Traceback (most recent call last):
  File "tools/converter.py", line 1346, in <module>
    flags.func(flags)
  File "tools/converter.py", line 853, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 782, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/yangfei/mace/tools/sh_commands.py", line 549, in gen_model_code
    _fg=True)
  File "/home/yangfei/.local/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=mace-models/deeplab-v3/deeplabv3/frozen_inference_graph.pb --weight_file= --model_checksum=b3b7c39d1010c6da1dd0e87973ca24a78fa7dc70d4136fbcf50b9585469b6d9a --weight_checksum= --input_node=ImageTensor:0 --input_data_types=float32 --input_data_formats=NHWC --output_node=SemanticPredictions:0 --output_data_types=float32 --output_data_formats=NHWC --check_node= --runtime=dsp --template=mace/python/tools --model_tag=deeplab_v3 --input_shape=1,513,513,3 --input_range=-1.0,1.0 --output_shape=1,513,513,1 --check_shape= --dsp_mode=0 --embed_model_data=False --winograd=0 --quantize=1 --quantize_range_file= --change_concat_ranges=0 --obfuscate=0 --output_dir=mace/codegen/models/deeplab_v3 --model_graph_format=file --data_type=uint8 --graph_optimize_options= --cl_mem_type=image

  STDOUT:

  STDERR:

Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lu229** [comment]
@yangfei963158659 Is your model a quantitative model?  Please reference: [Quantization](https://mace.readthedocs.io/en/latest/user_guide/quantization_usage.html#quantization)
