### ISSUE TITLE
Failed to convert model using squeeze excitation layer

### ISSUE THREAD

**Issue by netong** [XiaoMi/mace#489]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **NDK version(e.g., 15c)**:
r17c
- **GCC version(if compiling for host, e.g., 5.4.0)**:
5.4.0
- **MACE version (Use the command: git describe --long --tags)**:
v0.10.0-82-g19bf36b
- **Python version(2.7)**: 
2.7
- **Bazel version (e.g., 0.13.0)**:
0.13.0

### Model deploy file (*.yml)
```yaml
library_name: personlab
target_abis: [arm64-v8a]
model_graph_format: code
model_data_format: code
models:
    personlab:
        platform: tensorflow
        model_file_path: /root/mace/mace/examples/android/personlab_opt.pb
        model_sha256_checksum: f170310901719ed7cf26ecbf01511573221989a708adf374e6014a905da5fc35
        subgraphs:
            - input_tensors:
                - MobilenetV1/input_1
              input_shapes:
                - 1,224,224,3
              output_tensors:
                - tower0/Top/kp_maps/Sigmoid
                - tower0/Top/short_offsets/BiasAdd
                - tower0/Top/mid_offsets/BiasAdd
              output_shapes:
                - 1,14,14,17
                - 1,14,14,34
                - 1,14,14,72
        runtime: cpu+gpu
        winograd: 2
```

### Describe the problem
When I apply squeeze excitation layer in convolution layer, the following error occurs:
Can't I use squeeze excitation layer in mace?

```code
def relu6(x, name='relu6'):
    return tf.nn.relu6(x, name)

def hard_sigmoid(x, name='hard_sigmoid'):
    with tf.variable_scope(name):
        h_sigmoid = tf.nn.relu6(x + 3) / 6
    return h_sigmoid

def fully_connected_layer(inputs, units, name="fc", activation=None, use_bias=True, reuse=None):
    return tf.layers.dense(inputs, units, activation=activation, use_bias=use_bias,
                           name=name, reuse=False)

def global_avg(inputs, pool_size, strides, padding='valid', name='global_avg'):
    return tf.layers.average_pooling2d(inputs, pool_size, strides,
                                       padding=padding, data_format='channels_last', name=name)

def squeeze_excitation_layer(input, out_dim, ratio, layer_name, is_training=True, reuse=None):
    with tf.variable_scope(layer_name, reuse=reuse):
        squeeze = global_avg(input, pool_size=input.get_shape()[1:-1], strides=1)

        excitation = fully_connected_layer(squeeze, units=out_dim / ratio, name=layer_name + '_excitation1',
                                            reuse=reuse)
        excitation = relu6(excitation)
        excitation = fully_connected_layer(excitation, units=out_dim, name=layer_name + '_excitation2', reuse=reuse)
        excitation = hard_sigmoid(excitation)

        excitation = tf.reshape(excitation, [-1, 1, 1, out_dim])
        scale = input * excitation
        return scale
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs

```error
...
Remove identity: tower0/Top/kp_maps/conv1/squeeze_excitation/kp_maps/conv1/squeeze_excitation_excitation1/Tensordot/transpose(Identity)
Remove identity: tower0/Top/kp_maps/conv1/squeeze_excitation/kp_maps/conv1/squeeze_excitation_excitation2/Tensordot/transpose(Identity)
Remove identity: tower0/Top/kp_maps/conv2/squeeze_excitation/kp_maps/conv2/squeeze_excitation_excitation1/Tensordot/transpose(Identity)
Remove identity: tower0/Top/kp_maps/conv2/squeeze_excitation/kp_maps/conv2/squeeze_excitation_excitation2/Tensordot/transpose(Identity)
Remove identity: tower0/Top/kp_maps/conv3/squeeze_excitation/kp_maps/conv3/squeeze_excitation_excitation1/Tensordot/transpose(Identity)
Remove identity: tower0/Top/kp_maps/conv3/squeeze_excitation/kp_maps/conv3/squeeze_excitation_excitation2/Tensordot/transpose(Identity)
convert reshape and matmul to fc
convert reshape and matmul to fc
convert reshape and matmul to fc
convert reshape and matmul to fc
convert reshape and matmul to fc
Traceback (most recent call last):
  File "/root/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 363, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/root/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 197, in main
    output_graph_def, quantize_activation_info = mace_transformer.run()
  File "/root/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 128, in run
    changed = transformer()
  File "/root/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 1290, in transform_matmul_to_fc
    remove_input_tensor=True)
  File "/root/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 285, in safe_remove_node
    self._model.tensors.remove(const_tensor)
  File "/root/.cache/bazel/_bazel_root/13dfcf819da8ba7ada64e554af6d29e5/execroot/mace/bazel-out/k8-fastbuild/bin/mace/python/tools/converter.runfiles/com_google_protobuf/python/google/protobuf/internal/containers.py", line 401, in remove
    self._values.remove(elem)
ValueError: list.remove(x): x not in list
Traceback (most recent call last):
  File "tools/converter.py", line 1300, in <module>
    flags.func(flags)
  File "tools/converter.py", line 774, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 704, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/root/mace/tools/sh_commands.py", line 532, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python3.5/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=/root/mace/mace/examples/android/personlab_opt.pb --weight_file= --model_checksum=f170310901719ed7cf26ecbf01511573221989a708adf374e6014a905da5fc35 --weight_checksum= --input_node=MobilenetV1/input_1 --input_data_formats=NHWC --output_node=tower0/Top/kp_maps/Sigmoid,tower0/Top/short_offsets/BiasAdd,tower0/Top/mid_offsets/BiasAdd --output_data_formats=NHWC --check_node= --runtime=cpu+gpu --template=mace/python/tools --model_tag=personlab --input_shape=1,224,224,3 --input_range= --output_shape=1,14,14,17:1,14,14,34:1,14,14,72 --check_shape= --dsp_mode=0 --embed_model_data=True --winograd=0 --quantize=0 --quantize_range_file= --change_concat_ranges=0 --obfuscate=0 --output_dir=mace/codegen/models/personlab --model_graph_format=code --data_type=fp16_fp32 --graph_optimize_options= --cl_mem_type=image

  STDOUT:


  STDERR:
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lydoc** [comment]
Is it convenient for you to share this model?

**Comment by netong** [comment]
@lydoc 
Yes, this is model file
[http://54.178.215.65:80/model.zip](url)
