### ISSUE TITLE
Post training quantization出错，用的是官方inceptionv3的例子

### ISSUE THREAD

**Issue by WeixiangXu** [XiaoMi/mace#493]
按照https://mace.readthedocs.io/en/latest/user_guide/quantization_usage.html中post training的方式，到了第四步`python tools/converter.py convert --config ./mace_models/incept3-step4.yml`之后报错，错误信息如下：

Add quantize tensor range
Add default quantize info for input
Input range input: [-1.0, 1.0]
Add default quantize info for ops like Pooling, Softmax
Add mace quantize and dequantize nodes
Traceback (most recent call last):
  File "/home/xuweixiang/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 363, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/xuweixiang/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 197, in main
    output_graph_def, quantize_activation_info = mace_transformer.run()
  File "/home/xuweixiang/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 128, in run
    changed = transformer()
  File "/home/xuweixiang/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 1428, in quantize_nodes
    % (op.name, op.type))
  File "/home/xuweixiang/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/convert_util.py", line 20, in mace_check
    raise Exception(msg)
**Exception: Quantization only support float ops, but get InceptionV3/InceptionV3/Conv2d_1a_3x3/Relu(Conv2D)**
Traceback (most recent call last):
  File "tools/converter.py", line 1268, in <module>
    flags.func(flags)
  File "tools/converter.py", line 761, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 691, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))

**Comment by WeixiangXu** [comment]
另一个问题：mace量化现在只支持tensorflow的预训练模型吗？

**Comment by lee-bin** [comment]
1、MACE采用的是哪个版本？可以用最新master尝试一下。
2、post training的方式应该是支持caffe的，不过没有做过具体尝试。

**Comment by WeixiangXu** [comment]
> 1、MACE采用的是哪个版本？可以用最新master尝试一下。
> 2、post training的方式应该是支持其他框架的，不过没有做过具体尝试。

更新到了最新的MACE版本，在同样的位置出现了同样的问题：
```
Add quantize tensor range
Traceback (most recent call last):
  File "/home/xuweixiang/mace-master/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 422, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/xuweixiang/mace-master/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 231, in main
    output_graph_def, quantize_activation_info = mace_transformer.run()
  File "/home/xuweixiang/mace-master/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 137, in run
    changed = transformer()
  File "/home/xuweixiang/mace-master/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 1808, in add_quantize_tensor_range
    % op)
  File "/home/xuweixiang/mace-master/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/convert_util.py", line 20, in mace_check
    raise Exception(msg)
Exception: input: "InceptionV3/Logits/SpatialSqueeze:0"
input: "InceptionV3/Predictions/Reshape/shape:0"
output: "InceptionV3/Predictions/Reshape:0"
name: "InceptionV3/Predictions/Reshape"
type: "Reshape"
arg {
  name: "T"
  i: 3
}
arg {
  name: "framework_type"
  i: 0
}
arg {
  name: "data_format"
  i: 1
}
output_shape {
  dims: 1
  dims: 1001
}

```

**Comment by lee-bin** [comment]
不是同样位置的问题。
这个问题的意思是Reshape这一层没有统计的min/max信息，可以查看确保一下overall_range文件是否包含所有层的量化统计信息。

**Comment by WeixiangXu** [comment]
mace更新之后，现在把tensorflow也更新到最新，出现和最开始同样的报错：
Add default quantize info for input
Input range input: [-1.0, 1.0]
Add default quantize info for ops like Pooling, Softmax
Add mace quantize and dequantize nodes
Traceback (most recent call last):
  File "/home/xuweixiang/mace-master/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 422, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/xuweixiang/mace-master/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 231, in main
    output_graph_def, quantize_activation_info = mace_transformer.run()
  File "/home/xuweixiang/mace-master/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 137, in run
    changed = transformer()
  File "/home/xuweixiang/mace-master/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/transformer.py", line 1537, in quantize_nodes
    mace_pb2.DataType.Name(data_type_arg.i)))
  File "/home/xuweixiang/mace-master/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/convert_util.py", line 20, in mace_check
    raise Exception(msg)
**Exception: Quantization only support float ops, but get InceptionV3/InceptionV3/Conv2d_1a_3x3/Relu(Conv2D, DT_HALF)**
Traceback (most recent call last):
  File "tools/converter.py", line 1363, in <module>
    flags.func(flags)
  File "tools/converter.py", line 866, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 794, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/xuweixiang/mace-master/tools/sh_commands.py", line 553, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1:

**Comment by WeixiangXu** [comment]
换了其他模型的yml文件，解决。
