### ISSUE TITLE
covert error: TypeError: 'numpy.int32' object is not iterable

### ISSUE THREAD

**Issue by dnnyyq** [XiaoMi/mace#502]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
library_name: model
target_abis: [arm64-v8a]
model_graph_format: code
model_data_format: code
models:
  mobilenet_v3:
    platform: tensorflow
    model_file_path: /home/mace-all/model/mobileNetV3/test.pb
    model_sha256_checksum: 50286e001207af42f47a5993849d34ebfdf8aca6be3807c6682c15b25472ec85
    subgraphs:
      - input_tensors:
        - images
        input_shapes:
          - 1,112,96,3
        output_tensors:
          - linear_conv1x1/bn/FusedBatchNorm
        output_shapes:
          - 1,1,1,512
    runtime: cpu
    limit_opencl_kernel_time: 0
    obfuscate: 0
    winograd: 0

```

### Describe the problem
TypeError: 'numpy.int32' object is not iterable occurs When convert tensorflow model. 

my model is mobilenetv3 (add SGE), the model (not add SGE ) is converted rightly.
Do mace support 5 dimension operation ？

SGE like this:
net = tf.reshape(net, [n, h, w, groups, c // groups])
sge_branch = tf.reduce_mean(net, axis=4, keepdims=True)
sge_branch2 = net * sge_branch
....
mean, variance = tf.nn.moments(sge_branch2, axes=4, keep_dims=True)
sge_branch2 = (sge_branch2 - mean) / tf.sqrt(variance +  1e-5)

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
Transform model to one that can better run on device
Run transform_graph: ['strip_unused_nodes', 'remove_nodes(op=Identity, op=CheckNumerics)', 'fold_constants(ignore_errors=true)', 'fold_batch_norms', 'fold_old_batch_norms', 'remove_control_dependencies', 'strip_unused_nodes', 'sort_by_execution_order']
output keys:  dict_keys(['linear_conv1x1/bn/FusedBatchNorm'])
Traceback (most recent call last):
  File "/home/mace-all/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 422, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/mace-all/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 228, in main
    output_graph_def = converter.run()
  File "/home/mace-all/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 324, in run
    self.convert_ops(session)
  File "/home/mace-all/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 388, in convert_ops
    self._op_converters[tf_op.type](tf_op)
  File "/home/mace-all/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 912, in convert_reduce
    axis_arg.ints.extend(reduce_dims)
  File "/root/.cache/bazel/_bazel_root/884da15311c2d24e40775bea4e865ed1/execroot/mace/bazel-out/k8-fastbuild/bin/mace/python/tools/converter.runfiles/com_google_protobuf/python/google/protobuf/internal/containers.py", line 267, in extend
    elem_seq_iter = iter(elem_seq)
TypeError: 'numpy.int32' object is not iterable
Traceback (most recent call last):
  File "tools/converter.py", line 1363, in <module>
    flags.func(flags)
  File "tools/converter.py", line 866, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 794, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/mace-all/tools/sh_commands.py", line 553, in gen_model_code
    _fg=True)
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /root/.pyenv/versions/3.6.3/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=/home/mace-all/model/mobileNetV3/test.pb --weight_file= --model_checksum=50286e001207af42f47a5993849d34ebfdf8aca6be3807c6682c15b25472ec85 --weight_checksum= --input_node=images --input_data_types=float32 --input_data_formats=NHWC --output_node=linear_conv1x1/bn/FusedBatchNorm --output_data_types=float32 --output_data_formats=NHWC --check_node= --runtime=cpu --template=mace/python/tools --model_tag=mobilenet_v3 --input_shape=1,112,96,3 --input_range= --output_shape=1,1,1,512 --check_shape= --dsp_mode=0 --embed_model_data=True --winograd=0 --quantize=0 --quantize_large_weights=0 --quantize_range_file= --change_concat_ranges=0 --obfuscate=0 --output_dir=mace/codegen/models/mobilenet_v3 --model_graph_format=code --data_type=fp32_fp32 --graph_optimize_options= --cl_mem_type=image

  STDOUT:


  STDERR:
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by liyinhgqw** [comment]
We haven't supported more than 4 dims yet. But we're trying to refactor the code base. After that, it'll be supported.

**Comment by dnnyyq** [comment]
Thank you for response!

 This problem is done by modifying the number to list
sge_branch = tf.reduce_mean(net, axis=4, keepdims=True)--->sge_branch = tf.reduce_mean(net, axis=[4], keepdims=True)
