### ISSUE TITLE
convert.py 转换自己的模型

### ISSUE THREAD

**Issue by suyali** [XiaoMi/mace#510]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

Transform model to one that can better run on device
Traceback (most recent call last):
  File "/home/suyali/deeplearning/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 414, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/suyali/deeplearning/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 218, in main
    FLAGS.weight_file)
  File "/home/suyali/deeplearning/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/caffe_converter.py", line 206, in __init__
    str(f.read()), self._caffe_layers)
  File "/home/suyali/.cache/bazel/_bazel_suyali/844a92ef53127ce8bbb120f256c3d62c/execroot/mace/bazel-out/k8-fastbuild/bin/mace/python/tools/converter.runfiles/com_google_protobuf/python/google/protobuf/text_format.py", line 536, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/suyali/.cache/bazel/_bazel_suyali/844a92ef53127ce8bbb120f256c3d62c/execroot/mace/bazel-out/k8-fastbuild/bin/mace/python/tools/converter.runfiles/com_google_protobuf/python/google/protobuf/text_format.py", line 590, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/suyali/.cache/bazel/_bazel_suyali/844a92ef53127ce8bbb120f256c3d62c/execroot/mace/bazel-out/k8-fastbuild/bin/mace/python/tools/converter.runfiles/com_google_protobuf/python/google/protobuf/text_format.py", line 623, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/suyali/.cache/bazel/_bazel_suyali/844a92ef53127ce8bbb120f256c3d62c/execroot/mace/bazel-out/k8-fastbuild/bin/mace/python/tools/converter.runfiles/com_google_protobuf/python/google/protobuf/text_format.py", line 638, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/suyali/.cache/bazel/_bazel_suyali/844a92ef53127ce8bbb120f256c3d62c/execroot/mace/bazel-out/k8-fastbuild/bin/mace/python/tools/converter.runfiles/com_google_protobuf/python/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/home/suyali/.cache/bazel/_bazel_suyali/844a92ef53127ce8bbb120f256c3d62c/execroot/mace/bazel-out/k8-fastbuild/bin/mace/python/tools/converter.runfiles/com_google_protobuf/python/google/protobuf/text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/suyali/.cache/bazel/_bazel_suyali/844a92ef53127ce8bbb120f256c3d62c/execroot/mace/bazel-out/k8-fastbuild/bin/mace/python/tools/converter.runfiles/com_google_protobuf/python/google/protobuf/text_format.py", line 730, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 965:3 : Message type "caffe.LayerParameter" has no field named "yolov3_detection_output_param".
Traceback (most recent call last):
  File "tools/converter.py", line 1346, in <module>
    flags.func(flags)
  File "tools/converter.py", line 853, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 782, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/suyali/deeplearning/mace/tools/sh_commands.py", line 549, in gen_model_code
    _fg=True)
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

什么原因呢？

**Comment by lu229** [comment]
google.protobuf.text_format.ParseError: 965:3 : Message type "caffe.LayerParameter" has no field named "yolov3_detection_output_param"
=====================================
@suyali ，检查一下caffe的prototxt文件，能用python的protobuf打开吗？
