### ISSUE TITLE
caffe ssd-mobilenet-v1 convert failed

### ISSUE THREAD

**Issue by suyali** [XiaoMi/mace#512]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lydoc** [comment]
Any log？

**Comment by suyali** [comment]
python tools/converter.py convert --config=../mace-models/ssd-mobilenet-v1/ssd-mobilenet-v1_caffe.yml


Traceback (most recent call last):
  File "/home/su/deeplearning/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 414, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/su/deeplearning/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 227, in main
    output_graph_def = converter.run()
  File "/home/su/deeplearning/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/caffe_converter.py", line 225, in run
    shape_inferer.run()
  File "/home/su/deeplearning/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/shape_inference.py", line 72, in run
    self._op_shape_inference[op.type](op)
  File "/home/su/deeplearning/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/shape_inference.py", line 279, in infer_shape_reshape
    self.add_output_shape(op, [output_shape])
  File "/home/su/deeplearning/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/shape_inference.py", line 82, in add_output_shape
    output_shape.dims.extend(shapes[i])
  File "/home/su/.cache/bazel/_bazel_suyali/844a92ef53127ce8bbb120f256c3d62c/execroot/mace/bazel-out/k8-fastbuild/bin/mace/python/tools/converter.runfiles/com_google_protobuf/python/google/protobuf/internal/containers.py", line 275, in extend
    new_values = [self._type_checker.CheckValue(elem) for elem in elem_seq_iter]
  File "/home/su/.cache/bazel/_bazel_suyali/844a92ef53127ce8bbb120f256c3d62c/execroot/mace/bazel-out/k8-fastbuild/bin/mace/python/tools/converter.runfiles/com_google_protobuf/python/google/protobuf/internal/containers.py", line 275, in <listcomp>
    new_values = [self._type_checker.CheckValue(elem) for elem in elem_seq_iter]
  File "/home/su/.cache/bazel/_bazel_suyali/844a92ef53127ce8bbb120f256c3d62c/execroot/mace/bazel-out/k8-fastbuild/bin/mace/python/tools/converter.runfiles/com_google_protobuf/python/google/protobuf/internal/type_checkers.py", line 133, in CheckValue
    raise TypeError(message)
 TypeError: 1917.0 has type <class 'numpy.float64'>, but expected one of: (<class 'int'>,)
Traceback (most recent call last):
  File "tools/converter.py", line 1346, in <module>
    flags.func(flags)
  File "tools/converter.py", line 853, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 782, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/su/deeplearning/mace/tools/sh_commands.py", line 549, in gen_model_code
    _fg=True)
  File "/home/su/anaconda3/lib/python3.5/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1:

**Comment by lydoc** [comment]
it seems you should use an absolute path instead of "--config=../mace-models/ssd-mobilenet-v1/ssd-mobilenet-v1_caffe.yml"

**Comment by suyali** [comment]
ok, I'll try

**Comment by suyali** [comment]
It still got the same error???

**Comment by lydoc** [comment]
Sorry, maybe I got it wrong. "--config=../mace-models/ssd-mobilenet-v1/ssd-mobilenet-v1_caffe.yml" should be right, and which version of mace did you use?

**Comment by suyali** [comment]
the latest

**Comment by lydoc** [comment]
Did you modify the ssd-mobilenet-v1_caffe.yml?

**Comment by suyali** [comment]
No, the yml as follows:

library_name: ssd-mobilenet-v1
target_abis: [armeabi-v7a, arm64-v8a]
model_graph_format: code
model_data_format: code
models:
  ssd_mobilenet_v1:
    platform: caffe
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/ssd-mobilenet-v1/MobileNetSSD_deploy_new.prototxt
    weight_file_path: http://cnbj1.fds.api.xiaomi.com/mace/miai-models/ssd-mobilenet-v1/MobileNetSSD_deploy_new.caffemodel
    model_sha256_checksum: ed517e22400248542814f258c125b0921483170cd7b482a63f1cdae5e36fa636
    weight_sha256_checksum: 761c86fbae3d8361dd454f7c740a964f62975ed32f4324b8b85994edec30f6af
    subgraphs:
      - input_tensors:
          - data
        input_shapes:
          - 1,300,300,3
        output_tensors:
          - mbox_loc
          - mbox_conf_flatten
          - mbox_priorbox
        output_shapes:
          - 1,7668
          - 1,40257
          - 1,2,7668
        validation_inputs_data:
          - https://cnbj1.fds.api.xiaomi.com/mace/inputs/cat300.npy
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    nnlib_graph_mode: 0
    obfuscate: 0
    winograd: 0
    docker_image_tag: ssd
    dockerfile_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/ssd-mobilenet-v1/Dockerfile
    dockerfile_sha256_checksum: 3cdd6c526937cf92f3aad0e6b66cbbe62f3a71f7883af1020b1f3f9267c80f9e

**Comment by suyali** [comment]
hello?

**Comment by lydoc** [comment]
Maybe because of some environmental problems? Which version of your sh? try pip install sh==1.12.14? And could you use file/file instead of code/code?

**Comment by suyali** [comment]
first: the sh version is 1.12.14
sh                        1.12.14                   <pip>

second: I change file\file, got the same error

**Comment by suyali** [comment]
@lydoc

**Comment by yejw5** [comment]
Can you try python2

**Comment by suyali** [comment]
Yes,It works!
thanks
