### ISSUE TITLE
Mace does not support caffe op type DetectionOutput yet

### ISSUE THREAD

**Issue by suyali** [XiaoMi/mace#514]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **NDK version(e.g., 15c)**:
- **GCC version(if compiling for host, e.g., 5.4.0)**:
- **MACE version (Use the command: git describe --long --tags)**:
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Model deploy file (*.yml)
```yaml
......
```

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
LOGs
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.
Transform model to one that can better run on device
Remove layer data (AnnotatedData)
Remove layer mbox_loss (MultiBoxLoss)
Traceback (most recent call last):
  File "/home/suyali/deeplearning/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 414, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/suyali/deeplearning/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 227, in main
    output_graph_def = converter.run()
  File "/home/suyali/deeplearning/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/caffe_converter.py", line 221, in run
    self.convert_ops()
  File "/home/suyali/deeplearning/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/caffe_converter.py", line 342, in convert_ops
    % layer.type)
  File "/home/suyali/deeplearning/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/convert_util.py", line 20, in mace_check
    raise Exception(msg)
Exception: Mace does not support caffe op type DetectionOutput yet
Traceback (most recent call last):
  File "tools/converter.py", line 1346, in <module>
    flags.func(flags)
  File "tools/converter.py", line 853, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 782, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/suyali/deeplearning/mace/tools/sh_commands.py", line 549, in gen_model_code
    _fg=True)
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/suyali/anaconda3/bin/python bazel-bin/mace/python/tools/converter -u --platform=caffe --model_file=/home/suyali/deeplearning/mace/mymodel/pelee_304x304.prototxt --weight_file=/home/suyali/deeplearning/mace/mymodel/pelee_304x304_acc7094.caffemodel --model_checksum=d46b7af07492b54a79847b74651976edd49d9022e6e24dba6ff42a2b88504c98 --weight_checksum=50bd8331c286b9ce98fcd4f271c6315b19c68fd50a697d04a584dc2144a2d5f9 --input_node=data --input_data_types=float32 --input_data_formats=NHWC --output_node=mbox_loc,mbox_conf_flatten --output_data_types=float32,float32 --output_data_formats=NHWC,NHWC --check_node= --runtime=cpu+gpu --template=mace/python/tools --model_tag=pelee_coco_voc_304x304_test --input_shape=1,304,304,3 --input_range= --output_shape=1, 6675:1, 35028 --check_shape= --dsp_mode=0 --embed_model_data=True --winograd=0 --quantize=0 --quantize_range_file= --change_concat_ranges=0 --obfuscate=0 --output_dir=mace/codegen/models/pelee_coco_voc_304x304_test --model_graph_format=code --data_type=fp16_fp32 --graph_optimize_options= --cl_mem_type=image

  STDOUT:

  STDERR:

DetectionOutput

Transform model to one that can better run on device
Remove layer data (AnnotatedData)
Remove layer mbox_loss (MultiBoxLoss)
Traceback (most recent call last):
  File "/home/suyali/deeplearning/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 414, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/suyali/deeplearning/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 227, in main
    output_graph_def = converter.run()
  File "/home/suyali/deeplearning/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/caffe_converter.py", line 221, in run
    self.convert_ops()
  File "/home/suyali/deeplearning/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/caffe_converter.py", line 342, in convert_ops
    % layer.type)
  File "/home/suyali/deeplearning/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/convert_util.py", line 20, in mace_check
    raise Exception(msg)
Exception: Mace does not support caffe op type DetectionOutput yet
Traceback (most recent call last):
  File "tools/converter.py", line 1346, in <module>
    flags.func(flags)
  File "tools/converter.py", line 853, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 782, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/suyali/deeplearning/mace/tools/sh_commands.py", line 549, in gen_model_code
    _fg=True)
  File "/home/suyali/anaconda3/lib/python3.5/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/suyali/anaconda3/bin/python bazel-bin/mace/python/tools/converter -u --platform=caffe --model_file=/home/suyali/deeplearning/mace/mymodel/pelee_304x304.prototxt --weight_file=/home/suyali/deeplearning/mace/mymodel/pelee_304x304_acc7094.caffemodel --model_checksum=d46b7af07492b54a79847b74651976edd49d9022e6e24dba6ff42a2b88504c98 --weight_checksum=50bd8331c286b9ce98fcd4f271c6315b19c68fd50a697d04a584dc2144a2d5f9 --input_node=data --input_data_types=float32 --input_data_formats=NHWC --output_node=mbox_loc,mbox_conf_flatten --output_data_types=float32,float32 --output_data_formats=NHWC,NHWC --check_node= --runtime=cpu+gpu --template=mace/python/tools --model_tag=pelee_coco_voc_304x304_test --input_shape=1,304,304,3 --input_range= --output_shape=1, 6675:1, 35028 --check_shape= --dsp_mode=0 --embed_model_data=True --winograd=0 --quantize=0 --quantize_range_file= --change_concat_ranges=0 --obfuscate=0 --output_dir=mace/codegen/models/pelee_coco_voc_304x304_test --model_graph_format=code --data_type=fp16_fp32 --graph_optimize_options= --cl_mem_type=image

  STDOUT:

  STDERR:

really need help!
thanks!

**Comment by lu229** [comment]
@suyali Yes it is not supported yet, perhaps you can config the outputs as [mbox_loc, mbox_conf_flatten, mbox_priorbox] to avoid this problem, please reference: https://github.com/XiaoMi/mace-models/blob/master/ssd-mobilenet-v1/ssd-mobilenet-v1_caffe.yml

**Comment by suyali** [comment]
Yes, I have tried it, and it works! But when will mace support this layer? or if I want use this layer, what should I do?

**Comment by lydoc** [comment]
You can refer to this: https://github.com/XiaoMi/mace/blob/v0.10.0/mace/utils/detection_output.cc

**Comment by suyali** [comment]
我应该在哪个函数里面应用detection_output.cc呀？@lydoc

**Comment by lydoc** [comment]
@suyali 可以在用MaceEngine得到output之后，参考detection output的实现，自己写一下后处理

**Comment by suyali** [comment]
不好意思，我对整体的架构不是太了解，“用MaceEngine得到output之后”这里的MaceEngine是在哪个地方？

**Comment by suyali** [comment]
@lydoc

**Comment by suyali** [comment]
有相关的运行示例吗? @lydoc

**Comment by lydoc** [comment]
@suyali 我们之后可能会开源一些使用示例，目前你可以参考一下https://github.com/XiaoMi/mace/issues/309#issuecomment-455051042 这个工程写法。

**Comment by suyali** [comment]
ok,thanks
