### ISSUE TITLE
Mace does not support caffe op type DepthwiseConvolution yet

### ISSUE THREAD

**Issue by gasgallo** [XiaoMi/mace#517]
I'm using the provided docker image with MACE v0.10.0

### Model deploy file (*.yml)
```yaml
# The name of library
library_name: mnet
target_abis: [host]
model_graph_format: file
model_data_format: file
models:
  mnet_model: # model tag, which will be used in model loading and must be specific.
    platform: caffe
    model_file_path: /models/mnet.prototxt
    weight_file_path: /models/mnet.caffemodel
    model_sha256_checksum: 60814a424f5195ffe3ad9193dbe5123113603e7fa6f30b1b8266b63f2d72bf24
    weight_sha256_checksum: 09d1e6950af1df233b3d323e9e971a7fa5d391a22ba679252cc6a22d92cdb06a
    subgraphs:
      - input_tensors:
          - data
        input_shapes:
          - 1,3,640,640
        output_tensors:
          - face_rpn_cls_prob_reshape_stride32
          - face_rpn_bbox_pred_stride32
          - face_rpn_landmark_pred_stride32
          - face_rpn_cls_prob_reshape_stride16
          - face_rpn_bbox_pred_stride16
          - face_rpn_landmark_pred_stride16
          - face_rpn_cls_prob_reshape_stride8
          - face_rpn_bbox_pred_stride8
          - face_rpn_landmark_pred_stride8
        output_shapes:
          - 1,4
          - 1,8
          - 1,20
          - 1,4
          - 1,8
          - 1,20
          - 1,4
          - 1,8
          - 1,20
    obfuscate: 0
    runtime: cpu # cpu, gpu or cpu+gpu or dsp
    winograd: 0
```

### Describe the problem
Depthwise convoloution layer isn't recognized as supported even though I know it's supported by MACE.

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
Transform model to one that can better run on device
Traceback (most recent call last):
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 414, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 227, in main
    output_graph_def = converter.run()
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/caffe_converter.py", line 221, in run
    self.convert_ops()
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/caffe_converter.py", line 342, in convert_ops
    % layer.type)
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/convert_util.py", line 20, in mace_check
    raise Exception(msg)
Exception: Mace does not support caffe op type DepthwiseConvolution yet
Traceback (most recent call last):
  File "tools/converter.py", line 1346, in <module>
    flags.func(flags)
  File "tools/converter.py", line 853, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 782, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/mace/tools/sh_commands.py", line 549, in gen_model_code
    _fg=True)
  File "/root/.pyenv/versions/2.7.14/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1:
```

**Comment by lu229** [comment]
@gasgallo There is no DepthwiseConvolution layer in the original caffe. Depthwise can be implemented by using Convolution + group parameter greater than 1, which is supported by Mace.

**Comment by gasgallo** [comment]
@lu229 thanks, indeed I've temporarily fixed the problem by renaming the layer type.

So now I'm wondering why in my prototxt file there are layers of type `DepthwiseConvolution`?

**Comment by lu229** [comment]
@gasgallo perhaps you are using an extend caffe framework like this: https://github.com/farmingyard/caffe-mobilenet

**Comment by gasgallo** [comment]
I guess that's possible, I'm just using a pretrained model, so I cannot tell.

Thanks for the help!
