### ISSUE TITLE
Caffe Crop layer error

### ISSUE THREAD

**Issue by gasgallo** [XiaoMi/mace#518]
I'm using the provided docker image with MACE v0.11.0

### Model deploy file (*.yml)
```yaml
# The name of library
library_name: mnet
target_abis: [host]
model_graph_format: file
model_data_format: file
models:
  mnet_model: # model tag, which will be used in model loading and must be specific.
    platform: caffe
    model_file_path: /models/mnet.prototxt
    weight_file_path: /models/mnet.caffemodel
    model_sha256_checksum: 60814a424f5195ffe3ad9193dbe5123113603e7fa6f30b1b8266b63f2d72bf24
    weight_sha256_checksum: 09d1e6950af1df233b3d323e9e971a7fa5d391a22ba679252cc6a22d92cdb06a
    subgraphs:
      - input_tensors:
          - data
        input_shapes:
          - 1,3,640,640
        output_tensors:
          - face_rpn_cls_prob_reshape_stride32
          - face_rpn_bbox_pred_stride32
          - face_rpn_landmark_pred_stride32
          - face_rpn_cls_prob_reshape_stride16
          - face_rpn_bbox_pred_stride16
          - face_rpn_landmark_pred_stride16
          - face_rpn_cls_prob_reshape_stride8
          - face_rpn_bbox_pred_stride8
          - face_rpn_landmark_pred_stride8
        output_shapes:
          - 1,4
          - 1,8
          - 1,20
          - 1,4
          - 1,8
          - 1,20
          - 1,4
          - 1,8
          - 1,20
    obfuscate: 0
    runtime: cpu # cpu, gpu or cpu+gpu or dsp
    winograd: 0
```

### Describe the problem
Error during conversion of Caffe Crop layer. My `prototxt` file doesn't contain any parameter named `axis` or `offset` in the Crop layer.

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
Traceback (most recent call last):
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 414, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 227, in main
    output_graph_def = converter.run()
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/caffe_converter.py", line 222, in run
    self.convert_ops()
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/caffe_converter.py", line 346, in convert_ops
    self._op_converters[layer.type](caffe_op)
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/caffe_converter.py", line 567, in convert_crop
    offset_value[axis:] = param.offset
ValueError: cannot copy sequence with size 0 to array axis with dimension 2
Traceback (most recent call last):
  File "tools/converter.py", line 1346, in <module>
    flags.func(flags)
  File "tools/converter.py", line 853, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 782, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/mace/tools/sh_commands.py", line 549, in gen_model_code
    _fg=True)
  File "/root/.pyenv/versions/2.7.14/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1:
```

**Comment by gasgallo** [comment]
I've currently fixed/bypassed this issue by setting a default value for `offset` parameter (0). So the conversion process doesn't crash anymore.

Is it a flaw of my prototxt file or can we include this fix in MACE?

**Comment by lu229** [comment]
@gasgallo Perhaps it is the prototxt file's flaw, you can reference: [crop.html](https://caffe.berkeleyvision.org/tutorial/layers/crop.html)

**Comment by gasgallo** [comment]
I've noticed that rolling back to MACE v0.10.0 solves the issue because the `convert_crop` method takes into consideration the absence of `offset` parameter.

**Comment by lu229** [comment]
@gasgallo Thanks for your reply, I'm sorry I made a mistake, it is really the Mace's problem, I'll fix this problem and provide a temp patch for you.

**Comment by lu229** [comment]
@gasgallo Thanks for your reply, I'm sorry I made a mistake, it is really the Mace's problem, would you like to provide a fix for Mace? If it's not convenient, I'll fix the problem and provide a temporary patch for you.

**Comment by gasgallo** [comment]
@lu229 Sure, I can take care of it. I'll create a PR asap

**Comment by lu229** [comment]
@gasgallo OK, Thank you~

**Comment by gasgallo** [comment]
@lu229 I've submitted [pr512](https://github.com/XiaoMi/mace/pull/521)

**Comment by lu229** [comment]
@gasgallo Thank you, perhaps it is better to modify code based on the current version instead of roll back to 0.10.0, I have commented on the commit.

**Comment by gasgallo** [comment]
@lu229 it should be fine now

**Comment by lu229** [comment]
@gasgallo Yes, thank you, can you merge the two commits to one?

**Comment by gasgallo** [comment]
@lu229 Done

**Comment by lu229** [comment]
@gasgallo I have asked @TonyMou to merge the commit, Thank you!
