### ISSUE TITLE
DSP benchmark scripts forget to push libhexagon_controller.so

### ISSUE THREAD

**Issue by samsun639** [XiaoMi/mace#56]
**This command runs well:**
python tools/converter.py run --config mace-models/inception-v3/inception-v3-dsp.yml        //pass

**This command run failed , error message as below:**
python tools/converter.py benchmark --config mace-models/inception-v3/inception-v3-dsp.yml    //fail

CANNOT LINK EXECUTABLE "/data/local/tmp/mace_run/benchmark_model_static": library "libhexagon_controller.so" not found
Aborted 
Traceback (most recent call last):
  File "tools/converter.py", line 1376, in <module>
    flags.func(flags)
  File "tools/converter.py", line 1221, in benchmark_model
    target_soc, serial_num)
  File "tools/converter.py", line 1198, in bm_specific_target
    linkshared=linkshared)
  File "/local/mnt/mace/tools/sh_commands.py", line 1302, in benchmark_model
    _fg=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_134: 

  RAN: /usr/bin/adb -s c249ac33 shell sh /data/local/tmp/mace_run/cmd_file-inception_v3_dsp-1531204162.26

  STDOUT:

  STDERR:

**Comment by nolanliou** [comment]
`benchmark` does not support dsp. you could use `run` to test model run time.
