### ISSUE TITLE
Exception: Mace does not support onnx op type ReduceL2 yet

### ISSUE THREAD

**Issue by VirginianBlue** [XiaoMi/mace#565]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **NDK version(e.g., 15c)**:15c
- **GCC version(if compiling for host, e.g., 5.4.0)**: 5.4.0
- **MACE version (Use the command: git describe --long --tags)**:v0.11.0
- **Python version(2.7)**: 2.7
- **Bazel version (e.g., 0.13.0)**:0.13.0

### Model deploy file (*.yml)
```yaml
......
```

### Describe the problem
报错：Exception: Mace does not support onnx op type ReduceL2 yet

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=/path/to/your/model_deployment_file
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
---------------------------------------------------
                Common Configuration               
---------------------------------------------------
|        key        |            value            |
===================================================
|       library_name|                        model|
---------------------------------------------------
|        target_abis| ['armeabi-v7a', 'arm64-v8a']|
---------------------------------------------------
|        target_socs|                           []|
---------------------------------------------------
| model_graph_format|                         file|
---------------------------------------------------
|  model_data_format|                         file|
---------------------------------------------------

***************************************
          Convert model model          
***************************************

INFO: Analysed target //mace/python/tools:converter (0 packages loaded).
INFO: Found 1 target...
Target //mace/python/tools:converter up-to-date:
  bazel-bin/mace/python/tools/converter
INFO: Elapsed time: 0.278s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

Transform model to one that can better run on device
('onnx model IR version: ', 4L)
('constains ops domain: ', u'', 'version:', 9L)
Traceback (most recent call last):
  File "/home/clw/clw/mace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 422, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/clw/clw/mace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 228, in main
    output_graph_def = converter.run()
  File "/home/clw/clw/mace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/onnx_converter.py", line 459, in run
    self.convert_ops(graph_def)
  File "/home/clw/clw/mace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/onnx_converter.py", line 541, in convert_ops
    % node.op_type)
  File "/home/clw/clw/mace/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/convert_util.py", line 20, in mace_check
    raise Exception(msg)
Exception: Mace does not support onnx op type ReduceL2 yet
Traceback (most recent call last):
  File "tools/converter.py", line 1363, in <module>
    flags.func(flags)
  File "tools/converter.py", line 866, in convert_func
    convert_model(configs, flags.cl_mem_type)
  File "tools/converter.py", line 794, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/clw/clw/mace/mace/tools/sh_commands.py", line 553, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=onnx --model_file=/home/clw/clw/mace/superPoint/super_point.onnx --weight_file= --model_checksum=e12d0989a4ce3a04dd924ecedb6535612fe69d0145105009f70b08a03c34133c --weight_checksum= --input_node=0 --input_data_types=float32 --input_data_formats=NHWC --output_node=46,52 --output_data_types=float32,float32 --output_data_formats=NHWC,NHWC --check_node= --runtime=cpu+gpu --template=mace/python/tools --model_tag=model --input_shape=1,120,160,1 --input_range= --output_shape=1,15,20,65:1,15,20,256 --check_shape= --dsp_mode=0 --embed_model_data=False --winograd=0 --quantize=0 --quantize_large_weights=0 --quantize_range_file= --change_concat_ranges=0 --obfuscate=1 --output_dir=mace/codegen/models/model --model_graph_format=file --data_type=fp16_fp32 --graph_optimize_options= --cl_mem_type=image

  STDOUT:


  STDERR:


```

### Additional context
经查询网络结构，报错不支持的模块对应为torch.norm，请问对于该问题如何解决?是否只能修改原网络结构，替换不支持的网络操作？有没有其他解决方案？

**Comment by lu229** [comment]
@VirginianBlue , 替换掉不支持的OP, 或者自己去开发一个OP, 可参考: [Adding a new Op](https://mace.readthedocs.io/en/latest/development/adding_a_new_op.html#adding-a-new-op)
