### ISSUE TITLE
Fails on mace_run on device - `CXXABI_1.3.9' not found

### ISSUE THREAD

**Issue by pgaston** [XiaoMi/mace#577]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage? yes
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 
  Ubuntu 18.04 laptop, target is Qualcomm 820 w/ Adreno 530, Hexagon DSP
  target is running minimal linux
- **NDK version(e.g., 15c)**: n.a.
- **GCC version(if compiling for host, e.g., 5.4.0)**:  
  gcc version 5.4.0, in mace-dev docker
- **MACE version (Use the command: git describe --long --tags)**: v0.12.0-26-gfc973e7
- **Python version(2.7)**: 2.7.12
- **Bazel version (e.g., 0.13.0)**:  n.a.

### Model deploy file (*.yml)
default from tutorial - mobilenet.   shown at end

### Describe the problem
All works great till run_model.py.  It successfully finds and 
downloads multiple times via ssh to the target (Qualcomm 820 at 192.168.1.8)

It gets all the way to mace_run (!!!) but then dies: (full log below)
```
/tmp/mace_run/mobilenet_v1/mace_run: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/mace_run/mobilenet_v1/mace_run)
/tmp/mace_run/mobilenet_v1/mace_run: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /tmp/mace_run/mobilenet_v1/mace_run)
/tmp/mace_run/mobilenet_v1/mace_run: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/mace_run/mobilenet_v1/mace_run)
```
The key parts of the device.yml file are: (full contents below)
```
    target_abis: [aarch64]
  # device soc - https://en.wikipedia.org/wiki/List_of_Qualcomm_Snapdragon_systems-on-chip#Snapdragon_820_and_821_(2016)
    target_socs: [MSM8996]
  # not sure of this
    models: Qualcomm 820
    address: 192.168.8.1
    username: root
```
So close!

### To Reproduce
Steps to reproduce the problem:  Following tutorial instructions.
Invoked with (inside mace-dev docker environment)
```
python tools/python/run_model.py  \
    --config ../mace-models/mobilenet-v1/mobilenet-v1.yml \
    --validate \
    --target_abi aarch64-linux-gnu \
    --target_socs root@192.168.8.1 \
    --device_conf ../mace-models/820.yml
```

### Error information / logs
Please include the **full** log and/or traceback here.
```
python tools/python/run_model.py  \
    --config ../mace-models/mobilenet-v1/mobilenet-v1.yml \
    --validate \
    --target_abi aarch64-linux-gnu \
    --target_socs root@192.168.8.1 \
    --device_conf ../mace-models/820.yml
CMD> bazel version
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Build label: 0.16.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jul 31 17:01:24 2018 (1533056484)
Build timestamp: 1533056484
Build timestamp as int: 1533056484

CMD> bazel build //mace/proto:mace_py
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Loading:
Loading: 0 packages loaded
Analyzing: target //mace/proto:mace_py (12 packages loaded)
INFO: Analysed target //mace/proto:mace_py (17 packages loaded).
INFO: Found 1 target...
[1 / 26] [-----] BazelWorkspaceStatusAction stable-status.txt
Target //mace/proto:mace_py up-to-date:
bazel-genfiles/mace/proto/mace_pb2.py
INFO: Elapsed time: 1.825s, Critical Path: 0.07s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action

CMD> cp -f bazel-genfiles/mace/proto/mace_pb2.py /container/path/mace/tools/python/py_proto

CMD> bazel build //third_party/caffe:caffe_py
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Loading:
Loading: 0 packages loaded
Analyzing: target //third_party/caffe:caffe_py (12 packages loaded)
INFO: Analysed target //third_party/caffe:caffe_py (17 packages loaded).
INFO: Found 1 target...
[0 / 22] [-----] BazelWorkspaceStatusAction stable-status.txt
Target //third_party/caffe:caffe_py up-to-date:
bazel-genfiles/third_party/caffe/caffe_pb2.py
INFO: Elapsed time: 1.878s, Critical Path: 0.08s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action

CMD> cp -f bazel-genfiles/third_party/caffe/caffe_pb2.py /container/path/mace/tools/python/py_proto

!!! {'Snap820': {'target_abis': ['aarch64', 'armv7a'], 'models': 'Qualcomm 820', 'username': 'root', 'target_socs': ['MSM8996'], 'address': '192.168.8.1'}}
tools/python/run_model.py:76: Run on devices: ['root@192.168.8.1']
tools/python/run_model.py:88: Run model mobilenet_v1
{'model_sha256_checksum': '71b10f540ece33c49a7b51f5d4095fc9bd78ce46ebf0300487b2ee23d71294e6', 'output_shapes': ['1,1001'], 'output_tensors': ['MobilenetV1/Predictions/Reshape_1'], 'input_tensors': ['input'], 'input_shapes': ['1,224,224,3'], 'platform': 'tensorflow', 'model_file_path': 'https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v1/mobilenet-v1-1.0.pb', 'runtime': 'gpu'}
{'output_data_types': [1], 'model_sha256_checksum': '71b10f540ece33c49a7b51f5d4095fc9bd78ce46ebf0300487b2ee23d71294e6', 'data_type': 3, 'input_ranges': [[-1.0, 1.0]], 'input_data_formats': [<DataFormat.NHWC: 1>], 'output_shapes': [[1, 1001]], 'output_tensors': ['MobilenetV1/Predictions/Reshape_1'], 'input_tensors': ['input'], 'input_shapes': [[1, 224, 224, 3]], 'platform': <Platform.TENSORFLOW: 0>, 'output_data_formats': [<DataFormat.NHWC: 1>], 'model_file_path': 'https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v1/mobilenet-v1-1.0.pb', 'input_data_types': [1], 'runtime': <DeviceType.GPU: 2>}
CMD> ssh root@192.168.8.1 mkdir -p /tmp/mace_run/mobilenet_v1/interior

CMD> ssh root@192.168.8.1 mkdir -p /tmp/mace_run/mobilenet_v1

CMD> scp -r build/mobilenet_v1/model/mobilenet_v1.pb root@192.168.8.1:/tmp/mace_run/mobilenet_v1

CMD> ssh root@192.168.8.1 mkdir -p /tmp/mace_run/mobilenet_v1

CMD> scp -r build/mobilenet_v1/model/mobilenet_v1.data root@192.168.8.1:/tmp/mace_run/mobilenet_v1

tools/python/run_model.py:276: Generate input file: /tmp/tmpUnPTOL/mobilenet_v1_input
CMD> ssh root@192.168.8.1 mkdir -p /tmp/mace_run/mobilenet_v1/validate_in

CMD> scp -r /tmp/tmpUnPTOL root@192.168.8.1:/tmp/mace_run/mobilenet_v1/validate_in

CMD> ssh root@192.168.8.1 mkdir -p /tmp/mace_run/mobilenet_v1/validate_out

 MACE_INTERNAL_STORAGE_PATH=/tmp/mace_run/mobilenet_v1/interior build/cmake-build/aarch64-linux-gnu/install/bin/mace_run --device=GPU --input_data_format=NHWC --output_node=MobilenetV1/Predictions/Reshape_1 --output_shape=1,1001 --model_data_file=/tmp/mace_run/mobilenet_v1/mobilenet_v1.data --input_node=input --model_file=/tmp/mace_run/mobilenet_v1/mobilenet_v1.pb --model_name=mobilenet_v1 --output_data_format=NHWC --input_shape=1,224,224,3 --input_file=/tmp/mace_run/mobilenet_v1/validate_in/mobilenet_v1 --output_file=/tmp/mace_run/mobilenet_v1/validate_out/mobilenet_v1
!!! {'Snap820': {'target_abis': ['aarch64', 'armv7a'], 'models': 'Qualcomm 820', 'username': 'root', 'target_socs': ['MSM8996'], 'address': '192.168.8.1'}}
Run on devices: ['root@192.168.8.1']
Install target from build/cmake-build/aarch64-linux-gnu/install/bin/mace_run to /tmp/mace_run/mobilenet_v1
CMD> ssh root@192.168.8.1 mkdir -p /tmp/mace_run/mobilenet_v1

CMD> scp -r build/cmake-build/aarch64-linux-gnu/install/bin/mace_run root@192.168.8.1:/tmp/mace_run/mobilenet_v1

['', 'MACE_INTERNAL_STORAGE_PATH=/tmp/mace_run/mobilenet_v1/interior', 'LD_LIBRARY_PATH=/tmp/mace_run/mobilenet_v1', '/tmp/mace_run/mobilenet_v1/mace_run', '--device=GPU', '--input_data_format=NHWC', '--output_node=MobilenetV1/Predictions/Reshape_1', '--output_shape=1,1001', '--model_data_file=/tmp/mace_run/mobilenet_v1/mobilenet_v1.data', '--input_node=input', '--model_file=/tmp/mace_run/mobilenet_v1/mobilenet_v1.pb', '--model_name=mobilenet_v1', '--output_data_format=NHWC', '--input_shape=1,224,224,3', '--input_file=/tmp/mace_run/mobilenet_v1/validate_in/mobilenet_v1', '--output_file=/tmp/mace_run/mobilenet_v1/validate_out/mobilenet_v1']
 MACE_INTERNAL_STORAGE_PATH=/tmp/mace_run/mobilenet_v1/interior LD_LIBRARY_PATH=/tmp/mace_run/mobilenet_v1 /tmp/mace_run/mobilenet_v1/mace_run --device=GPU --input_data_format=NHWC --output_node=MobilenetV1/Predictions/Reshape_1 --output_shape=1,1001 --model_data_file=/tmp/mace_run/mobilenet_v1/mobilenet_v1.data --input_node=input --model_file=/tmp/mace_run/mobilenet_v1/mobilenet_v1.pb --model_name=mobilenet_v1 --output_data_format=NHWC --input_shape=1,224,224,3 --input_file=/tmp/mace_run/mobilenet_v1/validate_in/mobilenet_v1 --output_file=/tmp/mace_run/mobilenet_v1/validate_out/mobilenet_v1
Runing ...
['', 'MACE_INTERNAL_STORAGE_PATH=/tmp/mace_run/mobilenet_v1/interior', 'LD_LIBRARY_PATH=/tmp/mace_run/mobilenet_v1', '/tmp/mace_run/mobilenet_v1/mace_run', '--device=GPU', '--input_data_format=NHWC', '--output_node=MobilenetV1/Predictions/Reshape_1', '--output_shape=1,1001', '--model_data_file=/tmp/mace_run/mobilenet_v1/mobilenet_v1.data', '--input_node=input', '--model_file=/tmp/mace_run/mobilenet_v1/mobilenet_v1.pb', '--model_name=mobilenet_v1', '--output_data_format=NHWC', '--input_shape=1,224,224,3', '--input_file=/tmp/mace_run/mobilenet_v1/validate_in/mobilenet_v1', '--output_file=/tmp/mace_run/mobilenet_v1/validate_out/mobilenet_v1']
CMD> ssh root@192.168.8.1  MACE_INTERNAL_STORAGE_PATH=/tmp/mace_run/mobilenet_v1/interior LD_LIBRARY_PATH=/tmp/mace_run/mobilenet_v1 /tmp/mace_run/mobilenet_v1/mace_run --device=GPU --input_data_format=NHWC --output_node=MobilenetV1/Predictions/Reshape_1 --output_shape=1,1001 --model_data_file=/tmp/mace_run/mobilenet_v1/mobilenet_v1.data --input_node=input --model_file=/tmp/mace_run/mobilenet_v1/mobilenet_v1.pb --model_name=mobilenet_v1 --output_data_format=NHWC --input_shape=1,224,224,3 --input_file=/tmp/mace_run/mobilenet_v1/validate_in/mobilenet_v1 --output_file=/tmp/mace_run/mobilenet_v1/validate_out/mobilenet_v1
/tmp/mace_run/mobilenet_v1/mace_run: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/mace_run/mobilenet_v1/mace_run)
/tmp/mace_run/mobilenet_v1/mace_run: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /tmp/mace_run/mobilenet_v1/mace_run)
/tmp/mace_run/mobilenet_v1/mace_run: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/mace_run/mobilenet_v1/mace_run)

Traceback (most recent call last):
  File "tools/python/run_model.py", line 393, in <module>
    run_models(flags, args)
  File "tools/python/run_model.py", line 80, in run_models
    run_models_for_device(flags, args, dev)
  File "tools/python/run_model.py", line 90, in run_models_for_device
    run_model_for_device(flags, args, dev, name, model_conf)
  File "tools/python/run_model.py", line 216, in run_model_for_device
    device_ids=flags.target_socs)
  File "/container/path/mace/tools/python/run_target.py", line 57, in run_target
    dev.run(device_target)
  File "/container/path/mace/tools/python/utils/device.py", line 265, in run
    execute("ssh %s %s" % (self._device_id, target))
  File "/container/path/mace/tools/python/utils/device.py", line 58, in execute
    raise Exception("errorcode: %s" % p.returncode)
Exception: errorcode: 1
```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.
device.yml (**820.yml**)
```
devices:
  Snap820:
  # opkg returned multiple, list included:
  # ...
  # arch aarch64 16
  # ...
  # arch armv7a-vfp-neon 76
    target_abis: [aarch64]
  # device soc - https://en.wikipedia.org/wiki/List_of_Qualcomm_Snapdragon_systems-on-chip#Snapdragon_820_and_821_(2016)
    target_socs: [MSM8996]
  # not sure of this
    models: Qualcomm 820
    address: 192.168.8.1
    username: root
```
**mobilenet-v1.yml**    (from documentation)
```
models:
  mobilenet_v1:
    platform: tensorflow
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v1/mobilenet-v1-1.0.pb
    model_sha256_checksum: 71b10f540ece33c49a7b51f5d4095fc9bd78ce46ebf0300487b2ee23d71294e6
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,224,224,3
        output_tensors:
          - MobilenetV1/Predictions/Reshape_1
        output_shapes:
          - 1,1001
    runtime: gpu
```

**Comment by pgaston** [comment]
Iterated on multiple target architectures - no love.   Even tried Bazel.   Any help greatly appreciated!!!

This is a Qualcomm 820:
```
~# uname -a
Linux apq8096 3.18.71-perf #1 SMP PREEMPT Wed Jul 10 17:58:49 UTC 2019 aarch64 GNU/Linux
```

Using cmake - used both aarch64-linux-gnu (and arm-linux-gnueabihf) - these seemed to be the only ones that target linux - the rest are android.    I used in my device yml file iterations
```
target_abis: [aarch64]
target_socs: [MSM8996]
```
also tried target_abis: [arm64, armhf] and others...
In all cases ending up with the same error, i.e., 
```
/tmp/mace_run/mobilenet_v1/mace_run: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/mace_run/mobilenet_v1/mace_run)
/tmp/mace_run/mobilenet_v1/mace_run: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /tmp/mace_run/mobilenet_v1/mace_run)
/tmp/mace_run/mobilenet_v1/mace_run: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/mace_run/mobilenet_v1/mace_run)
```
Help!

Thanks - p

**Comment by lu229** [comment]
@pgaston There is no problem with your compilation, it seems that your OS dose not have libstdc++ library, app can't find it on the system, so it can't run. You can install libsdtc++ library on the OS first, for example on Ubuntu:
sudo apt-get install libstdc++6

**Comment by pgaston** [comment]
Thanks.   I did some further investigation.   It seems (this has been seen before) that the mace-dev compiler is gcc 5.4, while the compiler used to build my target is gcc 4.9.     The recommended approach is to back out to gcc 4.9 and re-try.    (And hope for the best!)

**Comment by lu229** [comment]
@pgaston I don't think this is the problem's cause, but wish you good luck all the same~

**Comment by pgaston** [comment]
I'm listening.   Also, yesterday I couldn't get that older compiler to install/run anyway.   (Ubuntu issue I think.)   My current understanding is that the target device has a libstdc++ on it - it's just old.     I can't really do a sudo from there given it's a stripped down linux, but I can figure out some way, like build from source.     Thanks again - hoping that I can get Mace to work!

**Comment by lu229** [comment]
@pgaston Yes you are right, it is possible that the problem is caused by the older libstdc++ library, which I ignored before.
Good luck~

**Comment by pgaston** [comment]
I downloaded a newer aarch64 in debian and moved it to (on target) /usr/lib64.     
https://packages.debian.org/stretch/all/libstdc++6-arm64-cross/download 

mace-run now works.

Other problems, but I'll open a new issue.    Thanks so much for your help here!

**Comment by lu229** [comment]
@pgaston Congratulations~
