### ISSUE TITLE
bug in script: DSP using mace-model mobilenet

### ISSUE THREAD

**Issue by pgaston** [XiaoMi/mace#580]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Platform - Ubuntu 18.04
Docker - mace-dev (full), new image
Target - Qualcomm 820
Kernel: Linux 3.18.71-perf
Architecture: arm64
- **NDK version(e.g., 15c)**: n.a.
- **GCC version(if compiling for host, e.g., 5.4.0)**:
docker - gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
target - gcc (GCC) 4.9.3
- **MACE version (Use the command: git describe --long --tags)**:
v0.12.0-0-ga610d50
- **Python version(2.7)**: 
docker - Python 2.7.12
target - Python 2.7.9
- **Bazel version (e.g., 0.13.0)**:
n.a., but 0.16.0

### Model deploy file (*.yml)
https://github.com/XiaoMi/mace-models/blob/master/mobilenet-v1/mobilenet-v1-quantize-retrain-dsp.yml

### Describe the problem
I attempted to deploy the quantized mobilenet v1 to use the DSP on my 820 target using the given, quantized model.   The run_model.py script failed while downloading  stuff to the target, specifically... (note the dangling colon where there should be a space then the target ip address.)    
```
CMD> scp -r third_party/nnlib/aarch64-linux-gnu/libhexagon_controller.so:/tmp/mace_run/mobilenet_v1_quantize_retrain
usage: scp [-12346BCpqrv] [-c cipher] [-F ssh_config] [-i identity_file]
[-l limit] [-o ssh_option] [-P port] [-S program]
[[user@]host1:]file1 ... [[user@]host2:]file2
Traceback (most recent call last):
...
```
I'm guessing this is a simple bug.

### To Reproduce
Steps to reproduce the problem:
follow normal procedures to build model then run_model

### Error information / logs
Please include the **full** log and/or traceback here.
```
# python tools/python/run_model.py  \
>     --config ../../mace-models/mobilenet-v1/mobilenet-v1-quantize-retrain-dsp.yml \
>     --benchmark \
>     --target_abi aarch64-linux-gnu \
>     --target_socs root@192.168.8.1 \
>     --device_conf ../../mace-models/820.yml
CMD> bazel build //mace/proto:mace_py
WARNING: detected http_proxy set in env, setting no_proxy for localhost.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Loading:
Loading: 0 packages loaded
Analyzing: target //mace/proto:mace_py (12 packages loaded)
INFO: Analysed target //mace/proto:mace_py (17 packages loaded).
INFO: Found 1 target...
[0 / 33] [-----] BazelWorkspaceStatusAction stable-status.txt
Target //mace/proto:mace_py up-to-date:
bazel-genfiles/mace/proto/mace_pb2.py
INFO: Elapsed time: 1.926s, Critical Path: 0.06s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action

CMD> cp -f bazel-genfiles/mace/proto/mace_pb2.py /container/path/mace/mace/tools/python/py_proto

CMD> bazel build //third_party/caffe:caffe_py
WARNING: detected http_proxy set in env, setting no_proxy for localhost.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Loading:
Loading: 0 packages loaded
Analyzing: target //third_party/caffe:caffe_py (12 packages loaded)
INFO: Analysed target //third_party/caffe:caffe_py (17 packages loaded).
INFO: Found 1 target...
[2 / 11] [-----] BazelWorkspaceStatusAction stable-status.txt
Target //third_party/caffe:caffe_py up-to-date:
bazel-genfiles/third_party/caffe/caffe_pb2.py
INFO: Elapsed time: 1.939s, Critical Path: 0.08s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action

CMD> cp -f bazel-genfiles/third_party/caffe/caffe_pb2.py /container/path/mace/mace/tools/python/py_proto

!!! {'Snap820': {'target_abis': ['aarch64'], 'models': 'Qualcomm 820', 'username': 'root', 'target_socs': ['MSM8996'], 'address': '192.168.8.1'}}
tools/python/run_model.py:73: Run on devices: ['root@192.168.8.1']
tools/python/run_model.py:84: Run model mobilenet_v1_quantize_retrain
{'model_sha256_checksum': 'c3faa9bd790310eb3dec411d2f2e2dd8802394e31ccb47daaa5e3b6369fadfa3', 'input_tensors': ['input'], 'limit_opencl_kernel_time': 0, 'output_shapes': ['1,1001'], 'winograd': 0, 'nnlib_graph_mode': 0, 'input_shapes': ['1,224,224,3'], 'quantize': 1, 'obfuscate': 0, 'platform': 'tensorflow', 'output_tensors': ['MobilenetV1/Predictions/Softmax:0'], 'validation_inputs_data': ['http://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v1/input_n01440764_15071.JPEG_input'], 'check_shapes': ['1,1,1,1001'], 'check_tensors': ['MobilenetV1/Logits/Conv2d_1c_1x1/BiasAdd:0'], 'runtime': 'dsp', 'input_ranges': ['-1.0,1.0'], 'model_file_path': '../../mace-models/mobilenet-v1/mobilenet_v1_1.0_224_quant_retrain.pb'}
{'model_sha256_checksum': 'c3faa9bd790310eb3dec411d2f2e2dd8802394e31ccb47daaa5e3b6369fadfa3', 'input_data_types': [1], 'output_tensors': ['MobilenetV1/Predictions/Softmax:0'], 'input_shapes': [[1, 224, 224, 3]], 'quantize': 1, 'platform': <Platform.TENSORFLOW: 0>, 'input_data_formats': [<DataFormat.NHWC: 1>], 'output_shapes': [[1, 1001]], 'nnlib_graph_mode': 0, 'output_data_types': [1], 'validation_inputs_data': ['http://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v1/input_n01440764_15071.JPEG_input'], 'check_shapes': [[1, 1, 1, 1001]], 'data_type': 1, 'input_tensors': ['input'], 'output_data_formats': [<DataFormat.NHWC: 1>], 'model_file_path': '../../mace-models/mobilenet-v1/mobilenet_v1_1.0_224_quant_retrain.pb', 'check_tensors': ['MobilenetV1/Logits/Conv2d_1c_1x1/BiasAdd:0'], 'input_ranges': [[-1.0, 1.0]], 'winograd': 0, 'limit_opencl_kernel_time': 0, 'obfuscate': 0, 'runtime': <DeviceType.HEXAGON: 3>}
CMD> ssh root@192.168.8.1 mkdir -p /tmp/mace_run/mobilenet_v1_quantize_retrain/interior

CMD> ssh root@192.168.8.1 mkdir -p /tmp/mace_run/mobilenet_v1_quantize_retrain

CMD> scp -r build/mobilenet_v1_quantize_retrain/model/mobilenet_v1_quantize_retrain.pb root@192.168.8.1:/tmp/mace_run/mobilenet_v1_quantize_retrain

CMD> ssh root@192.168.8.1 mkdir -p /tmp/mace_run/mobilenet_v1_quantize_retrain

CMD> scp -r build/mobilenet_v1_quantize_retrain/model/mobilenet_v1_quantize_retrain.data root@192.168.8.1:/tmp/mace_run/mobilenet_v1_quantize_retrain

/container/path/mace/mace/tools/python/utils/util.py:156: Downloading file http://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v1/input_n01440764_15071.JPEG_input to /tmp/tmp61tL3g/mobilenet_v1_quantize_retrain_input, please wait ...
/container/path/mace/mace/tools/python/utils/util.py:166: Model downloaded successfully.
CMD> ssh root@192.168.8.1 mkdir -p /tmp/mace_run/mobilenet_v1_quantize_retrain/validate_in

CMD> scp -r /tmp/tmp61tL3g root@192.168.8.1:/tmp/mace_run/mobilenet_v1_quantize_retrain/validate_in

CMD> ssh root@192.168.8.1 mkdir -p /tmp/mace_run/mobilenet_v1_quantize_retrain/validate_out

!!! {'Snap820': {'target_abis': ['aarch64'], 'models': 'Qualcomm 820', 'username': 'root', 'target_socs': ['MSM8996'], 'address': '192.168.8.1'}}
Run on devices: ['root@192.168.8.1']
Install target from build/cmake-build/aarch64-linux-gnu/install/bin/mace_run to /tmp/mace_run/mobilenet_v1_quantize_retrain
CMD> ssh root@192.168.8.1 mkdir -p /tmp/mace_run/mobilenet_v1_quantize_retrain

CMD> scp -r build/cmake-build/aarch64-linux-gnu/install/bin/mace_run root@192.168.8.1:/tmp/mace_run/mobilenet_v1_quantize_retrain

CMD> scp -r third_party/nnlib/aarch64-linux-gnu/libhexagon_controller.so:/tmp/mace_run/mobilenet_v1_quantize_retrain
usage: scp [-12346BCpqrv] [-c cipher] [-F ssh_config] [-i identity_file]
[-l limit] [-o ssh_option] [-P port] [-S program]
[[user@]host1:]file1 ... [[user@]host2:]file2
Traceback (most recent call last):
  File "tools/python/run_model.py", line 379, in <module>
    run_models(flags, args)
  File "tools/python/run_model.py", line 77, in run_models
    run_models_for_device(flags, args, dev)
  File "tools/python/run_model.py", line 86, in run_models_for_device
    run_model_for_device(flags, args, dev, name, model_conf)
  File "tools/python/run_model.py", line 204, in run_model_for_device
    device_ids=flags.target_socs)
  File "/container/path/mace/mace/tools/python/run_target.py", line 51, in run_target
    device_target = dev.install(target_obj, install_dir, install_deps=True)
  File "/container/path/mace/mace/tools/python/utils/device.py", line 251, in install
    execute("scp -r %s:%s" % (lib, install_dir))
  File "/container/path/mace/mace/tools/python/utils/device.py", line 58, in execute
    raise Exception("errorcode: %s" % p.returncode)
Exception: errorcode: 1
```

### Additional context
none.

**Comment by lu229** [comment]
@pgaston Yes it is a bug, thanks for your report, please use this [patch](https://github.com/lu229/repository/blob/master/fix_dsp_bug.patch), we will fix it after your validation.

**Comment by pgaston** [comment]
I think I have more work to do to get the DSP working - 'device_' Must not be NULL (I can work this out in a new issue if you wish.)    But the script made it past this point.    So feel free to apply that patch.
```
# python tools/python/run_model.py      --config ../../mace-models/mobilenet-v1/mobilenet-v1-quantize-retrain-dsp.yml     --benchmark     --target_abi aarch64-linux-gnu     --target_socs root@192.168.8.1     --device_conf ../../mace-models/820.yml
CMD> bazel build //mace/proto:mace_py
WARNING: ignoring http_proxy in environment.
Loading:
Loading: 0 packages loaded
Analyzing: target //mace/proto:mace_py (11 packages loaded)
INFO: Analysed target //mace/proto:mace_py (16 packages loaded).
INFO: Found 1 target...
[2 / 6] [-----] BazelWorkspaceStatusAction stable-status.txt
Target //mace/proto:mace_py up-to-date:
bazel-genfiles/mace/proto/mace_pb2.py
INFO: Elapsed time: 1.836s, Critical Path: 0.11s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

CMD> cp -f bazel-genfiles/mace/proto/mace_pb2.py /container/path/mace/mace/tools/python/py_proto

CMD> bazel build //third_party/caffe:caffe_py
WARNING: ignoring http_proxy in environment.
Loading:
Loading: 0 packages loaded
Analyzing: target //third_party/caffe:caffe_py (11 packages loaded)
INFO: Analysed target //third_party/caffe:caffe_py (16 packages loaded).
INFO: Found 1 target...
[1 / 15] [-----] BazelWorkspaceStatusAction stable-status.txt
Target //third_party/caffe:caffe_py up-to-date:
bazel-genfiles/third_party/caffe/caffe_pb2.py
INFO: Elapsed time: 1.775s, Critical Path: 0.12s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

CMD> cp -f bazel-genfiles/third_party/caffe/caffe_pb2.py /container/path/mace/mace/tools/python/py_proto

!!! {'Snap820': {'target_abis': ['aarch64'], 'models': 'Qualcomm 820', 'username': 'root', 'target_socs': ['MSM8996'], 'address': '192.168.8.1'}}
tools/python/run_model.py:73: Run on devices: ['root@192.168.8.1']
tools/python/run_model.py:84: Run model mobilenet_v1_quantize_retrain
{'model_sha256_checksum': 'c3faa9bd790310eb3dec411d2f2e2dd8802394e31ccb47daaa5e3b6369fadfa3', 'input_tensors': ['input'], 'limit_opencl_kernel_time': 0, 'output_shapes': ['1,1001'], 'winograd': 0, 'nnlib_graph_mode': 0, 'input_shapes': ['1,224,224,3'], 'quantize': 1, 'obfuscate': 0, 'platform': 'tensorflow', 'output_tensors': ['MobilenetV1/Predictions/Softmax:0'], 'validation_inputs_data': ['http://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v1/input_n01440764_15071.JPEG_input'], 'check_shapes': ['1,1,1,1001'], 'check_tensors': ['MobilenetV1/Logits/Conv2d_1c_1x1/BiasAdd:0'], 'runtime': 'dsp', 'input_ranges': ['-1.0,1.0'], 'model_file_path': '../../mace-models/mobilenet-v1/mobilenet_v1_1.0_224_quant_retrain.pb'}
{'model_sha256_checksum': 'c3faa9bd790310eb3dec411d2f2e2dd8802394e31ccb47daaa5e3b6369fadfa3', 'input_data_types': [1], 'output_tensors': ['MobilenetV1/Predictions/Softmax:0'], 'input_shapes': [[1, 224, 224, 3]], 'quantize': 1, 'platform': <Platform.TENSORFLOW: 0>, 'input_data_formats': [<DataFormat.NHWC: 1>], 'output_shapes': [[1, 1001]], 'nnlib_graph_mode': 0, 'output_data_types': [1], 'validation_inputs_data': ['http://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v1/input_n01440764_15071.JPEG_input'], 'check_shapes': [[1, 1, 1, 1001]], 'data_type': 1, 'input_tensors': ['input'], 'output_data_formats': [<DataFormat.NHWC: 1>], 'model_file_path': '../../mace-models/mobilenet-v1/mobilenet_v1_1.0_224_quant_retrain.pb', 'check_tensors': ['MobilenetV1/Logits/Conv2d_1c_1x1/BiasAdd:0'], 'input_ranges': [[-1.0, 1.0]], 'winograd': 0, 'limit_opencl_kernel_time': 0, 'obfuscate': 0, 'runtime': <DeviceType.HEXAGON: 3>}
CMD> ssh root@192.168.8.1 mkdir -p /tmp/mace_run/mobilenet_v1_quantize_retrain/interior

WARNING: tools/python/run_model.py:114: No models exist in build/mobilenet_v1_quantize_retrain/model/mobilenet_v1_quantize_retrain.pb, use --model_file and --model_data_file specified in args
/container/path/mace/mace/tools/python/utils/util.py:156: Downloading file http://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v1/input_n01440764_15071.JPEG_input to /tmp/tmpgkIx2g/mobilenet_v1_quantize_retrain_input, please wait ...
/container/path/mace/mace/tools/python/utils/util.py:166: Model downloaded successfully.
CMD> ssh root@192.168.8.1 mkdir -p /tmp/mace_run/mobilenet_v1_quantize_retrain/validate_in

CMD> scp -r /tmp/tmpgkIx2g root@192.168.8.1:/tmp/mace_run/mobilenet_v1_quantize_retrain/validate_in

CMD> ssh root@192.168.8.1 mkdir -p /tmp/mace_run/mobilenet_v1_quantize_retrain/validate_out

!!! {'Snap820': {'target_abis': ['aarch64'], 'models': 'Qualcomm 820', 'username': 'root', 'target_socs': ['MSM8996'], 'address': '192.168.8.1'}}
Run on devices: ['root@192.168.8.1']
Install target from build/cmake-build/aarch64-linux-gnu/install/bin/mace_run to /tmp/mace_run/mobilenet_v1_quantize_retrain
CMD> ssh root@192.168.8.1 mkdir -p /tmp/mace_run/mobilenet_v1_quantize_retrain

CMD> scp -r build/cmake-build/aarch64-linux-gnu/install/bin/mace_run root@192.168.8.1:/tmp/mace_run/mobilenet_v1_quantize_retrain

CMD> scp -r third_party/nnlib/aarch64-linux-gnu/libhexagon_controller.so root@192.168.8.1:/tmp/mace_run/mobilenet_v1_quantize_retrain

['', 'MACE_INTERNAL_STORAGE_PATH=/tmp/mace_run/mobilenet_v1_quantize_retrain/interior', 'LD_LIBRARY_PATH=/tmp/mace_run/mobilenet_v1_quantize_retrain', '/tmp/mace_run/mobilenet_v1_quantize_retrain/mace_run', '--device=HEXAGON', '--input_data_format=NHWC', '--output_node=MobilenetV1/Logits/Conv2d_1c_1x1/BiasAdd:0', '--output_shape=1,1,1,1001', '--model_data_file=/tmp/mace_run/mobilenet_v1_quantize_retrain/mobilenet_v1_quantize_retrain.data', '--input_node=input', '--model_file=/tmp/mace_run/mobilenet_v1_quantize_retrain/mobilenet_v1_quantize_retrain.pb', '--model_name=mobilenet_v1_quantize_retrain', '--output_data_format=NHWC', '--input_shape=1,224,224,3', '--benchmark', '--input_file=/tmp/mace_run/mobilenet_v1_quantize_retrain/validate_in/mobilenet_v1_quantize_retrain', '--output_file=/tmp/mace_run/mobilenet_v1_quantize_retrain/validate_out/mobilenet_v1_quantize_retrain']
 MACE_INTERNAL_STORAGE_PATH=/tmp/mace_run/mobilenet_v1_quantize_retrain/interior LD_LIBRARY_PATH=/tmp/mace_run/mobilenet_v1_quantize_retrain /tmp/mace_run/mobilenet_v1_quantize_retrain/mace_run --device=HEXAGON --input_data_format=NHWC --output_node=MobilenetV1/Logits/Conv2d_1c_1x1/BiasAdd:0 --output_shape=1,1,1,1001 --model_data_file=/tmp/mace_run/mobilenet_v1_quantize_retrain/mobilenet_v1_quantize_retrain.data --input_node=input --model_file=/tmp/mace_run/mobilenet_v1_quantize_retrain/mobilenet_v1_quantize_retrain.pb --model_name=mobilenet_v1_quantize_retrain --output_data_format=NHWC --input_shape=1,224,224,3 --benchmark --input_file=/tmp/mace_run/mobilenet_v1_quantize_retrain/validate_in/mobilenet_v1_quantize_retrain --output_file=/tmp/mace_run/mobilenet_v1_quantize_retrain/validate_out/mobilenet_v1_quantize_retrain
Runing ...
['', 'MACE_INTERNAL_STORAGE_PATH=/tmp/mace_run/mobilenet_v1_quantize_retrain/interior', 'LD_LIBRARY_PATH=/tmp/mace_run/mobilenet_v1_quantize_retrain', '/tmp/mace_run/mobilenet_v1_quantize_retrain/mace_run', '--device=HEXAGON', '--input_data_format=NHWC', '--output_node=MobilenetV1/Logits/Conv2d_1c_1x1/BiasAdd:0', '--output_shape=1,1,1,1001', '--model_data_file=/tmp/mace_run/mobilenet_v1_quantize_retrain/mobilenet_v1_quantize_retrain.data', '--input_node=input', '--model_file=/tmp/mace_run/mobilenet_v1_quantize_retrain/mobilenet_v1_quantize_retrain.pb', '--model_name=mobilenet_v1_quantize_retrain', '--output_data_format=NHWC', '--input_shape=1,224,224,3', '--benchmark', '--input_file=/tmp/mace_run/mobilenet_v1_quantize_retrain/validate_in/mobilenet_v1_quantize_retrain', '--output_file=/tmp/mace_run/mobilenet_v1_quantize_retrain/validate_out/mobilenet_v1_quantize_retrain']
CMD> ssh root@192.168.8.1  MACE_INTERNAL_STORAGE_PATH=/tmp/mace_run/mobilenet_v1_quantize_retrain/interior LD_LIBRARY_PATH=/tmp/mace_run/mobilenet_v1_quantize_retrain /tmp/mace_run/mobilenet_v1_quantize_retrain/mace_run --device=HEXAGON --input_data_format=NHWC --output_node=MobilenetV1/Logits/Conv2d_1c_1x1/BiasAdd:0 --output_shape=1,1,1,1001 --model_data_file=/tmp/mace_run/mobilenet_v1_quantize_retrain/mobilenet_v1_quantize_retrain.data --input_node=input --model_file=/tmp/mace_run/mobilenet_v1_quantize_retrain/mobilenet_v1_quantize_retrain.pb --model_name=mobilenet_v1_quantize_retrain --output_data_format=NHWC --input_shape=1,224,224,3 --benchmark --input_file=/tmp/mace_run/mobilenet_v1_quantize_retrain/validate_in/mobilenet_v1_quantize_retrain --output_file=/tmp/mace_run/mobilenet_v1_quantize_retrain/validate_out/mobilenet_v1_quantize_retrain
I /container/path/mace/mace/mace/tools/mace_run.cc:527] model name: mobilenet_v1_quantize_retrain
I /container/path/mace/mace/mace/tools/mace_run.cc:528] mace version: v0.12.0-0-ga610d50
I /container/path/mace/mace/mace/tools/mace_run.cc:529] input node: input
I /container/path/mace/mace/mace/tools/mace_run.cc:530] input shape: 1,224,224,3
I /container/path/mace/mace/mace/tools/mace_run.cc:531] output node: MobilenetV1/Logits/Conv2d_1c_1x1/BiasAdd:0
I /container/path/mace/mace/mace/tools/mace_run.cc:532] output shape: 1,1,1,1001
I /container/path/mace/mace/mace/tools/mace_run.cc:533] input_file: /tmp/mace_run/mobilenet_v1_quantize_retrain/validate_in/mobilenet_v1_quantize_retrain
I /container/path/mace/mace/mace/tools/mace_run.cc:534] output_file: /tmp/mace_run/mobilenet_v1_quantize_retrain/validate_out/mobilenet_v1_quantize_retrain
I /container/path/mace/mace/mace/tools/mace_run.cc:535] input dir:
I /container/path/mace/mace/mace/tools/mace_run.cc:536] output dir: output
I /container/path/mace/mace/mace/tools/mace_run.cc:537] model_data_file: /tmp/mace_run/mobilenet_v1_quantize_retrain/mobilenet_v1_quantize_retrain.data
I /container/path/mace/mace/mace/tools/mace_run.cc:538] model_file: /tmp/mace_run/mobilenet_v1_quantize_retrain/mobilenet_v1_quantize_retrain.pb
I /container/path/mace/mace/mace/tools/mace_run.cc:539] device: HEXAGON
I /container/path/mace/mace/mace/tools/mace_run.cc:540] round: 1
I /container/path/mace/mace/mace/tools/mace_run.cc:541] restart_round: 1
I /container/path/mace/mace/mace/tools/mace_run.cc:542] gpu_perf_hint: 3
I /container/path/mace/mace/mace/tools/mace_run.cc:543] gpu_priority_hint: 3
I /container/path/mace/mace/mace/tools/mace_run.cc:544] omp_num_threads: -1
I /container/path/mace/mace/mace/tools/mace_run.cc:545] cpu_affinity_policy: 1
I /container/path/mace/mace/mace/libmace/mace.cc:464] Creating MaceEngine, MACE version: v0.12.0-0-ga610d50
I /container/path/mace/mace/mace/libmace/mace.cc:503] Initializing MaceEngine
I /container/path/mace/mace/mace/libmace/mace.cc:636] Destroying MaceEngine
I /container/path/mace/mace/mace/tools/mace_run.cc:596] restart round 0
I /container/path/mace/mace/mace/libmace/mace.cc:911] Create MaceEngine from model graph proto and weights data
I /container/path/mace/mace/mace/libmace/mace.cc:464] Creating MaceEngine, MACE version: v0.12.0-0-ga610d50
F /container/path/mace/mace/mace/libmace/mace.cc:495] 'device_' Must not be NULL
Traceback (most recent call last):
  File "tools/python/run_model.py", line 379, in <module>
    run_models(flags, args)
  File "tools/python/run_model.py", line 77, in run_models
    run_models_for_device(flags, args, dev)
  File "tools/python/run_model.py", line 86, in run_models_for_device
    run_model_for_device(flags, args, dev, name, model_conf)
  File "tools/python/run_model.py", line 204, in run_model_for_device
    device_ids=flags.target_socs)
  File "/container/path/mace/mace/tools/python/run_target.py", line 57, in run_target
    dev.run(device_target)
  File "/container/path/mace/mace/tools/python/utils/device.py", line 262, in run
    execute("ssh %s %s" % (self._device_id, target))
  File "/container/path/mace/mace/tools/python/utils/device.py", line 58, in execute
    raise Exception("errorcode: %s" % p.returncode)
Exception: errorcode: 255

```

**Comment by lu229** [comment]
@pgaston 
The cause of the error is: 'device_' must not be null. 
In code the variable 'device_' is created by the new operator, have you modified the code?

**Comment by yejw5** [comment]
@pgaston It seems that you have built mace engine with other device? You can try `RUNTIME=HEXAGON bash tools/cmake/cmake-build-armeabi-v7a.sh` following [Basic Usage for Bazel Users](https://mace.readthedocs.io/en/latest/user_guide/basic_usage.html)
