### ISSUE TITLE
run_model.py errors for linux target

### ISSUE THREAD

**Issue by pgaston** [XiaoMi/mace#582]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage? yes
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 
  Ubuntu 18.04 laptop, target is Qualcomm 820 w/ Adreno 530, Hexagon DSP
  target is running minimal linux
- **NDK version(e.g., 15c)**: n.a.
- **GCC version(if compiling for host, e.g., 5.4.0)**:  
  gcc version 5.4.0, in mace-dev docker, 
**however** I changed this to use gcc version 4.9.3 to match my target environment with it's libOpenCL.so being 32 bit.   e.g., I executed:
```
apt-get install gcc-4.9-arm-linux-gnueabi
apt-get install g++-4.9-arm-linux-gnueabi
```
- **MACE version (Use the command: git describe --long --tags)**: v0.12.0-26-gfc973e7
- **Python version(2.7)**: 2.7.12
- **Bazel version (e.g., 0.13.0)**:  n.a.

### Model deploy file (*.yml)
default from tutorial - mobilenet

### Describe the problem

run_model.py dies.   However, after it dies I can go to target and manually
start mace_run with the appropriate arguments.

This occurs with a linux target (I'm guessing that you test Android more often...)

Issues I see:
- The folder 'interior' is not referenced consistently - it's built as 
/tmp/mace_run/mobilenet_v1/interior, run_model.py reports "Failed to read kv store file: /tmp/mace_run/mobilenet_v1/interior/mace_cl_compiled_program.bin"
 but in the script it's referenced as
/data/local/tmp/mace_run/interior.   This causes a fatal error.    After I created that folder manually I
could get the script to run.
- run_python dies with... "TypeError: 'NoneType' object has no attribute '__getitem__'" 
See below for full stack trace.
- input file is not connected right.   run_python calls it 
"/tmp/mace_run/mobilenet_v1/validate_in/mobilenet_v1" but it's stored as
"/tmp/mace_run/mobilenet_v1/validate_in/tmpQyL_51/mobilenet_v1_input"

### To Reproduce
Steps to reproduce the problem:  per above, just follow instructions (this time w/ full size docker)
Invoked with (inside mace-dev docker environment)

See following log...

### Error information / logs
Please include the **full** log and/or traceback here.
```
# python tools/python/run_model.py  \
>     --config ../../mace-models/mobilenet-v1/mobilenet-v1.yml \
>     --validate \
>     --target_abi arm-linux-gnueabihf \
>     --target_socs root@192.168.8.1 \
>     --device_conf ../../mace-models/820.yml
CMD> bazel build //mace/proto:mace_py
WARNING: detected http_proxy set in env, setting no_proxy for localhost.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Loading:
Loading: 0 packages loaded
Analyzing: target //mace/proto:mace_py (12 packages loaded)
INFO: Analysed target //mace/proto:mace_py (17 packages loaded).
INFO: Found 1 target...
[2 / 24] [-----] BazelWorkspaceStatusAction stable-status.txt
Target //mace/proto:mace_py up-to-date:
bazel-genfiles/mace/proto/mace_pb2.py
INFO: Elapsed time: 1.945s, Critical Path: 0.08s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action

CMD> cp -f bazel-genfiles/mace/proto/mace_pb2.py /container/path/mace/mace/tools/python/py_proto

CMD> bazel build //third_party/caffe:caffe_py
WARNING: detected http_proxy set in env, setting no_proxy for localhost.
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Loading:
Loading: 0 packages loaded
Analyzing: target //third_party/caffe:caffe_py (8 packages loaded)
INFO: Analysed target //third_party/caffe:caffe_py (17 packages loaded).
INFO: Found 1 target...
[2 / 20] [-----] BazelWorkspaceStatusAction stable-status.txt
Target //third_party/caffe:caffe_py up-to-date:
bazel-genfiles/third_party/caffe/caffe_pb2.py
INFO: Elapsed time: 2.021s, Critical Path: 0.08s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action

CMD> cp -f bazel-genfiles/third_party/caffe/caffe_pb2.py /container/path/mace/mace/tools/python/py_proto

!!! {'Snap820': {'target_abis': ['armv7a'], 'models': 'Qualcomm 820', 'username': 'root', 'target_socs': ['APQ8096'], 'address': '192.168.8.1'}}
tools/python/run_model.py:73: Run on devices: ['root@192.168.8.1']
tools/python/run_model.py:84: Run model mobilenet_v1
{'model_sha256_checksum': '71b10f540ece33c49a7b51f5d4095fc9bd78ce46ebf0300487b2ee23d71294e6', 'output_shapes': ['1,1001'], 'output_tensors': ['MobilenetV1/Predictions/Reshape_1'], 'input_tensors': ['input'], 'input_shapes': ['1,224,224,3'], 'platform': 'tensorflow', 'model_file_path': '../../mace-models/mobilenet-v1/mobilenet-v1-1.0.pb', 'runtime': 'gpu'}
{'output_data_types': [1], 'model_sha256_checksum': '71b10f540ece33c49a7b51f5d4095fc9bd78ce46ebf0300487b2ee23d71294e6', 'data_type': 3, 'input_ranges': [[-1.0, 1.0]], 'input_data_formats': [<DataFormat.NHWC: 1>], 'output_shapes': [[1, 1001]], 'output_tensors': ['MobilenetV1/Predictions/Reshape_1'], 'input_tensors': ['input'], 'input_shapes': [[1, 224, 224, 3]], 'platform': <Platform.TENSORFLOW: 0>, 'output_data_formats': [<DataFormat.NHWC: 1>], 'model_file_path': '../../mace-models/mobilenet-v1/mobilenet-v1-1.0.pb', 'input_data_types': [1], 'runtime': <DeviceType.GPU: 2>}
CMD> ssh root@192.168.8.1 mkdir -p /tmp/mace_run/mobilenet_v1/interior

CMD> ssh root@192.168.8.1 mkdir -p /tmp/mace_run/mobilenet_v1

CMD> scp -r build/mobilenet_v1/model/mobilenet_v1.pb root@192.168.8.1:/tmp/mace_run/mobilenet_v1

CMD> ssh root@192.168.8.1 mkdir -p /tmp/mace_run/mobilenet_v1

CMD> scp -r build/mobilenet_v1/model/mobilenet_v1.data root@192.168.8.1:/tmp/mace_run/mobilenet_v1

tools/python/run_model.py:264: Generate input file: /tmp/tmpQyL_51/mobilenet_v1_input
CMD> ssh root@192.168.8.1 mkdir -p /tmp/mace_run/mobilenet_v1/validate_in

CMD> scp -r /tmp/tmpQyL_51 root@192.168.8.1:/tmp/mace_run/mobilenet_v1/validate_in

CMD> ssh root@192.168.8.1 mkdir -p /tmp/mace_run/mobilenet_v1/validate_out

!!! {'Snap820': {'target_abis': ['armv7a'], 'models': 'Qualcomm 820', 'username': 'root', 'target_socs': ['APQ8096'], 'address': '192.168.8.1'}}
Run on devices: ['root@192.168.8.1']
Install target from build/cmake-build/arm-linux-gnueabihf/install/bin/mace_run to /tmp/mace_run/mobilenet_v1
CMD> ssh root@192.168.8.1 mkdir -p /tmp/mace_run/mobilenet_v1

CMD> scp -r build/cmake-build/arm-linux-gnueabihf/install/bin/mace_run root@192.168.8.1:/tmp/mace_run/mobilenet_v1

['', 'MACE_INTERNAL_STORAGE_PATH=/tmp/mace_run/mobilenet_v1/interior', 'LD_LIBRARY_PATH=/tmp/mace_run/mobilenet_v1', '/tmp/mace_run/mobilenet_v1/mace_run', '--device=GPU', '--input_data_format=NHWC', '--output_node=MobilenetV1/Predictions/Reshape_1', '--output_shape=1,1001', '--model_data_file=/tmp/mace_run/mobilenet_v1/mobilenet_v1.data', '--input_node=input', '--model_file=/tmp/mace_run/mobilenet_v1/mobilenet_v1.pb', '--model_name=mobilenet_v1', '--output_data_format=NHWC', '--input_shape=1,224,224,3', '--input_file=/tmp/mace_run/mobilenet_v1/validate_in/mobilenet_v1', '--output_file=/tmp/mace_run/mobilenet_v1/validate_out/mobilenet_v1']
 MACE_INTERNAL_STORAGE_PATH=/tmp/mace_run/mobilenet_v1/interior LD_LIBRARY_PATH=/tmp/mace_run/mobilenet_v1 /tmp/mace_run/mobilenet_v1/mace_run --device=GPU --input_data_format=NHWC --output_node=MobilenetV1/Predictions/Reshape_1 --output_shape=1,1001 --model_data_file=/tmp/mace_run/mobilenet_v1/mobilenet_v1.data --input_node=input --model_file=/tmp/mace_run/mobilenet_v1/mobilenet_v1.pb --model_name=mobilenet_v1 --output_data_format=NHWC --input_shape=1,224,224,3 --input_file=/tmp/mace_run/mobilenet_v1/validate_in/mobilenet_v1 --output_file=/tmp/mace_run/mobilenet_v1/validate_out/mobilenet_v1
Runing ...
['', 'MACE_INTERNAL_STORAGE_PATH=/tmp/mace_run/mobilenet_v1/interior', 'LD_LIBRARY_PATH=/tmp/mace_run/mobilenet_v1', '/tmp/mace_run/mobilenet_v1/mace_run', '--device=GPU', '--input_data_format=NHWC', '--output_node=MobilenetV1/Predictions/Reshape_1', '--output_shape=1,1001', '--model_data_file=/tmp/mace_run/mobilenet_v1/mobilenet_v1.data', '--input_node=input', '--model_file=/tmp/mace_run/mobilenet_v1/mobilenet_v1.pb', '--model_name=mobilenet_v1', '--output_data_format=NHWC', '--input_shape=1,224,224,3', '--input_file=/tmp/mace_run/mobilenet_v1/validate_in/mobilenet_v1', '--output_file=/tmp/mace_run/mobilenet_v1/validate_out/mobilenet_v1']
CMD> ssh root@192.168.8.1  MACE_INTERNAL_STORAGE_PATH=/tmp/mace_run/mobilenet_v1/interior LD_LIBRARY_PATH=/tmp/mace_run/mobilenet_v1 /tmp/mace_run/mobilenet_v1/mace_run --device=GPU --input_data_format=NHWC --output_node=MobilenetV1/Predictions/Reshape_1 --output_shape=1,1001 --model_data_file=/tmp/mace_run/mobilenet_v1/mobilenet_v1.data --input_node=input --model_file=/tmp/mace_run/mobilenet_v1/mobilenet_v1.pb --model_name=mobilenet_v1 --output_data_format=NHWC --input_shape=1,224,224,3 --input_file=/tmp/mace_run/mobilenet_v1/validate_in/mobilenet_v1 --output_file=/tmp/mace_run/mobilenet_v1/validate_out/mobilenet_v1
I /container/path/mace/mace/mace/tools/mace_run.cc:527] model name: mobilenet_v1
I /container/path/mace/mace/mace/tools/mace_run.cc:528] mace version: v0.12.0-0-ga610d50
I /container/path/mace/mace/mace/tools/mace_run.cc:529] input node: input
I /container/path/mace/mace/mace/tools/mace_run.cc:530] input shape: 1,224,224,3
I /container/path/mace/mace/mace/tools/mace_run.cc:531] output node: MobilenetV1/Predictions/Reshape_1
I /container/path/mace/mace/mace/tools/mace_run.cc:532] output shape: 1,1001
I /container/path/mace/mace/mace/tools/mace_run.cc:533] input_file: /tmp/mace_run/mobilenet_v1/validate_in/mobilenet_v1
I /container/path/mace/mace/mace/tools/mace_run.cc:534] output_file: /tmp/mace_run/mobilenet_v1/validate_out/mobilenet_v1
I /container/path/mace/mace/mace/tools/mace_run.cc:535] input dir:
I /container/path/mace/mace/mace/tools/mace_run.cc:536] output dir: output
I /container/path/mace/mace/mace/tools/mace_run.cc:537] model_data_file: /tmp/mace_run/mobilenet_v1/mobilenet_v1.data
I /container/path/mace/mace/mace/tools/mace_run.cc:538] model_file: /tmp/mace_run/mobilenet_v1/mobilenet_v1.pb
I /container/path/mace/mace/mace/tools/mace_run.cc:539] device: GPU
I /container/path/mace/mace/mace/tools/mace_run.cc:540] round: 1
I /container/path/mace/mace/mace/tools/mace_run.cc:541] restart_round: 1
I /container/path/mace/mace/mace/tools/mace_run.cc:542] gpu_perf_hint: 3
I /container/path/mace/mace/mace/tools/mace_run.cc:543] gpu_priority_hint: 3
I /container/path/mace/mace/mace/tools/mace_run.cc:544] omp_num_threads: -1
I /container/path/mace/mace/mace/tools/mace_run.cc:545] cpu_affinity_policy: 1
I /container/path/mace/mace/mace/libmace/mace.cc:464] Creating MaceEngine, MACE version: v0.12.0-0-ga610d50
I /container/path/mace/mace/mace/libmace/mace.cc:503] Initializing MaceEngine
I /container/path/mace/mace/mace/libmace/mace.cc:636] Destroying MaceEngine
I /container/path/mace/mace/mace/tools/mace_run.cc:596] restart round 0
I /container/path/mace/mace/mace/libmace/mace.cc:911] Create MaceEngine from model graph proto and weights data
I /container/path/mace/mace/mace/libmace/mace.cc:464] Creating MaceEngine, MACE version: v0.12.0-0-ga610d50
W /container/path/mace/mace/mace/core/kv_storage.cc:109] Failed to read kv store file: /tmp/mace_run/mobilenet_v1/interior/mace_cl_compiled_program.bin
W /container/path/mace/mace/mace/core/runtime/opencl/opencl_runtime.cc:382] Load OpenCL cached compiled kernel file failed. Please make sure the storage directory exist and you have Write&Read permission
I /container/path/mace/mace/mace/libmace/mace.cc:503] Initializing MaceEngine
I /container/path/mace/mace/mace/tools/mace_run.cc:269] Create Mace Engine latency: 2459.38 ms
I /container/path/mace/mace/mace/tools/mace_run.cc:276] Total init latency: 2459.76 ms
I /container/path/mace/mace/mace/tools/mace_run.cc:370] Warm up run
I /container/path/mace/mace/mace/tools/mace_run.cc:406] 1st warm up run latency: 2621.54 ms
I /container/path/mace/mace/mace/tools/mace_run.cc:414] Run model
I /container/path/mace/mace/mace/tools/mace_run.cc:476] Average latency: 16.639 ms
I /container/path/mace/mace/mace/tools/mace_run.cc:491] Write output file /tmp/mace_run/mobilenet_v1/validate_out/mobilenet_v1_MobilenetV1_Predictions_Reshape_1 with size 4004 done.
========================================================
capability(CPU)        init      warmup     run_avg
========================================================
time          25.337    2459.755    2621.537      16.639
I /container/path/mace/mace/mace/libmace/mace.cc:636] Destroying MaceEngine
Traceback (most recent call last):
  File "tools/python/run_model.py", line 379, in <module>
    run_models(flags, args)
  File "tools/python/run_model.py", line 77, in run_models
    run_models_for_device(flags, args, dev)
  File "tools/python/run_model.py", line 86, in run_models_for_device
    run_model_for_device(flags, args, dev, name, model_conf)
  File "tools/python/run_model.py", line 213, in run_model_for_device
    dev.info()["ro.product.model"].replace(' ', ''),
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Manually running mace_run - after moving/renaming the input file**
```
mace_run --device=GPU --input_data_format=NHWC \
  --output_node=MobilenetV1/Predictions/Reshape_1 \
  --output_shape=1,1001 \
  --model_data_file=/tmp/mace_run/mobilenet_v1/mobilenet_v1.data \
  --input_node=input --model_file=/tmp/mace_run/mobilenet_v1/mobilenet_v1.pb \
  --model_name=mobilenet_v1 --output_data_format=NHWC \
  --input_shape=1,224,224,3 --benchmark \
  --input_file=/tmp/mace_run/mobilenet_v1/validate_in/mobilenet_v1 \
  --output_file=/tmp/mace_run/mobilenet_v1/validate_out/mobilenet_v1
```

**Comment by lu229** [comment]
@pgaston It seems that when using cmake mode, there is problem with the GPU running on arm linux devices at present, for we haven't tested it with arm linux. At present, there are two ways to solve the problem:
1. You can try to use the [commands based on bazel](https://mace.readthedocs.io/en/latest/user_guide/basic_usage.html).
2. You can modify the source code to support it. The current problem is that the dev.info() (run_model.py", line 213) returns None. You can refer to the AndroidDevice class to implement the ArmLinuxDevice::Info() method in the /mace/tools/python/utils/device.py file. at the same time any contribution to the project is welcome.
Please feel free to communicate if you have any questions.

**Comment by pgaston** [comment]
Thanks.
Best - p
