### ISSUE TITLE
release v.0.13.0转换caffe模型时遇到问题：TypeError: __new__() got an unexpected keyword argument 'serialized_options'

### ISSUE THREAD

**Issue by ysh329** [XiaoMi/mace#633]
Hi，mace的小伙伴你们好，我最近跑release v.0.13.0，在转换caffe模型时遇到问题，最后部分log如下
```shell
CMD> cp -f bazel-genfiles/mace/proto/micro_mem_pb2.py tools/python/py_proto

CMD> bazel build //third_party/caffe:caffe_py
WARNING: ignoring http_proxy in environment.
Loading:
Loading: 0 packages loaded
INFO: Analysed target //third_party/caffe:caffe_py (0 packages loaded).
INFO: Found 1 target...
[0 / 1] [-----] BazelWorkspaceStatusAction stable-status.txt
Target //third_party/caffe:caffe_py up-to-date:
bazel-genfiles/third_party/caffe/caffe_pb2.py
INFO: Elapsed time: 0.136s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

CMD> cp -f bazel-genfiles/third_party/caffe/caffe_pb2.py tools/python/py_proto

Traceback (most recent call last):
  File "tools/converter.py", line 30, in <module>
    from device import DeviceWrapper, DeviceManager
  File "/home/yuanshuai/code/mace/tools/device.py", line 26, in <module>
    import layers_validate
  File "tools/python/layers_validate.py", line 21, in <module>
    from py_proto import mace_pb2
  File "tools/python/py_proto/mace_pb2.py", line 23, in <module>
    \x04name\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\x05\x12\x0c\n\x04\x64ims\x18\x03 \x03(\x05\x12\x15\n\rmax_byte_size\x18\x04 \x01(\x05\x12+\n\tdata_type\x18\x05 \x01(\x0e\x32\x0e.mace.DataType:\x08\x44T_FLOAT\x12\x16\n\x0b\x64\x61ta_format\x18\x06 \x01(\x05:\x01\x31\x12\r\n\x05scale\x18\x07 \x01(\x02\x12\x12\n\nzero_point\x18\x08 \x01(\x05\"\xec\x01\n\x06NetDef\x12\x1d\n\x02op\x18\x01 \x03(\x0b\x32\x11.mace.OperatorDef\x12\x1b\n\x03\x61rg\x18\x02 \x03(\x0b\x32\x0e.mace.Argument\x12\"\n\x07tensors\x18\x03 \x03(\x0b\x32\x11.mace.ConstTensor\x12+\n\tdata_type\x18\x04 \x01(\x0e\x32\x0e.mace.DataType:\x08\x44T_FLOAT\x12)\n\ninput_info\x18\x64 \x03(\x0b\x32\x15.mace.InputOutputInfo\x12*\n\x0boutput_info\x18\x65 \x03(\x0b\x32\x15.mace.InputOutputInfo*r\n\x08\x44\x61taType\x12\x0e\n\nDT_INVALID\x10\x00\x12\x0c\n\x08\x44T_FLOAT\x10\x01\x12\x0c\n\x08\x44T_UINT8\x10\x02\x12\x0b\n\x07\x44T_HALF\x10\x03\x12\x0c\n\x08\x44T_INT32\x10\x04\x12\x0e\n\nDT_FLOAT16\x10\x05\x12\x0f\n\x0b\x44T_BFLOAT16\x10\x06*;\n\nMemoryType\x12\x0e\n\nCPU_BUFFER\x10\x00\x12\x0e\n\nGPU_BUFFER\x10\x01\x12\r\n\tGPU_IMAGE\x10\x02\x42\x02H\x03')
TypeError: __new__() got an unexpected keyword argument 'serialized_options'
```

我看问题出在`TypeError: __new__() got an unexpected keyword argument 'serialized_options'`，但这个文件是只读的，我看也不是少个单引号什么的，我注释掉第22行，因为只读的缘故，失败了，我再试下改下

**Comment by ysh329** [comment]
![image](https://user-images.githubusercontent.com/7320657/80672217-a727d600-8ade-11ea-94c7-7b6160497034.png)

**Comment by lu229** [comment]
@ysh329 看起来是protobuf的版本过低导致，参考：https://blog.csdn.net/imucaoyue/article/details/85127043

**Comment by ysh329** [comment]
> @ysh329 看起来是protobuf的版本过低导致，参考：https://blog.csdn.net/imucaoyue/article/details/85127043

确实如此，由于用的是bvlc/caffe:cpu的docker镜像，protobuf版本较老。非常Thanks♪(･ω･)ﾉ

解决办法：

```shell
pip uninstall protobuf
pip install -U protobuf
```
