### ISSUE TITLE
jinja2: no filter named to json

### ISSUE THREAD

**Issue by LovelyBuggies** [XiaoMi/mace#649]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **NDK version(e.g., 15c)**: r15c
- **GCC version(if compiling for host, e.g., 5.4.0)**: 5.4.0
- **MACE version (Use the command: git describe --long --tags)**: v0.13.0-0-g9a06864
- **Python version(2.7)**: 
- **Bazel version (e.g., 0.13.0)**:

### Describe the problem

`no filter named to json` when building standalone. I tried the method in #620's https://github.com/XiaoMi/mace/issues/620#issuecomment-608426958. But `apt-get install python3-jinja2`==2.8.1 automatically, which will generate the problem `jinja2.exceptions.TemplateAssertionError: no filter named 'tojson'`.

P.S. A possible solution would be to upgrade jinja2 https://github.com/simonw/datasette/issues/100#issuecomment-344864254, but not sure how to do it (`apt-get upgrade python-jinja2` would always give me a 2.8.0). PyPI can get jinja2 2.11.0, but is of no use as mentioned above. Btw, aptitude gives me 2.8.0, too.😣

### To Reproduce

Steps to reproduce the problem:

```bash
bash tools/bazel-build-standalone-lib.sh [-abi=abi][-runtimes=rt1,rt2,...][-static]
```

### Error information / logs

Please include the **full** log and/or traceback here.

```bash
build shared lib for armeabi-v7a + cpu_gpu_dsp
Starting local Bazel server and connecting to it...
............
write version v0.13.0-0-g9a06864 to /home/parallels/.cache/bazel/_bazel_parallels/5ff1ff2df121917af4fe9fa25c7709ef/external/local_version_config/gen/version
Traceback (most recent call last):
  File "/home/parallels/.cache/bazel/_bazel_parallels/5ff1ff2df121917af4fe9fa25c7709ef/external/mace//mace/python/tools/encrypt_opencl_codegen.py", line 130, in <module>
    encrypt_opencl_codegen(FLAGS.cl_kernel_dir, FLAGS.output_path)
  File "/home/parallels/.cache/bazel/_bazel_parallels/5ff1ff2df121917af4fe9fa25c7709ef/external/mace//mace/python/tools/encrypt_opencl_codegen.py", line 104, in encrypt_opencl_codegen
    encrypted_code_maps, 'str2vec_maps.cc.jinja2', output_path)
  File "/home/parallels/.cache/bazel/_bazel_parallels/5ff1ff2df121917af4fe9fa25c7709ef/external/mace//mace/python/tools/encrypt_opencl_codegen.py", line 60, in write_cl_encrypted_kernel_to_file
    cl_encrypted_kernel = env.get_template(template_path).render(
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 786, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python2.7/dist-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 565, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/parallels/.cache/bazel/_bazel_parallels/5ff1ff2df121917af4fe9fa25c7709ef/external/mace//mace/python/tools/str2vec_maps.cc.jinja2", line 28, in template
    {{key|tojson}}, {
jinja2.exceptions.TemplateAssertionError: no filter named 'tojson'
ERROR: /home/parallels/mace/mace/codegen/BUILD.bazel:26:1: no such target '@local_opencl_kernel_encrypt//:gen/encrypt_opencl_kernel.cc': target 'gen/encrypt_opencl_kernel.cc' not declared in package '' defined by /home/parallels/.cache/bazel/_bazel_parallels/5ff1ff2df121917af4fe9fa25c7709ef/external/local_opencl_kernel_encrypt/BUILD.bazel and referenced by '//mace/codegen:encrypt_opencl_kernel_gen'
ERROR: /home/parallels/mace/mace/codegen/BUILD.bazel:26:1: no such target '@local_opencl_kernel_encrypt//:gen/encrypt_opencl_kernel.h': target 'gen/encrypt_opencl_kernel.h' not declared in package '' defined by /home/parallels/.cache/bazel/_bazel_parallels/5ff1ff2df121917af4fe9fa25c7709ef/external/local_opencl_kernel_encrypt/BUILD.bazel and referenced by '//mace/codegen:encrypt_opencl_kernel_gen'
ERROR: Analysis of target '//mace/libmace:libmace_dynamic' failed; build aborted: Loading failed
INFO: Elapsed time: 6.718s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (33 packages loaded)
```

**Comment by LovelyBuggies** [comment]
I think it **should** be okay to install jinja2 by pip, but not sure why #620 (forced to use apt or aptitude) happens?

**Comment by lee-bin** [comment]
@LovelyBuggies 
Please try this `pip install jinja2==2.10`.
I'm not sure about #620, may be different versions of python are used.

**Comment by LovelyBuggies** [comment]
> Please try this pip install jinja2==2.10.
> I'm not sure about #620, may be different versions of python are used.

Yeah, I tried, the fact is that I had jinja2==2.11.2 installed, but got `jinja2: no filter named to json` error when running `bash tools/bazel-build-standalone-lib.sh [-abi=abi][-runtimes=rt1,rt2,...][-static]`.

```bash
$ bash tools/bazel-build-standalone-lib.sh [-abi=abi][-runtimes=rt1,rt2,...][-static]
build shared lib for armeabi-v7a + cpu_gpu_dsp
Starting local Bazel server and connecting to it...
...........
write version v0.13.0-0-g9a06864 to /home/parallels/.cache/bazel/_bazel_parallels/5ff1ff2df121917af4fe9fa25c7709ef/external/local_version_config/gen/version
Traceback (most recent call last):
  File "/home/parallels/.cache/bazel/_bazel_parallels/5ff1ff2df121917af4fe9fa25c7709ef/external/mace//mace/python/tools/encrypt_opencl_codegen.py", line 20, in <module>
    import jinja2
ImportError: No module named jinja2
ERROR: /home/parallels/mace/mace/codegen/BUILD.bazel:26:1: no such target '@local_opencl_kernel_encrypt//:gen/encrypt_opencl_kernel.cc': target 'gen/encrypt_opencl_kernel.cc' not declared in package '' defined by /home/parallels/.cache/bazel/_bazel_parallels/5ff1ff2df121917af4fe9fa25c7709ef/external/local_opencl_kernel_encrypt/BUILD.bazel and referenced by '//mace/codegen:encrypt_opencl_kernel_gen'
ERROR: /home/parallels/mace/mace/codegen/BUILD.bazel:26:1: no such target '@local_opencl_kernel_encrypt//:gen/encrypt_opencl_kernel.h': target 'gen/encrypt_opencl_kernel.h' not declared in package '' defined by /home/parallels/.cache/bazel/_bazel_parallels/5ff1ff2df121917af4fe9fa25c7709ef/external/local_opencl_kernel_encrypt/BUILD.bazel and referenced by '//mace/codegen:encrypt_opencl_kernel_gen'
ERROR: Analysis of target '//mace/libmace:libmace_dynamic' failed; build aborted: Loading failed
INFO: Elapsed time: 6.132s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (33 packages loaded)

$ pip3 show jinja2
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Name: Jinja2
Version: 2.11.2
Summary: A very fast and expressive template engine.
Home-page: https://palletsprojects.com/p/jinja/
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: BSD-3-Clause
Location: /home/parallels/.local/lib/python3.5/site-packages
Requires: MarkupSafe
Required-by: 
```

**Comment by LovelyBuggies** [comment]
If I used the method at https://github.com/XiaoMi/mace/issues/620#issuecomment-608426958, i.e., using apt-get to install, the error `jinja2: no filter named to json` will occur because of the jinja2 version issue.

**Comment by lee-bin** [comment]
What's the output of `python --version`

**Comment by LovelyBuggies** [comment]
```bash
$ python --version
Python 2.7.12
$ python3 --version
Python 3.5.2
```

P.S. I am not using python2.

**Comment by lee-bin** [comment]
How do you ensure bazel use python3?

**Comment by LovelyBuggies** [comment]
> How do you ensure bazel use python3?

I cannot ensure, actually. Let me try 3.6+ and remove python2 :)
