### ISSUE TITLE
加入caffe后异常退出

### ISSUE THREAD

**Issue by hongsui169163** [XiaoMi/mace#66]
你好：
　　加入caffe后，报空指针异常退出
 Process: com.xiaomi.mace.demo, PID: 11333
 java.lang.NullPointerException: Attempt to get length of null array
at com.xiaomi.mace.demo.result.LabelCache.getResultFirst(LabelCache.java:67)
at com.xiaomi.mace.demo.AppModel$3.run(AppModel.java:68)
at android.os.Handler.handleCallback(Handler.java:836)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:203)
at android.os.HandlerThread.run(HandlerThread.java:61)

APPMODEL.java下面函数内
 public void maceMobilenetClassify(final float[] input) {
好像这一句返回为NULL　　　 float[] result = JniMaceUtils.maceMobilenetClassify(input);
这个CAFFE的数据是没问题的。

**Comment by lee-bin** [comment]
拉下最新代码

**Comment by lee-bin** [comment]
先关了，还有问题可随时打开。
