### ISSUE TITLE
How to generate PB for DSP runtime? 

### ISSUE THREAD

**Issue by samsun639** [XiaoMi/mace#69]
Reopen https://github.com/XiaoMi/mace/issues/59
@llhe Thanks for previous feedback!
I used this pb as input pb when do transform_graph, https://cnbj1.fds.api.xiaomi.com/mace/miai-models/inception-v3/inception-v3.pb
I believe it has been freezed. 

Checked https://cnbj1.fds.api.xiaomi.com/mace/miai-models/inception-v3/inception_v3_q_2015.pb, It also has placeholder node, not removed. 

Could you reproduce this issue ? ((even though I  used remove_nodes(op=Placeholder)) when transform_graph)

----------------------------- CallTrace -------------------------------------

Traceback (most recent call last):
  File "/local/mnt/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 300, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/local/mnt/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 104, in main
    FLAGS.dsp_mode)
  File "/local/mnt/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/tf_dsp_converter_lib.py", line 594, in convert_to_mace_pb
    dsp_ops)
  File "/local/mnt/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/tf_dsp_converter_lib.py", line 140, in convert_ops
    tf_tensor = first_op.outputs[0].eval()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 656, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 5016, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input' with dtype float and shape [?,299,299,3]
	 [[Node: input = Placeholder[dtype=DT_FLOAT, shape=[?,299,299,3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by springishere** [comment]
I have a similar issue when trying to use quantized model for DSP, however I think we all want to know how you generated the inception_v3_q_2015.pb.
I used quantize_graph.py to quantize mace's inception_v3 pb (Downloaded from https://cnbj1.fds.api.xiaomi.com/mace/miai-models/inception-v3/inception-v3.pb)

python quantize_graph.py --input=/xiaomi/mace-models/inception-v3.pb --output_node_names="InceptionV3/Predictions/Reshape_1" --output=/tmp/quantized_graph.pb --mode=eightbit

However when I try to 'convert' I have this error:
...
('Op: ', u'InceptionV3/Conv2d_1a_3x3/weights_min', u'Const', TensorShape([]))
('Add const node: ', u'InceptionV3/Conv2d_1a_3x3/weights_min')
('Op: ', u'InceptionV3/Conv2d_1a_3x3/weights_quint8_const', u'Const', TensorShape([Dimension(3), Dimension(3), Dimension(3), Dimension(32)]))
('Add const node: ', u'InceptionV3/Conv2d_1a_3x3/weights_quint8_const')
('Op: ', u'input', u'Placeholder', TensorShape([Dimension(None), Dimension(299), Dimension(299), Dimension(3)]))
Traceback (most recent call last):
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 300, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 104, in main
    FLAGS.dsp_mode)
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/tf_dsp_converter_lib.py", line 600, in convert_to_mace_pb
    dsp_ops)
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/tf_dsp_converter_lib.py", line 355, in convert_ops
    convert_op_outputs(op_def, first_op)
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/tf_dsp_converter_lib.py", line 115, in convert_op_outputs
    [max_elem_size(output) for output in tf_op.outputs])
  File "/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/tf_dsp_converter_lib.py", line 74, in max_elem_size
    return reduce(mul, tensor.shape.as_list()) * tensor.dtype.size
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
Traceback (most recent call last):
  File "tools/converter.py", line 1580, in <module>
    flags.func(flags)
  File "tools/converter.py", line 785, in convert_func
    convert_model(configs)
  File "tools/converter.py", line 711, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/mace/tools/sh_commands.py", line 530, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=/tmp/quantized_graph.pb --weight_file= --model_checksum=00dc44a6c49bca14d459695eae992f954e711446fb90cd706f57529a54f9fc30 --weight_checksum= --input_node=Mul --output_node=softmax --runtime=dsp --template=mace/python/tools --model_tag=inception_v3_dsp --input_shape=1,299,299,3 --dsp_mode=4 --embed_model_data=False --winograd=0 --obfuscate=1 --output_dir=mace/codegen/models/inception_v3_dsp --model_graph_format=file --data_type=uint8 --graph_optimize_options=

**Comment by chanchanzhang** [comment]
@samsun639 
I got a similiar error recently, check if it is same with https://github.com/XiaoMi/mace/issues/106

**Comment by liyinhgqw** [comment]
We have updated docs and dsp transformer, it is about to merge today.
I will notice you when it' merged

**Comment by liyinhgqw** [comment]
@samsun639 @springishere 
Please try master code and see if it is solved.
