### ISSUE TITLE
Error question when using converter.py and yml files

### ISSUE THREAD

**Issue by chartores** [XiaoMi/mace#692]
Thank you lu229 for your help every time.

First, there was no problem with creating "cpm.a" with the default "cpm.yml" file and building and running on Android.
(https://github.com/edvardHua/PoseEstimationForMobile/blob/master/release/mace_ymls/cpm.yml)

I have a question about an error that occurs when using converter.py and yml files.

The yml file is completed with the command below.
And an error occurred while making xxx.a with converter.py file.

I made it by referring to the document, but I would like to make sure that I have done it again.

Question 1: When writing a yml file, I know that the'model_file_path' item writes the path of the xxx.pb file. Is that right?

Question 2: When writing a yml file, is it correct to write the result of'model_sha256_checksum' through the following command (sha256 sum /path/to/your/file) using the path of the xxx.pb file?

The input was the same.
The output was changed because the result was human body (14 points) -> human hand (21 points).

-cmd line------------------------------------------------------------------
```
# Get device's soc info.
adb shell getprop | grep platform

# command for generating sha256_sum
sha256 sum /path/to/your/file

python tools/converter.py convert --config=/home/peng_ai/PoseEstimationForMobile/release/mace_ymls/cpm.yml
```

-cpm.yml file------------------------------------------------------------------
```
library_name: cpm
target_abis: [armeabi-v7a]
model_graph_format: code
model_data_format: code
models:
  cpm_v1: # model tag, which will be used in model loading and must be specific.
    platform: tensorflow
    # path to your tensorflow model's pb file. Support local path, http:// and https://
    model_file_path: /home/peng_ai/PoseEstimationForMobile/trained/mv2_cpm_tiny/models/model-124940.pb
    # sha256_checksum of your model's pb file.
    model_sha256_checksum: 909cd0cf242c8b29219f890128b7ffd34a6a3ac424998a934e35f8ac60f9fcfe
    subgraphs:
      - input_tensors:
          - image
        input_shapes:
          - 1,192,192,3
        output_tensors:
          - Convolutional_Pose_Machine/stage_5_out
        output_shapes:
          - 1,96,96,21
    # cpu, gpu or cpu+gpu
    runtime: cpu+gpu
    winograd: 0

```
-error msg------------------------------------------------------------------
```
--------------------------------------
         Common Configuration         
--------------------------------------
|        key        |     value      |
======================================
|       library_name|             cpm|
--------------------------------------
|        target_abis| ['armeabi-v7a']|
--------------------------------------
|        target_socs|              []|
--------------------------------------
| model_graph_format|            code|
--------------------------------------
|  model_data_format|            code|
--------------------------------------

* Generate mace engine creator source
Generate mace engine creator source done!

****************************************
          Convert cpm_v1 model          
****************************************

INFO: Analysed target //mace/python/tools:converter (0 packages loaded).
INFO: Found 1 target...
INFO: From ProtoCompile mace/proto/mace_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/any_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile third_party/caffe/caffe_pb2.py:
external/com_google_protobuf/python: warning: directory does not exist.
Target //mace/python/tools:converter up-to-date:
  bazel-bin/mace/python/tools/converter
INFO: Elapsed time: 1.676s, Critical Path: 0.72s
INFO: 7 processes, linux-sandbox.
INFO: Build completed successfully, 8 total actions

Transform model to one that can better run on device
Traceback (most recent call last):
  File "/home/peng_ai/mace-0.9/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 305, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/peng_ai/mace-0.9/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 134, in main
    option, FLAGS.model_file)
  File "/home/peng_ai/mace-0.9/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 210, in __init__
    tf.import_graph_def(tf_graph_def, name='')
  File "/home/peng_ai/anaconda3/envs/mace-0.9/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/home/peng_ai/anaconda3/envs/mace-0.9/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 540, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named FusedBatchNormV3 in defined operations.
Traceback (most recent call last):
  File "tools/converter.py", line 1609, in <module>
    flags.func(flags)
  File "tools/converter.py", line 793, in convert_func
    convert_model(configs)
  File "tools/converter.py", line 719, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/peng_ai/mace-0.9/tools/sh_commands.py", line 524, in gen_model_code
    _fg=True)
  File "/home/peng_ai/anaconda3/envs/mace-0.9/lib/python2.7/site-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/peng_ai/anaconda3/envs/mace-0.9/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=/home/peng_ai/PoseEstimationForMobile/trained/mv2_cpm_tiny/models/model-124940.pb --weight_file= --model_checksum=909cd0cf242c8b29219f890128b7ffd34a6a3ac424998a934e35f8ac60f9fcfe --weight_checksum= --input_node=image --output_node=Convolutional_Pose_Machine/stage_5_out --runtime=cpu+gpu --template=mace/python/tools --model_tag=cpm_v1 --input_shape=1,192,192,3 --dsp_mode=0 --embed_model_data=True --winograd=0 --obfuscate=0 --output_dir=mace/codegen/models/cpm_v1 --model_graph_format=code --data_type=fp16_fp32 --graph_optimize_options=

  STDOUT:


  STDERR:
```

**Comment by lu229** [comment]
@chartores 
Answer 1: yes it is right
Answer 1: yes it is correct

The error is: `No op named FusedBatchNormV3 in defined operations`, which is caused by the TensorFlow version. MACE uses TensorFlow to import the model, it seems that the version MACE used is lower than the TensorFlow version used to train the model. You can fix this error by updating the TensorFlow version.
