### ISSUE TITLE
ndk-depends: not found

### ISSUE THREAD

**Issue by gasgallo** [XiaoMi/mace#707]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **NDK version(e.g., 15c)**: 19c
- **GCC version(if compiling for host, e.g., 5.4.0)**: 5.4.0
- **MACE version (Use the command: git describe --long --tags)**: 0.13.0
- **Python version(2.7)**: 3.6
- **Bazel version (e.g., 0.13.0)**: 0.16.0
- **CMake version**: 3.16.0

### Model deploy file (*.yml)
```yaml
```

### Describe the problem
When following the documentation to run a model using CMake (https://mace.readthedocs.io/en/latest/user_guide/basic_usage_cmake.html#model-test-and-benchmark), I get an error related to NDK. Everything works fine when using Bazel instead (https://mace.readthedocs.io/en/latest/user_guide/basic_usage.html#build-and-run-an-example-model).

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. tools/clear_workspace.sh [--expunge]
3. python3 tools/python/convert.py --config <path_to_yml_file>
4. python3 tools/python/run_model.py --config <path_to_yml_file>
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
root@23284e2024d3:/mace-toolkit/mace# python3 tools/python/run_model.py --config=$(pwd)/../models/model.yml
CMD> bazel version
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Build label: 0.16.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jul 31 17:01:24 2018 (1533056484)
Build timestamp: 1533056484
Build timestamp as int: 1533056484

CMD> bazel build //mace/proto:mace_py
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Loading:
Loading: 0 packages loaded
Analyzing: target //mace/proto:mace_py (13 packages loaded)
INFO: Analysed target //mace/proto:mace_py (17 packages loaded).
INFO: Found 1 target...
[0 / 18] [-----] BazelWorkspaceStatusAction stable-status.txt
Target //mace/proto:mace_py up-to-date:
bazel-genfiles/mace/proto/mace_pb2.py
INFO: Elapsed time: 1.613s, Critical Path: 0.06s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action

CMD> cp -f bazel-genfiles/mace/proto/mace_pb2.py /mace-toolkit/mace/tools/python/py_proto

CMD> bazel build //mace/proto:micro_mem_py
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Loading:
Loading: 0 packages loaded
INFO: Analysed target //mace/proto:micro_mem_py (17 packages loaded).
Building: no action
INFO: Found 1 target...
[2 / 20] [-----] BazelWorkspaceStatusAction stable-status.txt
Target //mace/proto:micro_mem_py up-to-date:
bazel-genfiles/mace/proto/micro_mem_pb2.py
INFO: Elapsed time: 1.608s, Critical Path: 0.05s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action

CMD> cp -f bazel-genfiles/mace/proto/micro_mem_pb2.py /mace-toolkit/mace/tools/python/py_proto

CMD> bazel build //third_party/caffe:caffe_py
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Loading:
Loading: 0 packages loaded
Analyzing: target //third_party/caffe:caffe_py (17 packages loaded)
INFO: Analysed target //third_party/caffe:caffe_py (17 packages loaded).
INFO: Found 1 target...
[2 / 19] [-----] BazelWorkspaceStatusAction stable-status.txt
Target //third_party/caffe:caffe_py up-to-date:
bazel-genfiles/third_party/caffe/caffe_pb2.py
INFO: Elapsed time: 1.630s, Critical Path: 0.06s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action

CMD> cp -f bazel-genfiles/third_party/caffe/caffe_pb2.py /mace-toolkit/mace/tools/python/py_proto

CMD> adb devices
List of devices attached
2DR4C18B21003741	device


tools/python/run_model.py:73: Run on devices: ['2DR4C18B21003741']
tools/python/run_model.py:84: Run model face_detector
{'output_data_formats': [<DataFormat.NCHW: 2>, <DataFormat.NCHW: 2>, <DataFormat.NCHW: 2>, <DataFormat.NCHW: 2>, <DataFormat.NCHW: 2>, <DataFormat.NCHW: 2>, <DataFormat.NCHW: 2>, <DataFormat.NCHW: 2>, <DataFormat.NCHW: 2>], 'original_model_sha256_checksum': 'f306bba08dea145d932922d02f4b2df97754bedd653ae189b29dfe6d8113c1ae', 'platform': <Platform.CAFFE: 1>, 'output_tensors': ['face_rpn_cls_prob_reshape_stride32', 'face_rpn_bbox_pred_stride32', 'face_rpn_landmark_pred_stride32', 'face_rpn_cls_prob_reshape_stride16', 'face_rpn_bbox_pred_stride16', 'face_rpn_landmark_pred_stride16', 'face_rpn_cls_prob_reshape_stride8', 'face_rpn_bbox_pred_stride8', 'face_rpn_landmark_pred_stride8'], 'obfuscate': 0, 'winograd': 2, 'weight_file_path': '/data/face-models/retina_caffe/caffe_25_160.caffemodel', 'output_data_types': [1, 1, 1, 1, 1, 1, 1, 1, 1], 'model_sha256_checksum': '213d764bd605d02b1630740969ab7110a2ee0111e3f8200ce02304cf72fbd42a', 'input_data_types': [1], 'weight_sha256_checksum': 'c83d575645daf8541867a63197de6bfd44a7fb3bf9bf4c876cde8165c23fac0c', 'input_shapes': [[1, 3, 160, 160]], 'model_file_path': '/data/face-models/retina_caffe/caffe_25_160.prototxt', 'output_shapes': [[1, 4, 5, 5], [1, 8, 5, 5], [1, 20, 5, 5], [1, 4, 10, 10], [1, 8, 10, 10], [1, 20, 10, 10], [1, 4, 20, 20], [1, 8, 20, 20], [1, 20, 20, 20]], 'original_weight_sha256_checksum': '051313a2e7e62e981aafcf0dd5cb16505eca4295c4d2f6f36749a173eda8413c', 'input_ranges': [[-1.0, 1.0]], 'input_tensors': ['data'], 'data_type': 3, 'runtime': <DeviceType.CPU: 0>, 'input_data_formats': [<DataFormat.NCHW: 2>]}
CMD> adb -s 2DR4C18B21003741 shell mkdir -p /data/local/tmp/mace_run/face_detector/interior

CMD> adb -s 2DR4C18B21003741 shell mkdir -p /data/local/tmp/mace_run/face_detector

CMD> adb -s 2DR4C18B21003741 push build/face_detector/model/face_detector.pb /data/local/tmp/mace_run/face_detector
CMD> adb -s 2DR4C18B21003741 shell mkdir -p /data/local/tmp/mace_run/face_detector

CMD> adb -s 2DR4C18B21003741 push build/face_detector/model/face_detector.data /data/local/tmp/mace_run/face_detector
CMD> adb devices
List of devices attached
2DR4C18B21003741	device


Run on devices: ['2DR4C18B21003741']
Install target from build/cmake-build/arm64-v8a/install/bin/mace_run to /data/local/tmp/mace_run/face_detector
CMD> adb -s 2DR4C18B21003741 shell mkdir -p /data/local/tmp/mace_run/face_detector

CMD> adb -s 2DR4C18B21003741 push build/cmake-build/arm64-v8a/install/bin/mace_run /data/local/tmp/mace_run/face_detector

CMD> /opt/android-ndk-r19c/ndk-depends build/cmake-build/arm64-v8a/install/bin/mace_run
/bin/sh: 1: /opt/android-ndk-r19c/ndk-depends: not found


Traceback (most recent call last):
  File "tools/python/run_model.py", line 379, in <module>
    run_models(flags, args)
  File "tools/python/run_model.py", line 77, in run_models
    run_models_for_device(flags, args, dev)
  File "tools/python/run_model.py", line 86, in run_models_for_device
    run_model_for_device(flags, args, dev, name, model_conf)
  File "tools/python/run_model.py", line 204, in run_model_for_device
    device_ids=flags.target_socs)
  File "/mace-toolkit/mace/tools/python/run_target.py", line 51, in run_target
    device_target = dev.install(target_obj, install_dir, install_deps=True)
  File "/mace-toolkit/mace/tools/python/utils/device.py", line 167, in install
    self.install_common_libs_for_target(target, install_dir)
  File "/mace-toolkit/mace/tools/python/utils/device.py", line 174, in install_common_libs_for_target
    + target.path)
  File "/mace-toolkit/mace/tools/python/utils/device.py", line 60, in execute
    raise Exception("errorcode: %s" % p.returncode)
Exception: errorcode: 127

```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by lu229** [comment]
@gasgallo Sorry, the `ndk-depends` is not exist in `ndk` 19c, you can copy it from ndk 16 or the low versions.
