### ISSUE TITLE
Got "'device_' Must not be NULL" error when running a model coverted by CMake on Android

### ISSUE THREAD

**Issue by mexeniz** [XiaoMi/mace#713]
Before you open an issue, please make sure you have tried the following steps:

1. Make sure your **environment** is the same with (https://mace.readthedocs.io/en/latest/installation/env_requirement.html).
2. Have you ever read the document for your usage?
3. Check if your issue appears in [HOW-TO-DEBUG](https://mace.readthedocs.io/en/latest/development/how_to_debug.html) or [FAQ](https://mace.readthedocs.io/en/latest/faq.html).
4. The form below must be filled.

------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Docker Ubuntu 18.04
- **NDK version(e.g., 15c)**: r16b
- **GCC version(if compiling for host, e.g., 5.4.0)**: 5.4.0
- **MACE version (Use the command: git describe --long --tags)**: v1.0.2
- **Python version(2.7)**: 3.6.12
- **Bazel version (e.g., 0.13.0)**: 0.16.0
- **CMake version **: 3.16.5

### Model deploy file (*.yml)
```yaml
library_name: mobilenet
target_abis: [arm64-v8a]
target_socs:
- msmnile
model_graph_format: code
model_data_format: code
models:
  mobilenet_v1:
    platform: tensorflow
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v1/mobilenet-v1-1.0.pb
    model_sha256_checksum: 71b10f540ece33c49a7b51f5d4095fc9bd78ce46ebf0300487b2ee23d71294e6
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,224,224,3
        output_tensors:
          - MobilenetV1/Predictions/Reshape_1
        output_shapes:
          - 1,1001
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    obfuscate: 0
    winograd: 0
  mobilenet_v2:
    platform: tensorflow
    model_file_path: https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v2/mobilenet-v2-1.0.pb
    model_sha256_checksum: 369f9a5f38f3c15b4311c1c84c032ce868da9f371b5f78c13d3ea3c537389bb4
    subgraphs:
      - input_tensors:
          - input
        input_shapes:
          - 1,224,224,3
        output_tensors:
          - MobilenetV2/Predictions/Reshape_1
        output_shapes:
          - 1,1001
    runtime: cpu+gpu
    limit_opencl_kernel_time: 0
    obfuscate: 0
    winograd: 0

```

### Describe the problem
A script cannot run a model on an Android device (Xiaomi Mi 9) because it throws `'device_' Must not be NULL` error.
I am trying to tune OpenCL kernel so I need to specify `target_socs` in the model config. However, I cannot manage to run the model.

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. bash ./tools/cmake/cmake-build-arm64-v8a.sh
3. python3 tools/python/convert.py --config=./mobilenet.yml
4. python3 tools/python/run_model.py --config=./mobilenet.yml --tune
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
root@dfca3c5f8303:/mace-toolkit/mace# python3 tools/python/run_model.py --config=./mobilenet.yml 
CMD> bazel build //mace/proto:mace_py
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Loading:
Loading: 0 packages loaded
Analyzing: target //mace/proto:mace_py (11 packages loaded)
INFO: Analysed target //mace/proto:mace_py (17 packages loaded).
INFO: Found 1 target...
[0 / 15] [-----] BazelWorkspaceStatusAction stable-status.txt
Target //mace/proto:mace_py up-to-date:
bazel-genfiles/mace/proto/mace_pb2.py
INFO: Elapsed time: 1.883s, Critical Path: 0.04s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action

CMD> cp -f bazel-genfiles/mace/proto/mace_pb2.py /mace-toolkit/mace/tools/python/py_proto

CMD> bazel build //mace/proto:micro_mem_py
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Loading:
Loading: 0 packages loaded
Analyzing: target //mace/proto:micro_mem_py (8 packages loaded)
INFO: Analysed target //mace/proto:micro_mem_py (17 packages loaded).
INFO: Found 1 target...
[0 / 2] [-----] BazelWorkspaceStatusAction stable-status.txt
Target //mace/proto:micro_mem_py up-to-date:
bazel-genfiles/mace/proto/micro_mem_pb2.py
INFO: Elapsed time: 1.876s, Critical Path: 0.04s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action

CMD> cp -f bazel-genfiles/mace/proto/micro_mem_pb2.py /mace-toolkit/mace/tools/python/py_proto

CMD> bazel build //third_party/caffe:caffe_py
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Loading:
Loading: 0 packages loaded
Analyzing: target //third_party/caffe:caffe_py (9 packages loaded)
INFO: Analysed target //third_party/caffe:caffe_py (17 packages loaded).
INFO: Found 1 target...
[0 / 2] [-----] BazelWorkspaceStatusAction stable-status.txt
Target //third_party/caffe:caffe_py up-to-date:
bazel-genfiles/third_party/caffe/caffe_pb2.py
INFO: Elapsed time: 2.006s, Critical Path: 0.04s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action

CMD> cp -f bazel-genfiles/third_party/caffe/caffe_pb2.py /mace-toolkit/mace/tools/python/py_proto

CMD> adb devices
List of devices attached
b1524f99	device


tools/python/run_model.py:75: Run on devices: ['b1524f99']
tools/python/run_model.py:86: Run model mobilenet_v1
{'platform': <Platform.TENSORFLOW: 0>, 'model_file_path': 'https://cnbj1.fds.api.xiaomi.com/mace/miai-models/mobilenet-v1/mobilenet-v1-1.0.pb', 'model_sha256_checksum': '71b10f540ece33c49a7b51f5d4095fc9bd78ce46ebf0300487b2ee23d71294e6', 'runtime': <DeviceType.CPU_GPU: 100>, 'limit_opencl_kernel_time': 0, 'obfuscate': 0, 'winograd': 0, 'input_tensors': ['input'], 'input_shapes': [[1, 224, 224, 3]], 'output_tensors': ['MobilenetV1/Predictions/Reshape_1'], 'output_shapes': [[1, 1001]], 'data_type': 3, 'input_data_types': [1], 'input_data_formats': [<DataFormat.NHWC: 1>], 'input_ranges': [[-1.0, 1.0]], 'output_data_types': [1], 'output_data_formats': [<DataFormat.NHWC: 1>]}
CMD> adb -s b1524f99 shell mkdir -p /data/local/tmp/mace_run/mobilenet_v1/interior

CMD> adb -s b1524f99 shell mkdir -p /data/local/tmp/mace_run/mobilenet_v1

CMD> adb -s b1524f99 push build/mobilenet_v1/model/mobilenet_v1.pb /data/local/tmp/mace_run/mobilenet_v1
CMD> adb -s b1524f99 shell mkdir -p /data/local/tmp/mace_run/mobilenet_v1

CMD> adb -s b1524f99 push build/mobilenet_v1/model/mobilenet_v1.data /data/local/tmp/mace_run/mobilenet_v1
CMD> adb devices
List of devices attached
b1524f99	device


Run on devices: ['b1524f99']
Install target from build/cmake-build/arm64-v8a/install/bin/mace_run to /data/local/tmp/mace_run/mobilenet_v1
CMD> adb -s b1524f99 shell mkdir -p /data/local/tmp/mace_run/mobilenet_v1

CMD> adb -s b1524f99 push build/cmake-build/arm64-v8a/install/bin/mace_run /data/local/tmp/mace_run/mobilenet_v1
CMD> /opt/android-ndk/ndk-depends build/cmake-build/arm64-v8a/install/bin/mace_run
WARNING: Could not find library: libc++_shared.so
mace_run
libm.so
liblog.so
libdl.so
libc.so
libc++_shared.so

CMD> adb -s b1524f99 push /opt/android-ndk/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++_shared.so /data/local/tmp/mace_run/mobilenet_v1
['', 'MACE_INTERNAL_STORAGE_PATH=/data/local/tmp/mace_run/mobilenet_v1/interior', 'LD_LIBRARY_PATH=/data/local/tmp/mace_run/mobilenet_v1', '/data/local/tmp/mace_run/mobilenet_v1/mace_run', "--model_name='mobilenet_v1'", "--model_file='/data/local/tmp/mace_run/mobilenet_v1/mobilenet_v1.pb'", "--model_data_file='/data/local/tmp/mace_run/mobilenet_v1/mobilenet_v1.data'", "--input_node='input'", "--input_shape='1,224,224,3'", "--output_node='MobilenetV1/Predictions/Reshape_1'", "--output_shape='1,1001'", "--input_data_format='NHWC'", "--output_data_format='NHWC'", "--device='GPU'"]
 MACE_INTERNAL_STORAGE_PATH=/data/local/tmp/mace_run/mobilenet_v1/interior LD_LIBRARY_PATH=/data/local/tmp/mace_run/mobilenet_v1 /data/local/tmp/mace_run/mobilenet_v1/mace_run --model_name='mobilenet_v1' --model_file='/data/local/tmp/mace_run/mobilenet_v1/mobilenet_v1.pb' --model_data_file='/data/local/tmp/mace_run/mobilenet_v1/mobilenet_v1.data' --input_node='input' --input_shape='1,224,224,3' --output_node='MobilenetV1/Predictions/Reshape_1' --output_shape='1,1001' --input_data_format='NHWC' --output_data_format='NHWC' --device='GPU'
Runing ...
['', 'MACE_INTERNAL_STORAGE_PATH=/data/local/tmp/mace_run/mobilenet_v1/interior', 'LD_LIBRARY_PATH=/data/local/tmp/mace_run/mobilenet_v1', '/data/local/tmp/mace_run/mobilenet_v1/mace_run', "--model_name='mobilenet_v1'", "--model_file='/data/local/tmp/mace_run/mobilenet_v1/mobilenet_v1.pb'", "--model_data_file='/data/local/tmp/mace_run/mobilenet_v1/mobilenet_v1.data'", "--input_node='input'", "--input_shape='1,224,224,3'", "--output_node='MobilenetV1/Predictions/Reshape_1'", "--output_shape='1,1001'", "--input_data_format='NHWC'", "--output_data_format='NHWC'", "--device='GPU'"]
CMD> adb -s b1524f99 push /tmp/tmpi6_g6shu/cmd.sh /data/local/tmp/mace_run/mobilenet_v1
228 KB/s (541 bytes in 0.002s)

CMD> adb -s b1524f99 shell sh /data/local/tmp/mace_run/mobilenet_v1/cmd.sh
I /mace-toolkit/mace/mace/tools/mace_run.cc:550] model name: mobilenet_v1
I /mace-toolkit/mace/mace/tools/mace_run.cc:551] mace version: v1.0.2-0-gd5ae855
I /mace-toolkit/mace/mace/tools/mace_run.cc:552] input node: input
I /mace-toolkit/mace/mace/tools/mace_run.cc:553] input shape: 1,224,224,3
I /mace-toolkit/mace/mace/tools/mace_run.cc:554] output node: MobilenetV1/Predictions/Reshape_1
I /mace-toolkit/mace/mace/tools/mace_run.cc:555] output shape: 1,1001
I /mace-toolkit/mace/mace/tools/mace_run.cc:556] input_file:
I /mace-toolkit/mace/mace/tools/mace_run.cc:557] output_file:
I /mace-toolkit/mace/mace/tools/mace_run.cc:558] input dir:
I /mace-toolkit/mace/mace/tools/mace_run.cc:559] output dir: output
I /mace-toolkit/mace/mace/tools/mace_run.cc:560] model_data_file: /data/local/tmp/mace_run/mobilenet_v1/mobilenet_v1.data
I /mace-toolkit/mace/mace/tools/mace_run.cc:561] model_file: /data/local/tmp/mace_run/mobilenet_v1/mobilenet_v1.pb
I /mace-toolkit/mace/mace/tools/mace_run.cc:562] apu_cache_policy: 0
I /mace-toolkit/mace/mace/tools/mace_run.cc:563] apu_binary_file:
I /mace-toolkit/mace/mace/tools/mace_run.cc:564] apu_storage_file:
I /mace-toolkit/mace/mace/tools/mace_run.cc:565] device: GPU
I /mace-toolkit/mace/mace/tools/mace_run.cc:566] round: 1
I /mace-toolkit/mace/mace/tools/mace_run.cc:567] restart_round: 1
I /mace-toolkit/mace/mace/tools/mace_run.cc:568] gpu_perf_hint: 3
I /mace-toolkit/mace/mace/tools/mace_run.cc:569] gpu_priority_hint: 3
I /mace-toolkit/mace/mace/tools/mace_run.cc:570] num_threads: -1
I /mace-toolkit/mace/mace/tools/mace_run.cc:571] cpu_affinity_policy: 1
I /mace-toolkit/mace/mace/libmace/mace.cc:558] Creating MaceEngine, MACE version: v1.0.2-0-gd5ae855
I /mace-toolkit/mace/mace/libmace/mace.cc:628] Initializing MaceEngine
I /mace-toolkit/mace/mace/libmace/mace.cc:790] Destroying MaceEngine
I /mace-toolkit/mace/mace/tools/mace_run.cc:622] restart round 0
I /mace-toolkit/mace/mace/libmace/mace.cc:1150] Create MaceEngine from model graph proto and weights data
I /mace-toolkit/mace/mace/libmace/mace.cc:558] Creating MaceEngine, MACE version: v1.0.2-0-gd5ae855
F /mace-toolkit/mace/mace/libmace/mace.cc:606] 'device_' Must not be NULL
F /mace-toolkit/mace/mace/libmace/mace.cc:606] backtrace:
F /mace-toolkit/mace/mace/libmace/mace.cc:606]  pc 0x5e258ba278
F /mace-toolkit/mace/mace/libmace/mace.cc:606]  pc 0x5e258b98ac
F /mace-toolkit/mace/mace/libmace/mace.cc:606]  pc 0x5e258c0764
F /mace-toolkit/mace/mace/libmace/mace.cc:606]  pc 0x5e258c0644
F /mace-toolkit/mace/mace/libmace/mace.cc:606]  pc 0x5e258c0c64
F /mace-toolkit/mace/mace/libmace/mace.cc:606]  pc 0x5e258c0cb4
F /mace-toolkit/mace/mace/libmace/mace.cc:606]  pc 0x5e2562a900
F /mace-toolkit/mace/mace/libmace/mace.cc:606]  pc 0x5e2562a38c
F /mace-toolkit/mace/mace/libmace/mace.cc:606]  pc 0x5e2563d288
F /mace-toolkit/mace/mace/libmace/mace.cc:606]  pc 0x5e2563d238
F /mace-toolkit/mace/mace/libmace/mace.cc:606]  pc 0x5e2563d5fc
F /mace-toolkit/mace/mace/libmace/mace.cc:606]  pc 0x5e255f696c
F /mace-toolkit/mace/mace/libmace/mace.cc:606]  pc 0x5e255ffa44
F /mace-toolkit/mace/mace/libmace/mace.cc:606]  pc 0x5e25600808
F /mace-toolkit/mace/mace/libmace/mace.cc:606]  pc 0x735867dbc8 __libc_init
Aborted

CMD> adb -s b1524f99 shell getprop
CMD> adb -s b1524f99 shell getprop
CMD> adb -s b1524f99 pull /data/local/tmp/mace_run/mobilenet_v1/interior/mace_cl_compiled_program.bin build/mobilenet_v1/opencl/mobilenet_v1_compiled_opencl_kernel.MI9.msmnile.bin
Traceback (most recent call last):
  File "tools/python/run_model.py", line 385, in <module>
    run_models(flags, args)
  File "tools/python/run_model.py", line 79, in run_models
    run_models_for_device(flags, args, dev)
  File "tools/python/run_model.py", line 88, in run_models_for_device
    run_model_for_device(flags, args, dev, name, model_conf)
  File "tools/python/run_model.py", line 219, in run_model_for_device
    dev.info()["ro.board.platform"]))
  File "/mace-toolkit/mace/tools/python/utils/device.py", line 213, in pull
    execute("adb -s %s pull %s %s" % (sn, target.path, out_dir), False)
  File "/mace-toolkit/mace/tools/python/utils/device.py", line 43, in execute
    raise Exception("errorcode: {}".format(p.returncode))
Exception: errorcode: 1

```

### Additional context
Add any other context about the problem here, e.g., what you have modified about the code.

**Comment by mexeniz** [comment]
Sorry, it was my mistake that I built `libmace` without GPU-runtime support. I fixed the command building `libmace` like the below and tested again. The OpenCL tuning works now.
```
1. cd /path/to/mace
2. RUNTIME=GPU QUANTIZE=OFF bash ./tools/cmake/cmake-build-arm64-v8a.sh
3. python3 tools/python/convert.py --config=./mobilenet.yml
4. python3 tools/python/run_model.py --config=./mobilenet.yml --tune
```
