### ISSUE TITLE
Convert 转换模型报错：C++ compilation of rule '//mace/codegen:generated_models' failed

### ISSUE THREAD

**Issue by ddz-mark** [XiaoMi/mace#755]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 16.04
- **NDK version(e.g., 15c)**: r17c
- **GCC version(if compiling for host, e.g., 5.4.0)**: 5.4.0
- **MACE version (Use the command: git describe --long --tags)**:  v1.0.2-d5ae855a
- **Python version(2.7)**:  3.6.13
- **Bazel version (e.g., 0.13.0)**: 0.13.0

### Model deploy file (*.yml)
```yaml
../mace-models/mobilenet-v2/mobilenet-v2.yml
```

### Describe the problem
1. 编译可以成功：build tools/bazel_build_standalone_lib.sh
2. 转化模型报错：C++ compilation of rule '//mace/codegen:generated_models' failed

### To Reproduce
Steps to reproduce the problem:
```bash
1. cd /path/to/mace
2. python tools/converter.py convert --config_file=../mace-models/mobilenet-v2/mobilenet-v2.yml
```

### Error information / logs
Please include the **full** log and/or traceback here.
```bash
************************************************
          Model mobilenet_v2 converted          
************************************************

******************************************
          Building model library          
******************************************

* Build //mace/codegen:generated_models with ABI armeabi-v7a
INFO: Analysed target //mace/codegen:generated_models (0 packages loaded).
INFO: Found 1 target...
ERROR: /home/mark/github/mace/mace/codegen/BUILD.bazel:10:1: C++ compilation of rule '//mace/codegen:generated_models' failed (Exit 254): clang failed: error executing command 
  (cd /home/mark/.cache/bazel/_bazel_mark/b4948deb474a6dadcd57006a6b3d1995/execroot/mace && \
  exec env - \
    PWD=/proc/self/cwd \
  external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -fno-integrated-as -target armv7-none-linux-androideabi '-march=armv7-a' '-mfloat-abi=softfp' '-mfpu=vfpv3-d16' -mthumb -Os -g -DNDEBUG -MD -MF bazel-out/armeabi-v7a-opt/bin/mace/codegen/_objs/generated_models/mace/codegen/models/mobilenet_v2/code/tensor_data.d '-frandom-seed=bazel-out/armeabi-v7a-opt/bin/mace/codegen/_objs/generated_models/mace/codegen/models/mobilenet_v2/code/tensor_data.o' -iquote . -iquote bazel-out/armeabi-v7a-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/armeabi-v7a-opt/genfiles/external/bazel_tools -iquote external/com_google_protobuf -iquote bazel-out/armeabi-v7a-opt/genfiles/external/com_google_protobuf -iquote external/half -iquote bazel-out/armeabi-v7a-opt/genfiles/external/half -iquote external/opencl_clhpp -iquote bazel-out/armeabi-v7a-opt/genfiles/external/opencl_clhpp -iquote external/opencl_headers -iquote bazel-out/armeabi-v7a-opt/genfiles/external/opencl_headers -Ibazel-out/armeabi-v7a-opt/bin/include/_virtual_includes/public_headers -Ibazel-out/armeabi-v7a-opt/bin/external/opencl_headers/_virtual_includes/opencl20_headers -isystem external/com_google_protobuf/src -isystem bazel-out/armeabi-v7a-opt/genfiles/external/com_google_protobuf/src -isystem bazel-out/armeabi-v7a-opt/bin/external/com_google_protobuf/src -isystem external/opencl_clhpp/include -isystem bazel-out/armeabi-v7a-opt/genfiles/external/opencl_clhpp/include -isystem bazel-out/armeabi-v7a-opt/bin/external/opencl_clhpp/include '-std=c++11' -fPIC -D_GLIBCXX_USE_C99_MATH_TR1 -DMACE_OBFUSCATE_LITERALS -DGEMMLOWP_USE_MACE_THREAD_POOL -DMACE_DEPTHWISE_U8_USE_MULTI_THREAD -O2 '-std=c++11' -fPIC -D_GLIBCXX_USE_C99_MATH_TR1 -DMACE_OBFUSCATE_LITERALS -DGEMMLOWP_USE_MACE_THREAD_POOL -DMACE_DEPTHWISE_U8_USE_MULTI_THREAD -O2 -Oz -Wall -Wno-mismatched-tags -Wno-missing-braces -Oz -Wall -Wno-mismatched-tags -Wno-missing-braces -ffunction-sections -fdata-sections -fno-rtti -fno-exceptions -DGOOGLE_PROTOBUF_NO_RTTI '-DPROTOBUF_USE_EXCEPTIONS=0' -ffunction-sections -fdata-sections -fno-rtti -fno-exceptions -DGOOGLE_PROTOBUF_NO_RTTI '-DPROTOBUF_USE_EXCEPTIONS=0' '-fvisibility=hidden' -fvisibility-inlines-hidden '-fvisibility=hidden' -fvisibility-inlines-hidden -Werror -Wextra -Wno-missing-field-initializers '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm' -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -c mace/codegen/models/mobilenet_v2/code/tensor_data.cc -o bazel-out/armeabi-v7a-opt/bin/mace/codegen/_objs/generated_models/mace/codegen/models/mobilenet_v2/code/tensor_data.o)

Use --sandbox_debug to see verbose messages from the sandbox
terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
clang: error: unable to execute command: Aborted (core dumped)
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Android clang version 3.8.275480  (based on LLVM 3.8.275480)
Target: armv7-none-linux-android
Thread model: posix
InstalledDir: external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/tensor_data-0d9db8.cpp
clang: note: diagnostic msg: /tmp/tensor_data-0d9db8.sh
clang: note: diagnostic msg: 

********************
Target //mace/codegen:generated_models failed to build
INFO: Elapsed time: 20.985s, Critical Path: 12.99s
INFO: 1 process, linux-sandbox.
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "tools/converter.py", line 1223, in <module>
    flags.func(flags)
  File "tools/converter.py", line 904, in convert_func
    build_model_lib(configs, flags.address_sanitizer, flags.debug_mode)
  File "tools/converter.py", line 781, in build_model_lib
    debug_mode=debug_mode
  File "/home/mark/github/mace/tools/sh_commands.py", line 347, in bazel_build
    *bazel_args)
  File "/home/mark/github/py3.6/lib/python3.6/site-packages/sh.py", line 1553, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/mark/bin/bazel build //mace/codegen:generated_models --config android --cpu=armeabi-v7a --define neon=true --define opencl=true --define quantize=false --define bfloat16=false --define fp16=false --define rpcmem=true --define hexagon=false --define hta=false --define apu=false --define apu_ancient=false --config optimization --config symbol_hidden

  STDOUT:


  STDERR:




```

### Additional context
按照教程 Basic usage for Bazel users 来的，在转换模型时报的错，ndk 尝试过 r14b、r16b、r17c 都抱同样的错误。

**Comment by cychen3** [comment]
请问楼主怎么解决的？
因为什么问题呢？
