### ISSUE TITLE
type error 'RELUX'

### ISSUE THREAD

**Issue by pribadihcr** [XiaoMi/mace#85]
Hi,

when I tried to build android example, I got the following error:

```text
rudy@rchip:~/LIBRARY/mace/mace/examples/android$ ./build.sh 
~/LIBRARY/mace ~/LIBRARY/mace/mace/examples/android
------------------------------------
        Common Configuration        
------------------------------------
|        key        |    value     |
====================================
|       library_name|     mobilenet|
------------------------------------
|        target_abis| ['arm64-v8a']|
------------------------------------
|        target_socs|            []|
------------------------------------
| model_graph_format|          code|
------------------------------------
|  model_data_format|          code|
------------------------------------

* Generate mace engine creator source
Generate mace engine creator source done!

**********************************************
          Convert mobilenet_v1 model          
**********************************************

WARNING: Bazel Android NDK crosstools are based on Android NDK revision 12. The revision of the Android NDK given in android_ndk_repository rule 'androidndk' is '17.1.4828580'.
INFO: Found 1 target...
Target //mace/python/tools:converter up-to-date:
  bazel-bin/mace/python/tools/converter
INFO: Elapsed time: 0.103s, Critical Path: 0.00s
/home/rudy/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/rudy/LIBRARY/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 300, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/rudy/LIBRARY/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter.py", line 145, in main
    output_graph_def = converter.run()
  File "/home/rudy/LIBRARY/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 214, in run
    self.convert_ops()
  File "/home/rudy/LIBRARY/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 257, in convert_ops
    self._op_converters[tf_op.type](tf_op)
  File "/home/rudy/LIBRARY/mace/bazel-bin/mace/python/tools/converter.runfiles/mace/mace/python/tools/converter_tool/tensorflow_converter.py", line 438, in convert_activation
    type_arg.s = self.activation_type[tf_op.type].name
  File "/home/rudy/.cache/bazel/_bazel_rudy/445d8ca96b00154f40e14aa8c9e2c2af/execroot/mace/bazel-out/local-fastbuild/bin/mace/python/tools/converter.runfiles/com_google_protobuf/python/google/protobuf/internal/python_message.py", line 662, in field_setter
    new_value = type_checker.CheckValue(new_value)
  File "/home/rudy/.cache/bazel/_bazel_rudy/445d8ca96b00154f40e14aa8c9e2c2af/execroot/mace/bazel-out/local-fastbuild/bin/mace/python/tools/converter.runfiles/com_google_protobuf/python/google/protobuf/internal/type_checkers.py", line 109, in CheckValue
    raise TypeError(message)
TypeError: 'RELUX' has type <class 'str'>, but expected one of: ((<class 'bytes'>,),)
Traceback (most recent call last):
  File "tools/converter.py", line 1562, in <module>
    flags.func(flags)
  File "tools/converter.py", line 771, in convert_func
    convert_model(configs)
  File "tools/converter.py", line 698, in convert_model
    ",".join(model_config.get(YAMLKeyword.graph_optimize_options, [])))
  File "/home/rudy/LIBRARY/mace/tools/sh_commands.py", line 527, in gen_model_code
    _fg=True)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/rudy/anaconda3/bin/python bazel-bin/mace/python/tools/converter -u --platform=tensorflow --model_file=builds/downloads/f330dec17e45a8626cfb225ddce95051.pb --weight_file= --model_checksum=71b10f540ece33c49a7b51f5d4095fc9bd78ce46ebf0300487b2ee23d71294e6 --weight_checksum= --input_node=input --output_node=MobilenetV1/Predictions/Reshape_1 --runtime=cpu+gpu --template=mace/python/tools --model_tag=mobilenet_v1 --input_shape=1,224,224,3 --dsp_mode=0 --embed_model_data=True --winograd=0 --obfuscate=0 --output_dir=mace/codegen/models/mobilenet_v1 --model_graph_format=code --data_type=fp16_fp32 --graph_optimize_options=

  STDOUT:
```

**Comment by yejw5** [comment]
Can you try again in python2 environment?

**Comment by pribadihcr** [comment]
oh ok. its work but there is another error that I think no realted with python version.

```text
************************************************
          Model mobilenet_v2 converted          
************************************************

******************************************
          Building model library          
******************************************

* Build //mace/codegen:generated_models with ABI arm64-v8a
WARNING: Bazel Android NDK crosstools are based on Android NDK revision 12. The revision of the Android NDK given in android_ndk_repository rule 'androidndk' is '17.1.4828580'.
ERROR: /home/rudy/LIBRARY/mace/mace/BUILD:27:1: //mace:neon_enabled: no such attribute 'define_values' in 'config_setting' rule.
ERROR: /home/rudy/LIBRARY/mace/mace/BUILD:27:1: //mace:neon_enabled: missing value for mandatory attribute 'values' in 'config_setting' rule.
ERROR: /home/rudy/LIBRARY/mace/mace/BUILD:35:1: //mace:hexagon_enabled: no such attribute 'define_values' in 'config_setting' rule.
ERROR: /home/rudy/LIBRARY/mace/mace/BUILD:47:1: //mace:openmp_enabled: no such attribute 'define_values' in 'config_setting' rule.
ERROR: /home/rudy/LIBRARY/mace/mace/BUILD:47:1: //mace:openmp_enabled: missing value for mandatory attribute 'values' in 'config_setting' rule.
ERROR: /home/rudy/LIBRARY/mace/mace/core/BUILD:19:1: Target '//mace:android' contains an error and its package is in error and referenced by '//mace/core:core'.
ERROR: /home/rudy/LIBRARY/mace/mace/core/BUILD:19:1: Target '//mace:hexagon_enabled' contains an error and its package is in error and referenced by '//mace/core:core'.
ERROR: /home/rudy/LIBRARY/mace/mace/core/BUILD:19:1: Target '//mace:openmp_enabled' contains an error and its package is in error and referenced by '//mace/core:core'.
ERROR: /home/rudy/LIBRARY/mace/mace/core/BUILD:19:1: Target '//mace:android' contains an error and its package is in error and referenced by '//mace/core:core'.
ERROR: /home/rudy/LIBRARY/mace/mace/core/BUILD:19:1: Target '//mace:hexagon_enabled' contains an error and its package is in error and referenced by '//mace/core:core'.
ERROR: /home/rudy/LIBRARY/mace/mace/core/BUILD:19:1: Target '//mace:neon_enabled' contains an error and its package is in error and referenced by '//mace/core:core'.
ERROR: /home/rudy/LIBRARY/mace/mace/core/BUILD:19:1: Target '//mace:android' contains an error and its package is in error and referenced by '//mace/core:core'.
ERROR: /home/rudy/LIBRARY/mace/mace/core/BUILD:19:1: Target '//mace:hexagon_enabled' contains an error and its package is in error and referenced by '//mace/core:core'.
ERROR: /home/rudy/LIBRARY/mace/mace/core/BUILD:19:1: Target '//mace:android' contains an error and its package is in error and referenced by '//mace/core:core'.
ERROR: /home/rudy/LIBRARY/mace/mace/core/BUILD:19:1: Target '//mace:android' contains an error and its package is in error and referenced by '//mace/core:core'.
ERROR: /home/rudy/LIBRARY/mace/mace/core/BUILD:19:1: Target '//mace:hexagon_enabled' contains an error and its package is in error and referenced by '//mace/core:core'.
ERROR: Analysis of target '//mace/codegen:generated_models' failed; build aborted.
INFO: Elapsed time: 0.337s
Traceback (most recent call last):
  File "tools/converter.py", line 1562, in <module>
    flags.func(flags)
  File "tools/converter.py", line 774, in convert_func
    build_model_lib(configs, flags.address_sanitizer)
  File "tools/converter.py", line 743, in build_model_lib
    address_sanitizer=address_sanitizer
  File "/home/rudy/LIBRARY/mace/tools/sh_commands.py", line 318, in bazel_build
    *bazel_args)
  File "/usr/local/lib/python2.7/dist-packages/sh.py", line 1413, in __call__
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/bazel build //mace/codegen:generated_models --config android --cpu=arm64-v8a --define neon=true --define openmp=true --define hexagon=false --config optimization

  STDOUT:


  STDERR:
```

**Comment by yejw5** [comment]
What's your NDK version? It is adviced to r15b, r15c or r16b.

**Comment by yejw5** [comment]
Bazel haven't support with NDK 17.

**Comment by pribadihcr** [comment]
Hi @yejw5,

Yes. I try to change with r15c. Its work, and got new error:

```text
INFO: Build completed successfully, 2 total actions
build static lib for linux-x86-64
INFO: Analysed target //mace:libmace_static (0 packages loaded).
INFO: Found 1 target...
Target //mace:libmace_static up-to-date:
  bazel-genfiles/mace/libmace.a
INFO: Elapsed time: 27.173s, Critical Path: 6.91s
INFO: 90 processes: 89 linux-sandbox, 1 local.
INFO: Build completed successfully, 112 total actions
LIB PATH: builds/lib
INCLUDE FILE PATH: builds/include/mace/public
~/LIBRARY/mace/mace/examples/android
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type FileHasher using BuildSessionScopeServices.createFileSnapshotter().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s

```

**Comment by yejw5** [comment]
Is this the newest code?

**Comment by pribadihcr** [comment]
yes. I re run with sudo ./build.sh, got this error:

```text
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/basic_string.h:240: undefined reference to `std::string::_Rep::_S_empty_rep_storage'
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/basic_string.h:249: undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
  ../../../../src/main/cpp/lib/arm64-v8a/libmace.a(runtime_failure_mock.o): In function `mace::(anonymous namespace)::GetRuntimeFailureRatioFromEnv()':
  /proc/self/cwd/mace/core/runtime_failure_mock.cc:29: undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
  /proc/self/cwd/mace/core/runtime_failure_mock.cc:30: undefined reference to `std::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >::basic_istringstream(std::string const&, std::_Ios_Openmode)'
  ../../../../src/main/cpp/lib/arm64-v8a/libmace.a(runtime_failure_mock.o): In function `std::istream::operator>>(float&)':
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/istream:215: undefined reference to `std::istream& std::istream::_M_extract<float>(float&)'
  ../../../../src/main/cpp/lib/arm64-v8a/libmace.a(runtime_failure_mock.o): In function `~basic_istringstream':
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/sstream:338: undefined reference to `VTT for std::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >'
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/sstream:338: undefined reference to `VTT for std::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >'
  ../../../../src/main/cpp/lib/arm64-v8a/libmace.a(runtime_failure_mock.o): In function `~basic_stringbuf':
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/sstream.tcc:272: undefined reference to `vtable for std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >'
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/sstream.tcc:272: undefined reference to `vtable for std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >'
  ../../../../src/main/cpp/lib/arm64-v8a/libmace.a(runtime_failure_mock.o): In function `std::string::_Rep::_M_dispose(std::allocator<char> const&)':
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/basic_string.h:240: undefined reference to `std::string::_Rep::_S_empty_rep_storage'
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/basic_string.h:240: undefined reference to `std::string::_Rep::_S_empty_rep_storage'
  ../../../../src/main/cpp/lib/arm64-v8a/libmace.a(runtime_failure_mock.o): In function `~basic_streambuf':
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/streambuf:198: undefined reference to `vtable for std::basic_streambuf<char, std::char_traits<char> >'
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/streambuf:198: undefined reference to `vtable for std::basic_streambuf<char, std::char_traits<char> >'
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/streambuf:198: undefined reference to `std::locale::~locale()'
  ../../../../src/main/cpp/lib/arm64-v8a/libmace.a(runtime_failure_mock.o): In function `~basic_ios':
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/basic_ios.h:276: undefined reference to `std::ios_base::~ios_base()'
  ../../../../src/main/cpp/lib/arm64-v8a/libmace.a(runtime_failure_mock.o): In function `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)':
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/ostream:535: undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long)'
  ../../../../src/main/cpp/lib/arm64-v8a/libmace.a(runtime_failure_mock.o): In function `std::string::_Rep::_M_dispose(std::allocator<char> const&)':
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/basic_string.h:249: undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/basic_string.h:249: undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
  ../../../../src/main/cpp/lib/arm64-v8a/libmace.a(runtime_failure_mock.o): In function `~basic_istringstream':
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/sstream:338: undefined reference to `VTT for std::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >'
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/sstream:338: undefined reference to `VTT for std::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >'
  ../../../../src/main/cpp/lib/arm64-v8a/libmace.a(runtime_failure_mock.o): In function `~basic_stringbuf':
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/sstream.tcc:272: undefined reference to `vtable for std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >'
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/sstream.tcc:272: undefined reference to `vtable for std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >'
  ../../../../src/main/cpp/lib/arm64-v8a/libmace.a(runtime_failure_mock.o): In function `std::string::_Rep::_M_dispose(std::allocator<char> const&)':
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/basic_string.h:240: undefined reference to `std::string::_Rep::_S_empty_rep_storage'
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/basic_string.h:240: undefined reference to `std::string::_Rep::_S_empty_rep_storage'
  ../../../../src/main/cpp/lib/arm64-v8a/libmace.a(runtime_failure_mock.o): In function `~basic_streambuf':
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/streambuf:198: undefined reference to `vtable for std::basic_streambuf<char, std::char_traits<char> >'
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/streambuf:198: undefined reference to `vtable for std::basic_streambuf<char, std::char_traits<char> >'
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/streambuf:198: undefined reference to `std::locale::~locale()'
  ../../../../src/main/cpp/lib/arm64-v8a/libmace.a(runtime_failure_mock.o): In function `~basic_ios':
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/basic_ios.h:276: undefined reference to `std::ios_base::~ios_base()'
  ../../../../src/main/cpp/lib/arm64-v8a/libmace.a(runtime_failure_mock.o): In function `std::string::_Rep::_M_dispose(std::allocator<char> const&)':
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/basic_string.h:249: undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/basic_string.h:240: undefined reference to `std::string::_Rep::_S_empty_rep_storage'
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/basic_string.h:240: undefined reference to `std::string::_Rep::_S_empty_rep_storage'
  /proc/self/cwd/external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/basic_string.h:249: undefined reference to `std::string::_Rep::_M_destroy(std::allocator<char> const&)'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 47s
39 actionable tasks: 36 executed, 3 up-to-date

```

**Comment by yejw5** [comment]
@lee-bin could you help with this issue?

**Comment by liyinhgqw** [comment]
Close it. You can reopen it if issue still exists.
